INSERT INTO PCUSUARI@DBLCLOUD (
    CODFILIAL,
    CODUSUR,
    NOME,
    SENHA,
    TIPOVEND,
    PERCENT,
    PERCENT2,
    ENDERECO,
    CIDADE,
    ESTADO,
    CEP,
    TELEFONE1,
    TELEFONE2,
    CPF,
    CI,
    FAX,
    BIP,
    BLOQUEIO,
    DTINICIO,
    DTTERMINO,
    MOTIVO,
    DTNASC,
    FIRMA,
    CGC,
    BAIRRO,
    CODSUPERVISOR,
    EMAIL,
    OBS1,
    OBS2
)
SELECT
    P.CODFILIAL,
    P.CODUSUR,
    P.NOME,
    P.SENHA,
    P.TIPOVEND,
    P.PERCENT,
    P.PERCENT2,
    P.ENDERECO,
    P.CIDADE,
    P.ESTADO,
    P.CEP,
    P.TELEFONE1,
    P.TELEFONE2,
    P.CPF,
    P.CI,
    P.FAX,
    P.BIP,
    P.BLOQUEIO,
    P.DTINICIO, --FORMATO DD/MM/AAAA
    P.DTTERMINO, --FORMATO DD/MM/AAAA
    P.MOTIVO,
    P.DTNASC, --FORMATO DD/MM/AAAA
    P.FIRMA,
    P.CGC,
    P.BAIRRO,
    CASE 
        WHEN P.CODSUPERVISOR NOT IN (1,8,9)
            THEN 999
        ELSE P.CODSUPERVISOR
    END AS CODSUPERVISOR,
    P.EMAIL,
    P.OBS1,
    P.OBS2
FROM PCUSUARI P
WHERE NOT EXISTS (
    SELECT 1
    FROM PCUSUARI@DBLCLOUD D
    WHERE D.CODUSUR = P.CODUSUR
);