INSERT INTO PCMARCA@DBLCLOUD(
	CODMARCA,
	MARCA,
	ATIVO,
	CODADWORDS,
	DESCRICAOECOMMERCE,
	CODCAMPLOMADEE,
	TITULO,
	DTULTALTER,
	DTCADASTRO,
	CODCOMPRADOR,
	DTALTERC5
)
SELECT
	P.CODMARCA,
	P.MARCA,
	P.ATIVO,
	P.CODADWORDS,
	P.DESCRICAOECOMMERCE,
	P.CODCAMPLOMADEE,
	P.TITULO,
	P.DTULTALTER,
	P.DTCADASTRO,
	P.CODCOMPRADOR,
	P.DTALTERC5
FROM PCMARCA P
INNER JOIN (
	SELECT DISTINCT
	    P.CODMARCA
	FROM PCPRODUT@DBLCLOUD P
	WHERE P.CODMARCA IS NOT NULL
) M
	ON M.CODMARCA = P.CODMARCA