INSERT INTO PCPRACA@DBLCLOUD (
	CODPRACA,
	PRACA,
	NUMREGIAO,
	ROTA,
	SEQROTA
)
WITH PCPREST_AUX AS (
    SELECT DISTINCT 
        PCPREST.CODCLI, 
        PCPREST.CODFILIAL 
    FROM PCPREST 
    WHERE PCPREST.CODFILIAL IN (4, 8)
),
DADOS AS (
    SELECT
        PCCLIENT.CODCLI,
        PCCLIENT.CODPRACA,        
        PCCLIENT.CODUSUR1,
        PCCLIENT.CODUSUR2,
        CASE 
            WHEN EXISTS (
                SELECT 1
                FROM PCUSUARI
                WHERE PCUSUARI.CODUSUR = PCCLIENT.CODUSUR1
                  AND PCUSUARI.CODSUPERVISOR IN (1, 8, 9)
            )
            THEN (
                SELECT PCUSUARI.CODSUPERVISOR
                FROM PCUSUARI
                WHERE PCUSUARI.CODUSUR = PCCLIENT.CODUSUR1
            ) 

            WHEN EXISTS (
                SELECT 1
                FROM PCUSUARI
                WHERE PCUSUARI.CODUSUR = PCCLIENT.CODUSUR2
                  AND PCUSUARI.CODSUPERVISOR IN (1, 8, 9)
            )
            THEN (
                SELECT PCUSUARI.CODSUPERVISOR
                FROM PCUSUARI
                WHERE PCUSUARI.CODUSUR = PCCLIENT.CODUSUR2
            ) 

            WHEN EXISTS (
                SELECT 1
                FROM PCPREST_AUX
                WHERE PCPREST_AUX.CODCLI = PCCLIENT.CODCLI
            )
            THEN 999

            ELSE NULL
        END AS CODSUPERVISOR
        
    FROM PCCLIENT
)
SELECT DISTINCT 
	PCPRACA.CODPRACA,
	PCPRACA.PRACA,
	PCPRACA.NUMREGIAO,
	PCPRACA.ROTA,
	PCPRACA.SEQROTA
FROM PCPRACA
WHERE PCPRACA.CODPRACA IN (
    SELECT DISTINCT DADOS.CODPRACA
    FROM DADOS
    WHERE DADOS.CODSUPERVISOR IS NOT NULL
)
AND NOT EXISTS (
    SELECT 1
    FROM PCPRACA@DBLCLOUD DEST
    WHERE DEST.CODPRACA = PCPRACA.CODPRACA
);