INSERT INTO PCCONTATO@DBLCLOUD (
	CODCLI,
	NOMECONTATO,
	TIPOCONTATO,
	CGCCPF,
	DTNASCIMENTO,
	AUTORCH,
	CODCONTATO,
	CARGO,
	EMAIL,
	TELEFONE,
	CELULAR,
	HOBBIE,
	OBS
)
-- Tabela complementar de Contas a Receber de Clientes para relacionar com filial
WITH PCPREST_AUX AS (
	SELECT DISTINCT 
		PCPREST.CODCLI, 
		PCPREST.CODFILIAL 
	FROM PCPREST 
	WHERE 
		PCPREST.CODFILIAL IN (4, 8)
),
DADOS AS (
	SELECT
		PCCLIENT.CODCLI,	
		PCCLIENT.CODUSUR1,
		PCCLIENT.CODUSUR2,
		CASE 
			WHEN EXISTS( SELECT PCUSUARI.CODUSUR FROM PCUSUARI WHERE PCUSUARI.CODUSUR = PCCLIENT.CODUSUR1 AND PCUSUARI.CODSUPERVISOR IN (1, 8, 9))
			THEN (SELECT PCUSUARI.CODSUPERVISOR FROM  PCUSUARI WHERE PCUSUARI.CODUSUR = PCCLIENT.CODUSUR1) 
			WHEN EXISTS( SELECT PCUSUARI.CODUSUR FROM PCUSUARI WHERE PCUSUARI.CODUSUR = PCCLIENT.CODUSUR2 AND PCUSUARI.CODSUPERVISOR IN (1, 8, 9))
			THEN (SELECT PCUSUARI.CODSUPERVISOR FROM  PCUSUARI WHERE PCUSUARI.CODUSUR = PCCLIENT.CODUSUR2) 
			WHEN EXISTS( SELECT 1 FROM PCPREST_AUX WHERE PCPREST_AUX.CODCLI = PCCLIENT.CODCLI )
			THEN 999
			ELSE NULL
		END AS CODSUPERVISOR
	FROM PCCLIENT
)
SELECT DISTINCT 
	PCCONTATO.CODCLI,
	PCCONTATO.NOMECONTATO,
	PCCONTATO.TIPOCONTATO,
	PCCONTATO.CGCCPF,
	PCCONTATO.DTNASCIMENTO,
	PCCONTATO.AUTORCH,
	PCCONTATO.CODCONTATO,
	PCCONTATO.CARGO,
	PCCONTATO.EMAIL,
	PCCONTATO.TELEFONE,
	PCCONTATO.CELULAR,
	PCCONTATO.HOBBIE,
	PCCONTATO.OBS
FROM PCCONTATO
WHERE PCCONTATO.CODCLI IN (	
	SELECT DISTINCT DADOS.CODCLI FROM DADOS WHERE DADOS.CODSUPERVISOR IS NOT NULL
)