	INSERT INTO PCNCM@DBLCLOUD (
		CODNCM,
		DESCRICAO,
		CAPITULO,
		CODEX,
		DTINCLUSAO,
		DTEXCLUSAO,
		CODUSURINCLUSAO,
		CODUSUREXCLUSAO,
		CODNCMEX
	)
	SELECT
		PCNCM.CODNCM,
		PCNCM.DESCRICAO,
		PCNCM.CAPITULO,
		PCNCM.CODEX,
		PCNCM.DTINCLUSAO,
		PCNCM.DTEXCLUSAO,
		PCNCM.CODUSURINCLUSAO,
		PCNCM.CODUSUREXCLUSAO,
		PCNCM.CODNCMEX
	FROM PCNCM