INSERT INTO PCEMBALAGEM@DBLCLOUD (
	CODAUXILIAR,
	CODPROD,
	EMBALAGEM,
	UNIDADE,
	QTUNIT,
	PTABELA,
	PVENDA,
	DTULTALTPTABELA,
	DTULTALTPVENDA,
	CODFILIAL,
	PTABELAATAC,
	PVENDAATAC,
	PRECOANTERIORATAC,
	DESCRICAOECF,
	ENVIABALANCA,
	EXPORTACAMPO,
	TIPOEMBALAGEM,
	ENVIAFV,
	MARGEM,
	MARGEMIDEALATAC,
	QTMINIMAATACADO
)
SELECT
	PCEMBALAGEM.CODAUXILIAR,
	PCEMBALAGEM.CODPROD,
	PCEMBALAGEM.EMBALAGEM,
	PCEMBALAGEM.UNIDADE,
	PCEMBALAGEM.QTUNIT, --NÃO PODE SER NULO, MIN 1
	PCEMBALAGEM.PTABELA,
	PCEMBALAGEM.PVENDA,
	PCEMBALAGEM.DTULTALTPTABELA, --FORMATO DD/MM/AAAA
	PCEMBALAGEM.DTULTALTPVENDA, --FORMATO DD/MM/AAAA
	PCEMBALAGEM.CODFILIAL,
	PCEMBALAGEM.PTABELAATAC,
	PCEMBALAGEM.PVENDAATAC,
	PCEMBALAGEM.PRECOANTERIORATAC,
	PCEMBALAGEM.DESCRICAOECF,
	PCEMBALAGEM.ENVIABALANCA,
	PCEMBALAGEM.EXPORTACAMPO,
	PCEMBALAGEM.TIPOEMBALAGEM,
	PCEMBALAGEM.ENVIAFV,
	PCEMBALAGEM.MARGEM,
	PCEMBALAGEM.MARGEMIDEALATAC,
	PCEMBALAGEM.QTMINIMAATACADO
FROM PCEMBALAGEM