INSERT INTO PCEST@DBLCLOUD (
	CODFILIAL,
	CODPROD,
	QTEST,
	DTULTENT,
	QTULTENT,
	CUSTOULTENT,
	QTESTGER,
	CUSTOCONT,
	CUSTOREAL,
	VALORULTENT,
	QTVENDMES,
	QTVENDMES1,
	QTVENDMES2,
	QTVENDMES3
)
WITH PRODUT AS (
	SELECT
	    P.CODPROD
	FROM PCPRODUT P
	INNER JOIN (
	    SELECT
	        CODPROD
	    FROM PCMOV
	    WHERE CODFILIAL IN (4, 8)
	    GROUP BY CODPROD
	) M
	    ON M.CODPROD = P.CODPROD
)
SELECT DISTINCT
	P.CODFILIAL,
	P.CODPROD,
	P.QTEST,
	P.DTULTENT,
	P.QTULTENT,
	P.CUSTOULTENT,
	P.QTESTGER,
	P.CUSTOCONT,
	P.CUSTOREAL,
	P.VALORULTENT,
	P.QTVENDMES,
	P.QTVENDMES1,
	P.QTVENDMES2,
	P.QTVENDMES3
FROM PCEST P
INNER JOIN PRODUT M
	ON M.CODPROD = P.CODPROD
WHERE CODFILIAL IN (4, 8)