INSERT INTO PCTABTRIB@DBLCLOUD (
    CODFILIALINTEGRACAO,
	DTALTERC5,
	IDENTIFICARTRIBIPI,
	IDENTIFICARTRIBPISCOFINS,
	IDENTIFICARTRIB,
	CODPROD,
	CODFILIALNF,
	UFDESTINO,
	CODST,
	DTULTALTER,
	CODTRIBPISCOFINS
)
WITH TRIBUT_C AS (
	SELECT DISTINCT
		CODST 
	FROM PCTRIBUT
	WHERE PCTRIBUT.MENSAGEM LIKE 'F4%'
		OR PCTRIBUT.MENSAGEM LIKE 'F8%'
)
SELECT
	M.CODFILIALINTEGRACAO,
	M.DTALTERC5,
	M.IDENTIFICARTRIBIPI,
	M.IDENTIFICARTRIBPISCOFINS,
	M.IDENTIFICARTRIB,
	M.CODPROD,
	M.CODFILIALNF,
	M.UFDESTINO,
	M.CODST,
	M.DTULTALTER,
	M.CODTRIBPISCOFINS
FROM PCTABTRIB M
LEFT JOIN TRIBUT_C
	ON TRIBUT_C.CODST = M.CODST
WHERE TRIBUT_C.CODST IS NOT NULL