INSERT /*+ DRIVING_SITE(PCCORTEI) */ INTO PCCORTEI@DBLCLOUD(
    CODPROD, QTSEPARADA, QTCORTADA, DATA, NUMCAR, CODFUNC, NUMPED, PVENDA,
    CODFUNCCONF, CODFUNCSEP, CODFILIAL, QTORIG, QTFALTA, MOTIVO,
    DTFINALCHECKOUT, HORA, MINUTO, CODCLI, CODUSUR, CODROTINA,
    CONDVENDA, CODEMITENTEPED, NUMLOTE, NUMSEQ, TIPOCORTE
)
SELECT
    PCCORTEI.CODPROD, PCCORTEI.QTSEPARADA, PCCORTEI.QTCORTADA, PCCORTEI.DATA,
    PCCORTEI.NUMCAR, PCCORTEI.CODFUNC, PCCORTEI.NUMPED, PCCORTEI.PVENDA,
    PCCORTEI.CODFUNCCONF, PCCORTEI.CODFUNCSEP, PCCORTEI.CODFILIAL, PCCORTEI.QTORIG,
    PCCORTEI.QTFALTA, PCCORTEI.MOTIVO, PCCORTEI.DTFINALCHECKOUT, PCCORTEI.HORA,
    PCCORTEI.MINUTO, PCCORTEI.CODCLI, PCCORTEI.CODUSUR, PCCORTEI.CODROTINA,
    PCCORTEI.CONDVENDA, PCCORTEI.CODEMITENTEPED, PCCORTEI.NUMLOTE, PCCORTEI.NUMSEQ,
    PCCORTEI.TIPOCORTE
FROM PCCORTEI
WHERE EXISTS (
    SELECT /*+ NL_SJ */ 1
    FROM PCPEDC@DBLCLOUD D
    WHERE D.NUMPED = PCCORTEI.NUMPED
);