INSERT /*+ DRIVING_SITE(PCHISTCOB) */ INTO PCHISTCOB@DBLCLOUD (
	DATA,
	CODFUNC,
	CODCLI,
	TELCOB,
	CONTATO,
	OBS1,
	OBS2,
	OBS3,
	OBS4,
	DTPROXCONTATO,
	TIPOCONTATO,
	CODFORNEC,
	HORAPROXCONTATO,
	MINUTOPROXCONTATO,
	OBS5,
	RESULTADOCOB,
	AGENDARNOVOCONTATO,
	TIPOACOMPANHAMENTO,
	CODSTATUSCOB,
	NUMVERBA,
	NUMREGCOB
)
SELECT
	PCHISTCOB.DATA,
	PCHISTCOB.CODFUNC,
	PCHISTCOB.CODCLI,
	PCHISTCOB.TELCOB,
	PCHISTCOB.CONTATO,
	PCHISTCOB.OBS1,
	PCHISTCOB.OBS2,
	PCHISTCOB.OBS3,
	PCHISTCOB.OBS4,
	PCHISTCOB.DTPROXCONTATO,
	PCHISTCOB.TIPOCONTATO,
	PCHISTCOB.CODFORNEC,
	PCHISTCOB.HORAPROXCONTATO,
	PCHISTCOB.MINUTOPROXCONTATO,
	PCHISTCOB.OBS5,
	PCHISTCOB.RESULTADOCOB,
	PCHISTCOB.AGENDARNOVOCONTATO,
	PCHISTCOB.TIPOACOMPANHAMENTO,
	PCHISTCOB.CODSTATUSCOB,
	PCHISTCOB.NUMVERBA,
	PCHISTCOB.NUMREGCOB
FROM PCHISTCOB 
WHERE EXISTS (
	SELECT *
	FROM PCCLIENT@DBLCLOUD CLIENTES
	WHERE CLIENTES.CODCLI = PCHISTCOB.CODCLI
) AND NOT EXISTS (
	SELECT /*+ NL_SJ */ 1
	FROM PCHISTCOB@DBLCLOUD DEST
	WHERE DEST.DATA = PCHISTCOB.DATA
	  AND DEST.CODCLI = PCHISTCOB.CODCLI
	  AND DEST.CODFUNC = PCHISTCOB.CODFUNC
)