INSERT /*+ DRIVING_SITE(PCLOGALTCLI) */ INTO PCLOGALTCLI@DBLCLOUD ( 
	MATRICULA,
	CODCLI,
	DTALTERACAO,
	ROTINA,
	OBS,
	CAMPO,
	VALORANT,
	VALORATU,
	CODFUNC
)
SELECT
	PCLOGALTCLI.MATRICULA,
	PCLOGALTCLI.CODCLI,
	PCLOGALTCLI.DTALTERACAO,
	PCLOGALTCLI.ROTINA,
	PCLOGALTCLI.OBS,
	PCLOGALTCLI.CAMPO,
	PCLOGALTCLI.VALORANT,
	PCLOGALTCLI.VALORATU,
	PCLOGALTCLI.CODFUNC
FROM PCLOGALTCLI
WHERE EXISTS (
	SELECT *
	FROM PCCLIENT@DBLCLOUD CLIENTES
	WHERE CLIENTES.CODCLI = PCLOGALTCLI.CODCLI
) AND NOT EXISTS (
	SELECT /*+ NL_SJ */ 1
	FROM PCLOGALTCLI@DBLCLOUD DEST
	WHERE DEST.MATRICULA = PCLOGALTCLI.MATRICULA
	  AND DEST.CODCLI = PCLOGALTCLI.CODCLI
	  AND DEST.DTALTERACAO = PCLOGALTCLI.DTALTERACAO
	  AND DEST.ROTINA = PCLOGALTCLI.ROTINA
	  AND DEST.CAMPO = PCLOGALTCLI.CAMPO
	)