INSERT /*+ DRIVING_SITE(PCTRIBENTRADA) */ INTO PCTRIBENTRADA@DBLCLOUD(
	NCM,
	CODFILIAL,
	UFORIGEM,
	TIPOFORNEC,
	CODFIGURA,
	CODTRIBPISCOFINS,
	CODEXCECAOPISCOFINS,
	CODFUNCCAD,
	DTCADASTRO,
	OBS
)
WITH NCM_P AS (
	SELECT DISTINCT 
		SUBSTR(P.CODNCMEX, 1, 
				INSTR(P.CODNCMEX, '.')
			) AS CODNCMEX
	FROM PCNCM P
),
PCTRIBFIGURA_C AS (
	SELECT DISTINCT
		CODFIGURA 
	FROM PCTRIBFIGURA@DBLCLOUD
)
SELECT
	M.NCM,
	M.CODFILIAL,
	M.UFORIGEM,
	M.TIPOFORNEC,
	M.CODFIGURA,
	M.CODTRIBPISCOFINS,
	M.CODEXCECAOPISCOFINS,
	M.CODFUNCCAD,
	M.DTCADASTRO,
	M.OBS
FROM PCTRIBENTRADA M
LEFT JOIN NCM_P P
	ON P.CODNCMEX = M.NCM
LEFT JOIN PCTRIBFIGURA_C N
	ON N.CODFIGURA = M.CODFIGURA
WHERE P.CODNCMEX IS NOT NULL
	AND N.CODFIGURA IS NOT NULL
	AND M.CODFILIAL IN (4, 8)
AND NOT EXISTS (
	SELECT /*+ NL_SJ */ 1
	FROM PCTRIBENTRADA@DBLCLOUD DEST
	WHERE DEST.NCM = M.NCM
	  AND DEST.CODFILIAL = M.CODFILIAL
	  AND DEST.UFORIGEM = M.UFORIGEM
	  AND DEST.TIPOFORNEC = M.TIPOFORNEC
	  AND DEST.CODFIGURA = M.CODFIGURA
	)