    SELECT * FROM PCFILIAL;

    SELECT * FROM PCUSUARI;

    SELECT * FROM PCCLIENT;

    SELECT * FROM PCFORNEC;

    SELECT * FROM PCDEPTO;

    SELECT * FROM PCPRODUT;

    SELECT * FROM PCMARCA;

    SELECT * FROM PCPREST;

    SELECT * FROM PCPRACA;

    SELECT * FROM PCCONTATO;

    SELECT * FROM PCSECAO;

    SELECT * FROM PCTRIBUT;

    SELECT * FROM PCTRIBFIGURA;

    SELECT * FROM PCVEICUL;

    SELECT * FROM PCSUPERV;

    SELECT * FROM PCNCM;

    SELECT * FROM PCEMBALAGEM;

    SELECT * FROM PCLANC;

    SELECT * FROM PCEST;

    SELECT * FROM PCTABPR;

    SELECT * FROM PCREGIAO;

    SELECT * FROM PCTRIBENTRADA;

    SELECT * FROM PCEMPR;