-- FAZ A INCLUSÃO DO CODIGOD DO TURNO NO DE/PARA TURMAS

IF OBJECT_ID('AJUSTE_ZDEPARATURMAS') IS NOT NULL
   DROP TABLE AJUSTE_ZDEPARATURMAS;

SELECT (SELECT ST.TURNO FROM SOPHIA.TURMAS AS ST WHERE ST.CODIGO = ZDEPARA_TURMAS.CODIGO_DE) AS CODTURNO_DE,* INTO AJUSTE_ZDEPARATURMAS FROM ZDEPARA_TURMAS;

IF OBJECT_ID('ZDEPARA_TURMAS') IS NOT NULL
   DROP TABLE ZDEPARA_TURMAS;

SELECT * INTO ZDEPARA_TURMAS FROM AJUSTE_ZDEPARATURMAS;

SELECT * FROM ZDEPARA_TURMAS;