
IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[SP_GENERATEINSERT]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1)
   DROP PROCEDURE [DBO].[SP_GENERATEINSERT]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO


CREATE PROCEDURE SP_GENERATEINSERT
@TABLENAME VARCHAR(200),
@NAMEDESTINO VARCHAR(200)
AS
BEGIN

PRINT ''
--PRINT 'SET IDENTITY_INSERT ' + @TABLENAME + ' ON'
--PRINT 'GO'
PRINT ''

DECLARE @STRSQL VARCHAR(MAX)
DECLARE @COLUMNLIST VARCHAR(MAX)
DECLARE @COLUMNLISTINONE VARCHAR(MAX)
DECLARE @COLUMNNAME VARCHAR(MAX)
DECLARE @COLUMNTYPE INT
DECLARE @ID AS INTEGER

SELECT @ID = ID FROM SYSOBJECTS WHERE TYPE = 'U' AND NAME = @TABLENAME
SET @COLUMNLIST = ''
SET @COLUMNLISTINONE = ''

DECLARE CCURSOR CURSOR FOR
SELECT NAME, XTYPE
FROM SYSCOLUMNS
WHERE ID = @ID

OPEN CCURSOR
FETCH NEXT FROM CCURSOR INTO @COLUMNNAME, @COLUMNTYPE
WHILE @@FETCH_STATUS = 0
BEGIN

SELECT @COLUMNLIST = @COLUMNLIST + @COLUMNNAME + ', '

IF (@COLUMNTYPE = (SELECT XTYPE FROM SYSTYPES WHERE NAME = 'INT')) OR (@COLUMNTYPE = (SELECT XTYPE FROM SYSTYPES WHERE NAME = 'FLOAT'))
BEGIN
	SELECT @COLUMNLISTINONE = @COLUMNLISTINONE
	SELECT @COLUMNLISTINONE = @COLUMNLISTINONE + ' LTRIM(RTRIM(REPLACE(ISNULL(CONVERT(VARCHAR(MAX), ' + @COLUMNNAME + '),''{|NULL_VALUE|}''),'''''''','''''''''''')))'
END
ELSE
BEGIN
	SELECT @COLUMNLISTINONE = @COLUMNLISTINONE + '''''''''' + ' + '
	SELECT @COLUMNLISTINONE = @COLUMNLISTINONE + ' LTRIM(RTRIM(REPLACE(ISNULL(CONVERT(VARCHAR(MAX), ' + @COLUMNNAME + '),''''),'''''''','''''''''''')))'
END

IF (@COLUMNTYPE = (SELECT XTYPE FROM SYSTYPES WHERE NAME = 'INT')) OR (@COLUMNTYPE = (SELECT XTYPE FROM SYSTYPES WHERE NAME = 'FLOAT'))
BEGIN
SELECT @COLUMNLISTINONE = @COLUMNLISTINONE
END
ELSE
BEGIN
SELECT @COLUMNLISTINONE = @COLUMNLISTINONE + ' + ' + ''''''''''
END

SELECT @COLUMNLISTINONE = @COLUMNLISTINONE + ' + '', '' + '

FETCH NEXT FROM CCURSOR INTO @COLUMNNAME, @COLUMNTYPE
END --WHILE @@FETCH_STATUS = 0
CLOSE CCURSOR

DEALLOCATE CCURSOR

SET @COLUMNLIST = LEFT(@COLUMNLIST,LEN(@COLUMNLIST)-1)
SET @COLUMNLISTINONE = LEFT(@COLUMNLISTINONE,LEN(@COLUMNLISTINONE)-9)

SET @STRSQL = ''
SET @STRSQL = @STRSQL + ' DECLARE @ALLVALUES VARCHAR(8000)'
SET @STRSQL = @STRSQL + ' SET @ALLVALUES = '''''
SET @STRSQL = @STRSQL + ' DECLARE CCURSOR CURSOR FOR '
SET @STRSQL = @STRSQL + ' SELECT ' + @COLUMNLISTINONE + ' FROM ' + @TABLENAME
SET @STRSQL = @STRSQL + ' OPEN CCURSOR '
SET @STRSQL = @STRSQL + ' FETCH NEXT FROM CCURSOR INTO @ALLVALUES '
SET @STRSQL = @STRSQL + ' WHILE @@FETCH_STATUS = 0 '
SET @STRSQL = @STRSQL + ' BEGIN '
SET @STRSQL = @STRSQL + ' PRINT ''INSERT INTO ' + @NAMEDESTINO + ' (' + @COLUMNLIST + ') VALUES ('' + REPLACE(@ALLVALUES, ''{|NULL_VALUE|}'', ''NULL'') + '')'' '
SET @STRSQL = @STRSQL + ' FETCH NEXT FROM CCURSOR INTO @ALLVALUES '
SET @STRSQL = @STRSQL + ' END '
SET @STRSQL = @STRSQL + ' CLOSE CCURSOR '
SET @STRSQL = @STRSQL + ' DEALLOCATE CCURSOR '
EXEC (@STRSQL )

PRINT ''
--PRINT 'SET IDENTITY_INSERT ' + @TABLENAME + ' OFF'
--PRINT 'GO'

END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO
