IF OBJECT_ID('ZPPESSOA_GERAL') IS NOT NULL
   DROP TABLE ZPPESSOA_GERAL
;

IF OBJECT_ID('dbo.fn_RemoveAcentos', 'FN') IS NOT NULL
    DROP FUNCTION dbo.fn_RemoveAcentos;
GO

CREATE FUNCTION dbo.fn_RemoveAcentos (
    @Texto NVARCHAR(MAX)
) RETURNS NVARCHAR(MAX) AS
BEGIN
    RETURN TRANSLATE
    (
        @Texto,
        N'ÁÀÃÂÄáàãâäÉÈÊËéèêëÍÌÎÏíìîïÓÒÕÔÖóòõôöÚÙÛÜúùûüÇçÑñÝŸýÿ',
        N'AAAAAaaaaaEEEEeeeeIIIIiiiiOOOOOoooooUUUUuuuuCcNnYYyy'
    );
END;
GO

DECLARE @CODPESSOA AS INTEGER = 37342 --ULTIMO CODPESSOA

SELECT DISTINCT 
	  X.TIPO,
      X.MATRICULA,
      X.CODIGO FISICA,
      UPPER(X.NOME) as NOME,
      X.APELIDO,     
      CASE 
          WHEN X.DTNASCIMENTO IS NULL OR X.DTNASCIMENTO = '' OR X.DTNASCIMENTO < '1931-12-31' 
          THEN '1931-12-31'
          ELSE X.DTNASCIMENTO
      END AS DTNASCIMENTO,
      CASE
        WHEN UPPER(X.ESTADOCIVIL) LIKE 'S'              THEN 'S'  
        WHEN UPPER(X.ESTADOCIVIL) LIKE 'C'              THEN 'C'  
        WHEN UPPER(X.ESTADOCIVIL) LIKE 'D'              THEN 'I'  
        WHEN UPPER(X.ESTADOCIVIL) LIKE 'V'              THEN 'V'  
        WHEN UPPER(X.ESTADOCIVIL) LIKE 'UEST'           THEN 'E'  
        WHEN UPPER(X.ESTADOCIVIL) LIKE 'J'              THEN 'O'
      END AS ESTADOCIVIL,        
      ISNULL(X.SEXO,'M') AS SEXO,
      CASE
        WHEN TRIM(X.NATURALIDADE) = ''
        THEN 'NAO IDENTIFICADO'
        ELSE dbo.fn_RemoveAcentos(UPPER(X.NATURALIDADE)) 
      END AS NATURALIDADE, 
        CASE 
           WHEN EXISTS(SELECT 1 FROM CorporeRM.dbo.GETD WHERE CODETD COLLATE SQL_Latin1_General_CP1_CI_AS = X.ESTADONATAL) THEN X.ESTADONATAL
           WHEN LTRIM(X.ESTADONATAL) IS NULL OR TRIM(X.ESTADONATAL) = '' THEN 'NA'
           ELSE '--'
        END AS ESTADONATAL,
      dbo.fn_RemoveAcentos(X.NACIONALIDADE) AS NACIONALIDADE, 
      CASE WHEN X.GRAUINSTRUCAO ='0' THEN NULL ELSE X.GRAUINSTRUCAO END GRAUINSTRUCAO,
      X.CODTIPORUA, 
      dbo.fn_RemoveAcentos(LEFT(UPPER(X.RUA),100)) AS RUA, 
      LEFT(X.NUMERO,8) AS NUMERO, 
      dbo.fn_RemoveAcentos(LEFT(UPPER(REPLACE(X.COMPLEMENTO,';',' ')),30)) COMPLEMENTO, 
      X.CODTIPOBAIRRO,
      dbo.fn_RemoveAcentos(LEFT(UPPER(X.BAIRRO),30)) AS BAIRRO, 
      dbo.fn_RemoveAcentos(
         CASE 
           WHEN EXISTS(SELECT 1 FROM CorporeRM.dbo.GETD WHERE CODETD COLLATE SQL_Latin1_General_CP1_CI_AS = X.ESTADO) THEN X.ESTADO
           WHEN LTRIM(X.ESTADO) IS NULL OR TRIM(X.ESTADO) = '' THEN 'NA'
           ELSE '--'
         END
      ) AS ESTADO,
      dbo.fn_RemoveAcentos(
       UPPER(
         CASE
           WHEN LTRIM(X.CIDADE) IS NULL OR X.CIDADE = '' THEN 'NAO IDENTIFICADO'
           ELSE LTRIM(X.CIDADE)
       END)
       ) CIDADE,
      ISNULL(X.CEP,'') AS CEP, 
      X.PAIS, 
      X.REGPROFISSIONAL,	
      X.CPF, 
      LEFT(X.TELEFONE1,15) AS TELEFONE1,
      LEFT(X.TELEFONE2,15) AS TELEFONE2,
      LEFT(X.TELEFONE3,15) AS TELEFONE3,
      X.FAX,
      LEFT(REPLACE(X.EMAIL,';',''),60) EMAIL, 
      REPLACE(REPLACE(LEFT(
        TRANSLATE(X.CARTIDENTIDADE, 
                  'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', 
                  '####################################################'), 
        15
    ),'##-',''),'##','') AS CARTIDENTIDADE, 
      X.UFCARTIDENT AS UFCARTIDENT,
      X.ORGEMISSORIDENT AS ORGEMISSORIDENT, 
      X.DTEMISSAOIDENT, 
      LEFT(X.TITULOELEITOR,14) AS TITULOELEITOR,
      X.ZONATITELEITOR, 
      X.SECAOTITELEITOR, 
      X.DTTITELEITOR,
      X.ESTELEIT,
      LEFT(X.CARTEIRATRAB,10) AS CARTEIRATRAB,
      X.SERIECARTTRAB,
      X.UFCARTTRAB,
      X.DTCARTTRAB, 
      X.NIT, 
      X.CARTMOTORISTA,
      X.TIPOCARTHABILIT, 
      X.DTVENCHABILIT,
      X.SITMILITAR, 
      X.CERTIFRESERV, 
      X.CATEGMILITAR, 
      X.CSM, 
      X.DTEXPCML, 
      X.EXPED, 
      X.RM, 
      X.NROREGGERAL, 
      X.NPASSAPORTE,
      X.PAISORIGEM,
      NULLIF(X.DTEMISSPASSAPORTE,'1900-01-01') AS DTEMISSPASSAPORTE,
      X.DTVALPASSAPORTE, 
        CASE
            WHEN UPPER(X.CORRACA) LIKE 'INDIGENA'          THEN 0
            WHEN UPPER(X.CORRACA) LIKE 'BRANCA'            THEN 2
            WHEN UPPER(X.CORRACA) LIKE 'NEGRA'             THEN 4
            WHEN UPPER(X.CORRACA) LIKE 'AMARELA'           THEN 6
            WHEN UPPER(X.CORRACA) LIKE 'PARDA'             THEN 8
            WHEN UPPER(X.CORRACA) LIKE 'NAO DECLARADA'     THEN 10
        END AS CORRACA,
      X.DEFICIENTEFISICO, 
      X.DEFICIENTEAUDITIVO,
      X.DEFICIENTEFALA,
      X.DEFICIENTEVISUAL, 
      CASE WHEN LEN(X.DEFICIENTEMENTAL) >1 THEN '1' ELSE X.DEFICIENTEMENTAL END DEFICIENTEMENTAL, 
      X.RECURSOREALIZACAOTRAB,
      X.RECURSOACESSIBILIDADE, 
      X.PROFISSAO,
      X.EMPRESA,
      '' AS OCUPACAO,
      X.TIPOSANG, 
      X.ALUNO,
      X.PROFESSOR,
      X.USUARIOBIBLIOS,
      X.FUNCIONARIO,
      X.EXFUNCIONARIO,
      X.CANDIDATO, 
      X.FALECIDO, 
      X.DATAOBITO,
      X.MATRICULAOBITO,
      X.NOMESOCIAL,
      X.OBSERVACOES 
	  INTO ZPPESSOA_GERAL
  FROM (
      SELECT * FROM DEPARA_PESSOA_ALUNO_PAI_MAE_RESP --ORDER BY MATRICULA
UNION ALL
      SELECT * FROM ZDEPARA_PESSOA_PROFESSOR --ORDER BY MATRICULA
) AS X
WHERE  NULLIF(LTRIM(RTRIM(X.CPF)), '') IS NOT NULL;
--ORDER BY X.NOME

--COPIA TABELA PARA TRAZER ALUNOS E PROFESSORES JÁ CADASTRADOS
IF OBJECT_ID('PESSOAS') IS NOT NULL
   DROP TABLE PESSOAS;

SELECT * INTO PESSOAS FROM ZPPESSOA_GERAL;

/*----CONSULTA AUXLILIAR PARA VERIFICAR SE EXISTEM DUPLICIDADES DE PESSOAS NA BASE DE DADOS DO SESC----*/

-- DELETE DE CPFs QUE JÁ EXISTEM NA BASE DE DADOS DO SESC - PARA ISSO É NECESSÁRIO COPIAR OS DADOS DA BASE DE DADOS DE DESTINO E FAZER UM EXISTIS 

-- PRIMEIRO VAMOS LISTAR AS PESSOAS QUE JÁ EXISTEM NA BASE DE DADOS DO SESC. VEREMOS ISSO PELO CPF 

SELECT * FROM ZPPESSOA_GERAL WHERE EXISTS (SELECT 1
                                      FROM ZDADOSORIGEM AS Z
                                     WHERE Z.CPF = ZPPESSOA_GERAL.CPF
                                   )

-- -- AGORA VAMOS EFETUAR O DELETE DOS DADOS DUPLICADOS                                    

 DELETE ZPPESSOA_GERAL WHERE EXISTS (SELECT 1
                                FROM ZDADOSORIGEM AS Z
                               WHERE Z.CPF = ZPPESSOA_GERAL.CPF
                              )

/*-----------------------------------------------------------------------------------------------------*/

SELECT TIPO,COUNT(*)  QTD FROM ZPPESSOA_GERAL GROUP BY TIPO;

SELECT * FROM ZPPESSOA_GERAL WHERE NATURALIDADE LIKE ('%NAO IDENTIFICADO%'); 


IF OBJECT_ID('ZPESSOA_REG') IS NOT NULL
   DROP TABLE ZPESSOA_REG;

-- GERA TABELA COM REGISTROS PARA ELIMINAR DUPLICIDADES
SELECT 
    ROW_NUMBER() OVER (PARTITION BY NIT ORDER BY NOME) AS REG, * INTO ZPESSOA_REG FROM ZPPESSOA_GERAL ;-- ORDER BY NOME

-- RETORNA SEM DUPLICIDADES
IF OBJECT_ID('ZPESSOA_REG2') IS NOT NULL
   DROP TABLE ZPESSOA_REG2 ; 

SELECT * INTO ZPESSOA_REG2 
	FROM ZPESSOA_REG (NOLOCK)
WHERE REG IN ( SELECT MAX(ZZ.REG) FROM ZPESSOA_REG AS ZZ	
WHERE 
ZZ.CPF          = ZPESSOA_REG.CPF) ;

--SELECT * INTO ZPESSOA_REG2 
--	FROM ZPESSOA_REG (NOLOCK)
--WHERE REG IN ( SELECT TOP 1 (ZZ.REG) 
--                 FROM ZPESSOA_REG AS ZZ	
--                WHERE ZZ.CPF = ZPESSOA_REG.CPF
--				ORDER BY TIPO )

--ORDER BY NOME

SELECT * FROM ZPESSOA_REG2 ;

-- VERIFICA SE RESTOU DUPLICIDADES
SELECT NOME,DTNASCIMENTO,NATURALIDADE,ESTADONATAL,CPF FROM ZPESSOA_REG2 GROUP BY NOME,DTNASCIMENTO,NATURALIDADE,ESTADONATAL,CPF
HAVING COUNT(*) >1 ; 

IF OBJECT_ID('ZPESSOA_FINALII') IS NOT NULL
   DROP TABLE ZPESSOA_FINALII;

-- GERA TABELA FINAL PPESSOA
SELECT 
    ROW_NUMBER() OVER (PARTITION BY NIT ORDER BY NOME) + @CODPESSOA AS CODIGO, * INTO ZPESSOA_FINALII FROM ZPESSOA_REG2 ; --COLOCAR AQUI O ÚLTIMO CODPESSOA ENCONTRADO NA BASE DE DADOS DO SESC

ALTER TABLE ZPESSOA_FINALII DROP COLUMN REG;
ALTER TABLE ZPESSOA_FINALII DROP COLUMN TIPO;
ALTER TABLE ZPESSOA_FINALII DROP COLUMN MATRICULA;
ALTER TABLE ZPESSOA_FINALII DROP COLUMN OBSERVACOES;
ALTER TABLE ZPESSOA_FINALII DROP COLUMN FISICA;

--ALTER TABLE ZPESSOA_FINALII DROP COLUMN CODIGO
--GO                                                /* RETIRADO POIS ESTAVAMOS GERANDO A NUMERA??O MAIS DE UMA VEZ. E FOI MEXIDO NO ORDER BY DO ROW_NUMBER PARA GERAR ORDENADO PELO NOME E N?O PELO NIT */ 

IF OBJECT_ID('ZPESSOA_FINAL') IS NOT NULL
   DROP TABLE ZPESSOA_FINAL ;

SELECT 
    * INTO ZPESSOA_FINAL FROM ZPESSOA_FINALII ;

SELECT * FROM ZPESSOA_FINAL ;

-- CRIANDO ZPESSOA E DELETANDO COLUNA DE BASE DE DADOS
IF OBJECT_ID('ZPESSOA') IS NOT NULL
   DROP TABLE ZPESSOA ;

SELECT * INTO ZPESSOA FROM ZPESSOA_FINAL ORDER BY NOME ;

-- ADICIONA CAMPO CODPESSOA A TABELA
ALTER TABLE ZPPESSOA_GERAL ADD CODPESSOA INT 
;

UPDATE ZPPESSOA_GERAL
   SET CODPESSOA = ZPESSOA.CODIGO
  FROM ZPPESSOA_GERAL WITH (NOLOCK)
  JOIN ZPESSOA WITH (NOLOCK) 
    ON ZPESSOA.CPF = ZPPESSOA_GERAL.CPF
 WHERE  NULLIF(LTRIM(RTRIM(ZPESSOA.CPF)), '') IS NOT NULL ; /* LINHA ADICIONADA PARA NÃO ATRIBUIR O CÓDIGO DE PESSOA */ 

DROP FUNCTION dbo.fn_RemoveAcentos;
GO

SELECT * FROM ZPESSOA;
