IF OBJECT_ID('ZDEPARA_RESPACAD_PAIMAE') IS NOT NULL
	DROP TABLE ZDEPARA_RESPACAD_PAIMAE
;
SELECT DISTINCT
	'MT' AS BASE,
	CASE
		WHEN ZDEPARA_PPESSOA_PAI_MAE.TIPO = 'PAI' THEN 'RESP_ACAD_PAI'
		WHEN ZDEPARA_PPESSOA_PAI_MAE.TIPO = 'MAE' THEN 'RESP_ACAD_MAE'
	END AS TIPO,
	ZDEPARA_PPESSOA_PAI_MAE.COD_ALUNO AS CODEXT,
	CASE
		WHEN EXISTS (
			SELECT 1 
			FROM PAI_ALUNO 
			WHERE PAI_ALUNO.PFL_FILID = ZDEPARA_PPESSOA_PAI_MAE.COD_ALUNO
			  AND PAI_ALUNO.NOME = ZDEPARA_PPESSOA_PAI_MAE.NOME
		)
		THEN (
			SELECT PAI_ALUNO.PFL_PESID
			FROM PAI_ALUNO 
			WHERE PAI_ALUNO.PFL_PESID = ZDEPARA_PPESSOA_PAI_MAE.COD_ALUNO
			  AND PAI_ALUNO.NOME = ZDEPARA_PPESSOA_PAI_MAE.NOME
		)
		ELSE NULL
		END AS FISICA
		INTO ZDEPARA_RESPACAD_PAIMAE
FROM ZDEPARA_PPESSOA_PAI_MAE
;

SELECT * FROM ZDEPARA_RESPACAD_PAIMAE ;
