IF OBJECT_ID('dbo.fn_calcular_digito_verificador_modulo10','FN') IS NOT NULL
    DROP FUNCTION dbo.fn_calcular_digito_verificador_modulo10
GO

CREATE FUNCTION dbo.fn_calcular_digito_verificador_modulo10
(
    @matricula VARCHAR(20) -- Número da matrícula
) RETURNS CHAR(1) AS
BEGIN
    DECLARE @soma INT = 0;
    DECLARE @i INT;
    DECLARE @multiplicador INT;
    DECLARE @digito INT;

    -- Laço para percorrer cada caractere da matrícula (da direita para a esquerda)
    SET @i = LEN(@matricula);
    
    -- Inicia o multiplicador como 2 (posição ímpar)
    SET @multiplicador = 2;

    WHILE @i > 0
    BEGIN
        -- Pega o valor do caractere (dígito) da matrícula e calcula o valor
        DECLARE @valor INT = CAST(SUBSTRING(@matricula, @i, 1) AS INT);
        
        -- Se a posição for ímpar (começando da direita, a partir de 1), multiplica por 2
        IF @multiplicador = 2
        BEGIN
            SET @valor = @valor * 2;
            -- Se o resultado for maior que 9, subtrai 9
            IF @valor > 9
            BEGIN
                SET @valor = @valor - 9;
            END
        END

        -- Soma o valor ao total
        SET @soma = @soma + @valor;

        -- Atualiza o multiplicador (2 -> 1, 1 -> 2, e assim por diante)
        SET @multiplicador = CASE 
            WHEN @multiplicador = 2 THEN 1 
            ELSE 2 
        END;

        SET @i = @i - 1;
    END

    -- Calcula o dígito verificador
    SET @digito = (@soma * 9) % 10;

    -- Retorna o dígito verificador
    RETURN CAST(@digito AS CHAR(1));
END
GO

IF OBJECT_ID('ZMIGRA_SPESSOA_SALUNO_TEMP') IS NOT NULL
   DROP TABLE ZMIGRA_SPESSOA_SALUNO_TEMP
;

DECLARE @CODCOLIGADA INT = 13
DECLARE @RA INT = 75426

SELECT DISTINCT
   ZPESSOA_REG.NOME                          AS NOME,
   SUBSTRING(
      ZPESSOA_REG.NOME, 
      CHARINDEX(' ', ZPESSOA_REG.NOME) + 1, 
      LEN(ZPESSOA_REG.NOME)
   ) AS SOBRENOME,
   ZPESSOA_REG.DTNASCIMENTO                  AS DTNASCIMENTO,  
   ZPESSOA_REG.CPF                           AS CPF,
   ZPESSOA_REG.CARTIDENTIDADE                AS CARTIDENTIDADE,
   ''                                        AS UFCARTIDENT,
   ''                                        AS CARTEIRATRAB,
   ''                                        AS SERIECARTTRAB,
   ''                                        AS UFCARTTRAB,
   ''                                        AS EMPRESANOME,
   ''                                        AS EMPRESARUA,
   ''                                        AS EMPRESANUMERO,
   ''                                        AS EMPRESACOMPLEMENTO,
   ''                                        AS EMPRESABAIRRO,
   ''                                        AS EMPRESACEP,
   ''                                        AS EMPRESACIDADE,
   ''                                        AS EMPRESAUF,
   ''                                        AS EMPRESATELEFONE,
   ''                                        AS EMPRESAHORARIO,
   ''                                        AS TIPOCERTIDAO,
   ''                                        AS CERTNUMERO,
   ''                                        AS CERTCARTORIO,
   ''                                        AS CERTCOMARCA,
   ''                                        AS CERTDATA,
   ''                                        AS CERTFOLHA,
   ''                                        AS CERTLIVRO,
   ''                                        AS CERTDISTRITO,
   ''                                        AS CERTUF,
   CASE 
	   WHEN EXISTS (SELECT 1 FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%PAI%')
	   THEN (SELECT TOP 1 NOME FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%PAI%')
	ELSE ''
   END AS NOMEPAI,
   CASE 
	   WHEN EXISTS (SELECT 1 FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%PAI%')
	   THEN (SELECT TOP 1 DTNASCIMENTO FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%PAI%')
	ELSE ''
   END AS DTNASCIMENTOPAI,
   CASE 
	   WHEN EXISTS (SELECT 1 FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%PAI%')
	   THEN (SELECT TOP 1 CPF FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%PAI%')
	ELSE ''
   END AS CPFPAI,
   CASE 
	   WHEN EXISTS (SELECT 1 FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%PAI%')
	   THEN (SELECT TOP 1 RG FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%PAI%')
	ELSE ''
   END AS RGPAI,
   CASE 
	   WHEN EXISTS (SELECT 1 FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%MAE%')
	   THEN (SELECT TOP 1 NOME FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%MAE%')
	ELSE ''
   END AS NOMEMAE,
   CASE 
	   WHEN EXISTS (SELECT 1 FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%MAE%')
	   THEN (SELECT TOP 1 DTNASCIMENTO FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%MAE%')
	ELSE ''
   END AS DTNASCIMENTOMAE,
   CASE 
	   WHEN EXISTS (SELECT 1 FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%MAE%')
	   THEN (SELECT TOP 1 CPF FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%MAE%')
	ELSE ''
   END AS CPFMAE,
   CASE 
	   WHEN EXISTS (SELECT 1 FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%MAE%')
	   THEN (SELECT TOP 1 RG FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%MAE%')
	ELSE ''
   END AS RGMAE,
   @CODCOLIGADA                        AS CODCOLIGADA,
   ZPESSOA_REG.MATRICULA,
   1                                   AS TIPOALUNO,
   ''                                  AS INSTDESTINO,
   ''                                  AS INSTORIGEM,
   ''                                  AS CODCURHIST,
   ''                                  AS CODSERIEHIST,
   ''                                  AS CODCOLCFO,
   ''                                  AS CODCFO,
   ''                                  AS CODPARENTCFO,
   (
      SELECT TOP 1 NOME FROM ZPESSOA_REG RESP WHERE TIPO LIKE 'RESP_ACAD' AND RESP.MATRICULA = ZPESSOA_REG.MATRICULA
   ) AS NOMERESPACAD,
   (
      SELECT TOP 1 DTNASCIMENTO FROM ZPESSOA_REG RESP WHERE TIPO LIKE 'RESP_ACAD' AND RESP.MATRICULA = ZPESSOA_REG.MATRICULA
   ) AS DTNASCIMENTORESPACAD, 
   (
      SELECT TOP 1 CPF FROM ZPESSOA_REG RESP WHERE TIPO LIKE 'RESP_ACAD' AND RESP.MATRICULA = ZPESSOA_REG.MATRICULA
   ) AS CPFRESPACAD,
   (
      SELECT TOP 1 CARTIDENTIDADE FROM ZPESSOA_REG RESP WHERE TIPO LIKE 'RESP_ACAD' AND RESP.MATRICULA = ZPESSOA_REG.MATRICULA
   )AS RGRESPACAD,
   CASE
      WHEN EXISTS(
         SELECT 1 FROM PAI_ALUNO WHERE PFL_FILID =  (
             SELECT TOP 1 FISICA
             FROM ZPESSOA_REG RESP
             WHERE TIPO LIKE 'RESP_ACAD'
               AND RESP.MATRICULA = ZPESSOA_REG.MATRICULA
         )
      )
      THEN (
         SELECT TOP 1 TIPO FROM PAI_ALUNO WHERE PFL_FILID =  (
             SELECT TOP 1 FISICA
             FROM ZPESSOA_REG RESP
             WHERE TIPO LIKE 'RESP_ACAD'
               AND RESP.MATRICULA = ZPESSOA_REG.MATRICULA
         )
      )
   END CODPARENTRACA,
   ''                                  AS OBSHIST,
   ZPESSOA_REG.MATRICULA               AS IDENTIFICADOR2,
   ''                                  AS IDENTIFICADOR3,
   ''                                  AS ANOINGRESSO,
   ''                                  AS ANOTACOES,
   1                                   AS CODTIPOCURSO,
   ''                                  AS CODINSTORIGEM,
   ''                                  AS CODINSTDESTINO,
   ZPESSOA_REG.NATURALIDADE                AS NATURALIDADE,
   ZPESSOA_REG.ESTADONATAL                 AS ESTADONATAL,
   CASE 
	   WHEN EXISTS (SELECT 1 FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%PAI%')
	   THEN (SELECT TOP 1 NATURALIDADE FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%PAI%')
	ELSE ''
   END AS NATURALIDADEPAI,
   CASE 
	   WHEN EXISTS (SELECT 1 FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%PAI%')
	   THEN (SELECT TOP 1 ESTADONATAL FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%PAI%')
	ELSE ''
   END AS ESTADONATALPAI,
   CASE 
	   WHEN EXISTS (SELECT 1 FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%MAE%')
	   THEN (SELECT TOP 1 NATURALIDADE FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%MAE%')
	ELSE ''
   END AS NATURALIDADEMAE,
      CASE 
	   WHEN EXISTS (SELECT 1 FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%MAE%')
	   THEN (SELECT TOP 1 ESTADONATAL FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%MAE%')
	ELSE ''
   END AS ESTADONATALMAE,
   CASE
      WHEN EXISTS (SELECT 1 FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%MAE%')
	   THEN (SELECT TOP 1 NATURALIDADE FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%MAE%')
      ELSE (SELECT TOP 1 NATURALIDADE FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%PAI%')
   END AS NATURALIDADEACAD,
   CASE
      WHEN EXISTS (SELECT 1 FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%MAE%')
	   THEN (SELECT TOP 1 NATURALIDADE FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%MAE%')
      ELSE (SELECT TOP 1 NATURALIDADE FROM PAI_ALUNO WHERE PFL_PESID = ZPESSOA_REG.MATRICULA AND TIPO LIKE '%PAI%')
   END AS ESTADONATALACAD,
   ''                                  AS CODSISTEC,
   ''                                  AS CODINST2GRAU,
   ''                                  AS GRAUULTIMAINST,
   ''                                  AS ANOULTIMAINST,
   ''                                  AS CODETNIA
   INTO ZMIGRA_SPESSOA_SALUNO_TEMP
FROM (SELECT * FROM ZPESSOA_REG WHERE TIPO = 'ALUNO') ZPESSOA_REG

SELECT DISTINCT * FROM  ZMIGRA_SPESSOA_SALUNO_TEMP ;

-- FAZ O TRATAMENTO DO RA PARA UNIFICAÇÃO 
IF OBJECT_ID('ZMIGRA_SPESSOA_TEMP') IS NOT NULL
   DROP TABLE ZMIGRA_SPESSOA_TEMP ;
SELECT DISTINCT
 	   TEMP.MATRICULA,
      ZPESSOA.NOME,
      TEMP.SOBRENOME,
      ZPESSOA.DTNASCIMENTO ,
      ZPESSOA.CPF,
      ZPESSOA.CARTIDENTIDADE,
      ZPESSOA.UFCARTIDENT,
      ZPESSOA.CARTEIRATRAB,
      ZPESSOA.SERIECARTTRAB,
      ZPESSOA.UFCARTTRAB,
      TEMP.EMPRESANOME,
      TEMP.EMPRESARUA,
      TEMP.EMPRESANUMERO,
      TEMP.EMPRESACOMPLEMENTO,
      TEMP.EMPRESABAIRRO,
      TEMP.EMPRESACEP,
      TEMP.EMPRESACIDADE,
      TEMP.EMPRESAUF,
      TEMP.EMPRESATELEFONE,
      TEMP.EMPRESAHORARIO,
      TEMP.TIPOCERTIDAO,
      TEMP.CERTNUMERO,
      TEMP.CERTCARTORIO,
      TEMP.CERTCOMARCA,
      TEMP.CERTDATA,
      TEMP.CERTFOLHA,
      TEMP.CERTLIVRO,
      TEMP.CERTDISTRITO,
      TEMP.CERTUF,
      TEMP.NOMEPAI,
      TEMP.DTNASCIMENTOPAI,
      TEMP.CPFPAI,
      TEMP.RGPAI,
      TEMP.NOMEMAE,
      TEMP.DTNASCIMENTOMAE,
      TEMP.CPFMAE,
      TEMP.RGMAE,
      TEMP.CODCOLIGADA,
      FORMAT(@RA+DENSE_RANK() OVER (ORDER BY TEMP.MATRICULA ) , '00000000') + -- '-'+ - RETIRANDO O "-" DO CÓDIGO DA MATRÍCULA
      CAST(dbo.fn_calcular_digito_verificador_modulo10(@RA+DENSE_RANK() OVER (ORDER BY TEMP.MATRICULA ) ) AS VARCHAR(1))  AS RA, -- COLOCAR AQUI A ULTIMA MATRÍCULA ENCONTRADA NA BASE DE DADOS DO SESC
      TEMP.TIPOALUNO, -- Ativo 
      TEMP.INSTDESTINO,
      TEMP.INSTORIGEM,
      TEMP.CODCURHIST,
      TEMP.CODSERIEHIST,
      TEMP.CODCOLCFO,
      TEMP.CODCFO,
      TEMP.CODPARENTCFO,
      TEMP.NOMERESPACAD,
      TEMP.DTNASCIMENTORESPACAD,
      TEMP.CPFRESPACAD,
      TEMP.RGRESPACAD,
      TEMP.CODPARENTRACA,
      TEMP.OBSHIST,
      TEMP.IDENTIFICADOR2,
      TEMP.IDENTIFICADOR3,
      TEMP.ANOINGRESSO,
      TEMP.ANOTACOES,
      TEMP.CODTIPOCURSO,
      TEMP.CODINSTORIGEM,
      TEMP.CODINSTDESTINO,
      ZPESSOA.NATURALIDADE,
      ZPESSOA.ESTADONATAL,
      TEMP.NATURALIDADEPAI,
      TEMP.ESTADONATALPAI,
      TEMP.NATURALIDADEMAE,
      TEMP.ESTADONATALMAE,
      TEMP.NATURALIDADEACAD,
      TEMP.ESTADONATALACAD,
      TEMP.CODSISTEC,
      TEMP.CODINST2GRAU,
      TEMP.GRAUULTIMAINST,
      TEMP.ANOULTIMAINST,
      TEMP.CODETNIA
      INTO ZMIGRA_SPESSOA_TEMP
  FROM 
      ZMIGRA_SPESSOA_SALUNO_TEMP TEMP
	  JOIN ZPESSOA  
	    ON ZPESSOA.CPF = TEMP.CPF ; 

-- ATUALIZAR CAMPO RA COM O MENOR NÚMERO DE RA DAQUELE ALUNO 

UPDATE ZMIGRA_SPESSOA_TEMP SET RA = (SELECT MIN(TEMP.RA) FROM ZMIGRA_SPESSOA_TEMP AS TEMP WHERE TEMP.CPF = Z.CPF ) FROM ZMIGRA_SPESSOA_TEMP AS Z ; --WHERE Z.CPF = '05881574303'


-- CRIANDO TABELA DE DE/PARA REFERENCIAL - TABELA ZDEPARA_SALUNO_RA
IF OBJECT_ID('ZDEPARA_SALUNO_RA') IS NOT NULL
   DROP TABLE ZDEPARA_SALUNO_RA ;

SELECT DISTINCT  
	  ZMIGRA_SPESSOA_TEMP.MATRICULA,
      ZMIGRA_SPESSOA_TEMP.RA
      INTO ZDEPARA_SALUNO_RA
  FROM 
      ZMIGRA_SPESSOA_TEMP 
	  LEFT JOIN ZMIGRA_SPESSOA_SALUNO_TEMP 
              ON (ZMIGRA_SPESSOA_TEMP.MATRICULA = ZMIGRA_SPESSOA_SALUNO_TEMP.MATRICULA ) ;

-- GERA ARQUIVO FINAL COM RA
IF OBJECT_ID('ZMIGRA_SPESSOA_SALUNO') IS NOT NULL
   DROP TABLE ZMIGRA_SPESSOA_SALUNO ;
 
-- GERA ARQUIVO FINAL ESCOLHENDO A LINHA MAIS PREENCHIDA
SELECT DISTINCT
      (SELECT TOP 1 MAX(MATRICULA) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND MATRICULA IS NOT NULL) AS MATRICULA,
      ZPESSOA.NOME,
      (SELECT TOP 1 MAX(SOBRENOME) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND SOBRENOME IS NOT NULL) AS SOBRENOME,
      ZPESSOA.DTNASCIMENTO,
      ZPESSOA.CPF,
      ZPESSOA.CARTIDENTIDADE,
      ZPESSOA.UFCARTIDENT,
      ZPESSOA.CARTEIRATRAB,
      ZPESSOA.SERIECARTTRAB,
      ZPESSOA.UFCARTTRAB,
      (SELECT TOP 1 MAX(EMPRESANOME) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND EMPRESANOME IS NOT NULL) AS EMPRESANOME,
      (SELECT TOP 1 MAX(EMPRESARUA) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND EMPRESARUA IS NOT NULL) AS EMPRESARUA,
      (SELECT TOP 1 MAX(EMPRESANUMERO) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND EMPRESANUMERO IS NOT NULL) AS EMPRESANUMERO,
      (SELECT TOP 1 MAX(EMPRESACOMPLEMENTO) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND EMPRESACOMPLEMENTO IS NOT NULL) AS EMPRESACOMPLEMENTO,
      (SELECT TOP 1 MAX(EMPRESABAIRRO) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND EMPRESABAIRRO IS NOT NULL) AS EMPRESABAIRRO,
      (SELECT TOP 1 MAX(EMPRESACEP) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND EMPRESACEP IS NOT NULL) AS EMPRESACEP,
      (SELECT TOP 1 MAX(EMPRESACIDADE) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND EMPRESACIDADE IS NOT NULL) AS EMPRESACIDADE,
      (SELECT TOP 1 MAX(EMPRESAUF) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND EMPRESAUF IS NOT NULL) AS EMPRESAUF,
      (SELECT TOP 1 MAX(EMPRESATELEFONE) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND EMPRESATELEFONE IS NOT NULL) AS EMPRESATELEFONE,
      (SELECT TOP 1 MAX(EMPRESAHORARIO) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND EMPRESAHORARIO IS NOT NULL) AS EMPRESAHORARIO,
      (SELECT TOP 1 MAX(TIPOCERTIDAO) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND TIPOCERTIDAO IS NOT NULL) AS TIPOCERTIDAO,
      (SELECT TOP 1 MAX(CERTNUMERO) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CERTNUMERO IS NOT NULL) AS CERTNUMERO,
      (SELECT TOP 1 MAX(CERTCARTORIO) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CERTCARTORIO IS NOT NULL) AS CERTCARTORIO,
      (SELECT TOP 1 MAX(CERTCOMARCA) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CERTCOMARCA IS NOT NULL) AS CERTCOMARCA,
      (SELECT TOP 1 MAX(CERTDATA) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CERTDATA IS NOT NULL) AS CERTDATA,
      (SELECT TOP 1 MAX(CERTFOLHA) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CERTFOLHA IS NOT NULL) AS CERTFOLHA,
      (SELECT TOP 1 MAX(CERTLIVRO) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CERTLIVRO IS NOT NULL) AS CERTLIVRO,
      (SELECT TOP 1 MAX(CERTDISTRITO) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CERTDISTRITO IS NOT NULL) AS CERTDISTRITO,
      (SELECT TOP 1 MAX(CERTUF) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CERTUF IS NOT NULL) AS CERTUF,
      (SELECT TOP 1 MAX(NOMEPAI) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND NOMEPAI IS NOT NULL) AS NOMEPAI,
      (SELECT TOP 1 MAX(DTNASCIMENTOPAI) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND DTNASCIMENTOPAI IS NOT NULL) AS DTNASCIMENTOPAI,
      (SELECT TOP 1 MAX(CPFPAI) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CPFPAI IS NOT NULL) AS CPFPAI,
      (SELECT TOP 1 MAX(RGPAI) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND RGPAI IS NOT NULL) AS RGPAI,
      (SELECT TOP 1 MAX(NOMEMAE) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND NOMEMAE IS NOT NULL) AS NOMEMAE,
      (SELECT TOP 1 MAX(DTNASCIMENTOMAE) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND DTNASCIMENTOMAE IS NOT NULL) AS DTNASCIMENTOMAE,
      (SELECT TOP 1 MAX(CPFMAE) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CPFMAE IS NOT NULL) AS CPFMAE,
      (SELECT TOP 1 MAX(RGMAE) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND RGMAE IS NOT NULL) AS RGMAE,
      (SELECT TOP 1 MAX(CODCOLIGADA) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CODCOLIGADA IS NOT NULL) AS CODCOLIGADA,
      (SELECT MIN(RA) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF) AS RA,
      (SELECT TOP 1 MAX(TIPOALUNO) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND TIPOALUNO IS NOT NULL) AS TIPOALUNO,
      (SELECT TOP 1 MAX(INSTDESTINO) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND INSTDESTINO IS NOT NULL) AS INSTDESTINO,
      (SELECT TOP 1 MAX(INSTORIGEM) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND INSTORIGEM IS NOT NULL) AS INSTORIGEM,
      (SELECT TOP 1 MAX(CODCURHIST) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CODCURHIST IS NOT NULL) AS CODCURHIST,
      (SELECT TOP 1 MAX(CODSERIEHIST) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CODSERIEHIST IS NOT NULL) AS CODSERIEHIST,
      (SELECT TOP 1 MAX(CODCOLCFO) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CODCOLCFO IS NOT NULL) AS CODCOLCFO,
      (SELECT TOP 1 MAX(CODCFO) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CODCFO IS NOT NULL) AS CODCFO,
      (SELECT TOP 1 MAX(CODPARENTCFO) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CODPARENTCFO IS NOT NULL) AS CODPARENTCFO,
      (SELECT TOP 1 MAX(NOMERESPACAD) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND NOMERESPACAD IS NOT NULL) AS NOMERESPACAD,
      (SELECT TOP 1 MAX(DTNASCIMENTORESPACAD) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND DTNASCIMENTORESPACAD IS NOT NULL) AS DTNASCIMENTORESPACAD,
      (SELECT TOP 1 MAX(CPFRESPACAD) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CPFRESPACAD IS NOT NULL) AS CPFRESPACAD,
      (SELECT TOP 1 MAX(RGRESPACAD) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND RGRESPACAD IS NOT NULL) AS RGRESPACAD,
      (SELECT TOP 1 MAX(CODPARENTRACA) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CODPARENTRACA IS NOT NULL) AS CODPARENTRACA,
      (SELECT TOP 1 MAX(OBSHIST) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND OBSHIST IS NOT NULL) AS OBSHIST,
      (SELECT TOP 1 MAX(IDENTIFICADOR2) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND IDENTIFICADOR2 IS NOT NULL) AS IDENTIFICADOR2,
      (SELECT TOP 1 MAX(IDENTIFICADOR3) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND IDENTIFICADOR3 IS NOT NULL) AS IDENTIFICADOR3,
      (SELECT TOP 1 MAX(ANOINGRESSO) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND ANOINGRESSO IS NOT NULL) AS ANOINGRESSO,
      (SELECT TOP 1 MAX(ANOTACOES) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND ANOTACOES IS NOT NULL) AS ANOTACOES,
      (SELECT TOP 1 MAX(CODTIPOCURSO) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CODTIPOCURSO IS NOT NULL) AS CODTIPOCURSO,
      (SELECT TOP 1 MAX(CODINSTORIGEM) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CODINSTORIGEM IS NOT NULL) AS CODINSTORIGEM,
      (SELECT TOP 1 MAX(CODINSTDESTINO) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CODINSTDESTINO IS NOT NULL) AS CODINSTDESTINO,
      ZPESSOA.NATURALIDADE,
      ZPESSOA.ESTADONATAL,
      (SELECT TOP 1 MAX(NATURALIDADEPAI) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND NATURALIDADEPAI IS NOT NULL) AS NATURALIDADEPAI,
      (SELECT TOP 1 MAX(ESTADONATALPAI) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND ESTADONATALPAI IS NOT NULL) AS ESTADONATALPAI,
      (SELECT TOP 1 MAX(NATURALIDADEMAE) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND NATURALIDADEMAE IS NOT NULL) AS NATURALIDADEMAE,
      (SELECT TOP 1 MAX(ESTADONATALMAE) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND ESTADONATALMAE IS NOT NULL) AS ESTADONATALMAE,
      (SELECT TOP 1 MAX(NATURALIDADEACAD) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND NATURALIDADEACAD IS NOT NULL) AS NATURALIDADEACAD,
      (SELECT TOP 1 MAX(ESTADONATALACAD) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND ESTADONATALACAD IS NOT NULL) AS ESTADONATALACAD,
      (SELECT TOP 1 MAX(CODSISTEC) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CODSISTEC IS NOT NULL) AS CODSISTEC,
      (SELECT TOP 1 MAX(CODINST2GRAU) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CODINST2GRAU IS NOT NULL) AS CODINST2GRAU,
      (SELECT TOP 1 MAX(GRAUULTIMAINST) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND GRAUULTIMAINST IS NOT NULL) AS GRAUULTIMAINST,
      (SELECT TOP 1 MAX(ANOULTIMAINST) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND ANOULTIMAINST IS NOT NULL) AS ANOULTIMAINST,
      (SELECT TOP 1 MAX(CODETNIA) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF AND CODETNIA IS NOT NULL) AS CODETNIA
      INTO ZMIGRA_SPESSOA_SALUNO
  FROM ZMIGRA_SPESSOA_TEMP TEMP
       JOIN ZPESSOA ON ZPESSOA.CPF = TEMP.CPF
 WHERE
       TEMP.RA = (SELECT MIN(RA) FROM ZMIGRA_SPESSOA_TEMP WHERE CPF = TEMP.CPF) ;
		  
-- EXCLUIR CAMPOS FORA DO LAYOUT
ALTER TABLE ZMIGRA_SPESSOA_SALUNO DROP COLUMN MATRICULA;

SELECT RA,IDENTIFICADOR2,NOME FROM ZMIGRA_SPESSOA_SALUNO;

DROP FUNCTION dbo.fn_calcular_digito_verificador_modulo10
GO