IF OBJECT_ID('ZMIGRA_SPESSOA_SPROFESSOR') IS NOT NULL
   DROP TABLE ZMIGRA_SPESSOA_SPROFESSOR ;

DECLARE @CODCOLIGADA AS INTEGER = 13

SELECT DISTINCT
	PESSOAS.NOME AS NOME,
	PESSOAS.DTNASCIMENTO AS DTNASCIMENTO,
	PESSOAS.CPF AS CPF,
	PESSOAS.CARTIDENTIDADE AS CARTIDENTIDADE,
	PESSOAS.UFCARTIDENT AS UFCARTIDENT, --NAO TEM ESSA INFORMAÇÃO EM CAMPO
	PESSOAS.CARTEIRATRAB AS CARTEIRATRAB, 
	PESSOAS.SERIECARTTRAB AS SERIECARTTRAB,
	PESSOAS.UFCARTTRAB AS UFCARTTRAB,
	@CODCOLIGADA AS CODCOLIGADA,
	PESSOAS.FISICA AS CODPROF,
	'' AS CHAPA,
	'' AS VALORAULA,
	'' AS TITULACAO,
	PESSOAS.NATURALIDADE AS NATURALIDADE,
	PESSOAS.ESTADONATAL AS ESTADONATAL
    INTO ZMIGRA_SPESSOA_SPROFESSOR
  FROM 
      PESSOAS
 WHERE 
      TIPO = 'PROFESSOR';

SELECT * FROM ZMIGRA_SPESSOA_SPROFESSOR;