/*
IMPORTAR TABELA PARA VERIFICACAO DE DADOS QUE JÁ EXISTEM => SUBIR COMO ZDADOSORI_SHABILITACAOFILIAL
SELECT
	SHABILITACAOFILIAL.CODCOLIGADA,
	SHABILITACAOFILIAL.CODFILIAL,
	SHABILITACAOFILIAL.CODTIPOCURSO,
	SHABILITACAOFILIAL.CODCURSO,
	SHABILITACAOFILIAL.CODHABILITACAO,
	SHABILITACAOFILIAL.CODGRADE,
	SHABILITACAOFILIAL.CODTURNO,
	STURNO.NOME AS NOME_TURNO
FROM SHABILITACAOFILIAL
JOIN STURNO
  ON STURNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
  AND STURNO.CODTURNO = SHABILITACAOFILIAL.CODTURNO
WHERE SHABILITACAOFILIAL.CODCOLIGADA = :CODCOLIGADA
IMPORTAR TABELA PARA VERIFICACAO DE DADOS QUE JÁ EXISTEM => SUBIR COMO ZDADOSORI_STURNO
SELECT * FROM STURNO WHERE CODCOLIGADA = :CODCOLIGADA
*/

IF OBJECT_ID('ZMIGRA_SHABILITACAOFILIAL') IS NOT NULL
   DROP TABLE ZMIGRA_SHABILITACAOFILIAL ; 

  DECLARE @CODCOLIGADA AS INTEGER = 13
  DECLARE @ANOLETIVO AS INTEGER = 2026

  SELECT DISTINCT 
        @CODCOLIGADA                                                              AS CODCOLIGADA,
        CAST(ZDEPARA_SHABILITACAOFILIAL.CODFILIAL_PARA AS INT)                    AS CODFILIAL,
        CAST(ZDEPARA_SHABILITACAOFILIAL.NIVELENSINO AS INT)                       AS CODTIPOCURSO,
        ZDEPARA_SHABILITACAOFILIAL.CODCURSO_PARA                                  AS CODCURSO,
        ZDEPARA_SHABILITACAOFILIAL.CODHABILITACAO_PARA                            AS CODHABILITACAO,
        ZDEPARA_SHABILITACAOFILIAL.CODGRADE_PARA                                  AS CODGRADE,
        ZDADOSORI_STURNO.NOME                                                     AS TURNO,
        NULL                                                                      AS CODCCUSTO,
        'N'                                                                       AS ATIVO,
        NULL                                                                      AS CODDEPARTAMENTO,
        NULL                                                                      AS EMAILCOORDENACAO,
        NULL                                                                      AS DECRETOCURSO,
        NULL                                                                      AS DECRETOHABILITACAO,
        NULL                                                                      AS DESCRICAOCURSO,
        NULL                                                                      AS DESCRICAOHABILITACAO
        INTO ZMIGRA_SHABILITACAOFILIAL
    FROM 
        ZDEPARA_SHABILITACAOFILIAL
    JOIN ZDADOSORI_STURNO
      ON ZDADOSORI_STURNO.CODCOLIGADA = ZDEPARA_SHABILITACAOFILIAL.CODCOLIGADA
      AND ZDADOSORI_STURNO.CODTURNO = ZDEPARA_SHABILITACAOFILIAL.CODTURNO_PARA
  WHERE
    ZDEPARA_SHABILITACAOFILIAL.ANO LIKE @ANOLETIVO
    AND ZDEPARA_SHABILITACAOFILIAL.CODCURSO_PARA NOT LIKE 'NÃO IMPORTAR' 
    AND NOT EXISTS (
      SELECT 1
      FROM ZDADOSORI_SHABILITACAOFILIAL X
      WHERE 
        X.CODCOLIGADA           = ZDEPARA_SHABILITACAOFILIAL.CODCOLIGADA
        AND X.CODFILIAL         = ZDEPARA_SHABILITACAOFILIAL.CODFILIAL_PARA
        AND X.CODTIPOCURSO      = ZDEPARA_SHABILITACAOFILIAL.NIVELENSINO
        AND X.CODCURSO          = ZDEPARA_SHABILITACAOFILIAL.CODCURSO_PARA
        AND X.CODHABILITACAO    = ZDEPARA_SHABILITACAOFILIAL.CODHABILITACAO_PARA
        AND X.CODGRADE          = ZDEPARA_SHABILITACAOFILIAL.CODGRADE_PARA
        AND X.CODTURNO           = ZDEPARA_SHABILITACAOFILIAL.CODTURNO_PARA
    )

SELECT * FROM ZMIGRA_SHABILITACAOFILIAL ORDER BY 1,2; 
