IF OBJECT_ID('ZMIGRA_BASE') IS NOT NULL
	DROP TABLE ZMIGRA_BASE
;

DECLARE @CODCOLIGADA AS INT = 13
DECLARE @ANOLETIVO AS INT = 2026

SELECT DISTINCT
	@CODCOLIGADA	                                        AS CODCOLIGADA,
	ZDEPARA_TURMAS.FILIAL_DE	                            AS CODFILIAL_DE,
	ZDEPARA_TURMAS.CURSO_DE									AS CURSO_DE,
	ZDEPARA_TURMAS.CODCURSO_PARA							AS CODCURSO,
	ZDEPARA_SHABILITACAOFILIAL.COD_MATRIZ					AS COD_MATRIZ_DE,
	ZDEPARA_SHABILITACAOFILIAL.CODIGO						AS CODHABILITACAO_DE,
	ZDEPARA_TURMAS.CODHABILITACAO_PARA						AS CODHABILITACAO,
	ZDEPARA_SHABILITACAOFILIAL.COD_MATRIZ					AS CODGRADE_DE,
	ZDEPARA_TURMAS.CODGRADE_PARA							AS CODGRADE_PARA,
	ZDEPARA_STURNO.TURNO									AS CODTURNO_DE,
	ZDEPARA_TURMAS.CODTURNO_PARA							AS CODTURNO_PARA,
	ZDEPARA_STURNO.DESCRICAO								AS TURNO_DE,
	ZDEPARA_TURMAS.NOMETURNO_PARA							AS TURNO_PARA,
	ZDEPARA_TURMAS.FILIAL_PARA								AS CODFILIAL,
	ZDEPARA_TURMAS.NIVEL_ENSINO								AS CODTIPOCURSO,
	ZDEPARA_TURMAS.CODIGO_DE								AS CODTURMA_DE,
	ZDEPARA_TURMAS.CODIGOTURMA_PARA							AS CODTURMA,
	ZDEPARA_TURMAS.PERIODO_LETIVO_DE						AS CODPERLET,
	BITB_ACOMPA_MAT.PES_ID									AS MATRICULA,
	ZDEPARA_SALUNO_RA.RA									AS RA,
	ZDEPARA_TURMAS.NOMETURMA_PARA 							AS NOME,
	CASE
		WHEN BITB_ACOMPA_MAT.MAL_SITMAT = 'ATIVO' THEN 'Matriculado'								
		WHEN BITB_ACOMPA_MAT.MAL_SITMAT = 'PREMAT' THEN 'Matriculado'								
	END AS STATUSRES,
	CASE
		WHEN BITB_ACOMPA_MAT.MAL_SITMAT = 'ATIVO' THEN 'Matriculado'								
		WHEN BITB_ACOMPA_MAT.MAL_SITMAT = 'PREMAT' THEN 'Matriculado'								
	END AS STATUS,
	--CAST(TB_INGRESSO.ING_DATENT AS DATE)					AS DTMATRICULA,
	TB_TURMA.TUR_SEQTUR										AS NUMALUNO
	INTO ZMIGRA_BASE
FROM ZMIGRA_SPESSOA_SALUNO
INNER JOIN BITB_ACOMPA_MAT
  ON BITB_ACOMPA_MAT.PES_ID 							= ZMIGRA_SPESSOA_SALUNO.IDENTIFICADOR2
LEFT JOIN TB_TURMA
  ON TB_TURMA.GRUPO_UNIDON 								= BITB_ACOMPA_MAT.GUN_ID
  AND TB_TURMA.UNIDON 									= BITB_ACOMPA_MAT.UNID_CODUNI
  AND TB_TURMA.TUR_ID 									= BITB_ACOMPA_MAT.TUR_ID
LEFT JOIN ZDEPARA_TURMAS
  ON TB_TURMA.TUR_ID 									= ZDEPARA_TURMAS.CODIGO_DE
  AND TB_TURMA.TUR_CURID 								= ZDEPARA_TURMAS.CURSO_DE
  AND TB_TURMA.TUR_FASE 								= ZDEPARA_TURMAS.SERIE_DE
  AND TB_TURMA.UNIDON 									= ZDEPARA_TURMAS.FILIAL_DE
  AND TB_TURMA.TUR_PERID 								= ZDEPARA_TURMAS.PERIODO_DE
LEFT JOIN ZDEPARA_SHABILITACAOFILIAL
  ON ZDEPARA_SHABILITACAOFILIAL.CODFILIAL           	= ZDEPARA_TURMAS.FILIAL_DE  
  AND ZDEPARA_SHABILITACAOFILIAL.COD_CURSO       		= ZDEPARA_TURMAS.CURSO_DE
  AND ZDEPARA_SHABILITACAOFILIAL.COD_SERIE           	= ZDEPARA_TURMAS.SERIE_DE
  AND ZDEPARA_SHABILITACAOFILIAL.ANO                 	= ZDEPARA_TURMAS.PERIODO_LETIVO_DE
LEFT JOIN ZDEPARA_STURNO
  ON ZDEPARA_STURNO.CODIGO 								= ZDEPARA_TURMAS.CODIGO_DE
  AND ZDEPARA_STURNO.CODFILIAL 							= ZDEPARA_TURMAS.FILIAL_DE
  AND ZDEPARA_STURNO.DESCRICAO 							= ZDEPARA_TURMAS.NOME_DE
LEFT JOIN TB_INGRESSO
  ON TB_INGRESSO.ING_PESID 								= BITB_ACOMPA_MAT.PES_ID
  AND TB_INGRESSO.ING_CURID 							= BITB_ACOMPA_MAT.CUR_ID
  AND TB_INGRESSO.ING_PELID = (SELECT TOP 1 PEL_PERID FROM TB_PERIODO_LETIVO WHERE PEL_ANOREF = @ANOLETIVO)
LEFT JOIN ZDEPARA_SALUNO_RA
  ON ZDEPARA_SALUNO_RA.MATRICULA 						= BITB_ACOMPA_MAT.PES_ID
WHERE TB_TURMA.TUR_PERID 								= (SELECT TOP 1 PEL_PERID FROM TB_PERIODO_LETIVO WHERE PEL_ANOREF = @ANOLETIVO)
  AND ZDEPARA_TURMAS.FILIAL_DE IS NOT NULL
  AND NOT ZDEPARA_TURMAS.CODCURSO_PARA = '%N%O IMPORTAR%'
  ;
-- ATUALIZA SITUAÇÃO DE MATRICULA PARA QUEM ESTA COM ELA NULL NO SISTEMA DE ORIGEM. COLOCA MATRICULADO POIS É OBRIGATÓRIA NO SISTEMA TOTVS
UPDATE ZMIGRA_BASE SET [STATUS] 						= 'Matriculado' WHERE STATUS IS NULL ;

SELECT * FROM ZMIGRA_BASE;
