IF OBJECT_ID('ZMIGRA_BASE_ESAD') IS NOT NULL
   DROP TABLE ZMIGRA_BASE_ESAD ;

SELECT 
      DADOS.*
	  INTO ZMIGRA_BASE_ESAD
FROM
(
SELECT 
    ZDEPARA_SHABILITACAOFILIAL.CODCOLIGADA                                         AS CODCOLIGADA,
	ZDEPARA_SHABILITACAOFILIAL.COD_CURSO                                           AS CURSO_DE,
	ZDEPARA_SHABILITACAOFILIAL.CODCURSO_PARA                                       AS CODCURSO,
	ZDEPARA_SHABILITACAOFILIAL.COD_MATRIZ                                          AS COD_MATRIZ_DE,
	ZDEPARA_SHABILITACAOFILIAL.COD_SERIE                                           AS CODHABILITACAO_DE,
	ZDEPARA_SHABILITACAOFILIAL.CODHABILITACAO_PARA                                 AS CODHABILITACAO,
	ZDEPARA_SGRADE.CODGRADE                                                        AS CODGRADE_DE,
	ZDEPARA_SHABILITACAOFILIAL.CODGRADE_PARA                                       AS CODGRADE_PARA,
	ZDEPARA_STURNO.CODIGO                                                          AS CODTURNO_DE,
	ZDEPARA_STURNO.DESCRICAO                                                       AS TURNO_DE,
	ZDEPARA_STURNO.DESCRICAO_PARA                                                  AS TURNO,
	ZDEPARA_SHABILITACAOFILIAL.CODFILIAL_PARA                                      AS CODFILIAL,
	ZDEPARA_SHABILITACAOFILIAL.NIVELENSINO                                         AS CODTIPOCURSO,
    SOPHIA.TURMAS.CODIGO                                                           AS CODTURMA, --SOPHIA.TURMAS.CODIGO
	'2025'                                                                         AS CODPERLET,
    SOPHIA.MATRICULA.FISICA                                                        AS FISICA,
	SOPHIA.MATRICULA.CODIGO                                                        AS MATRICULA,
	SOPHIA.MATRICULA.PERIODO                                                       AS SOPHIA_PERIODO,
	ZDEPARA_SALUNO_RA.RA                                                           AS RA,
	ZDEPARA_STATUS.DESCRICAO_PARA                                                  AS STATUSRES,
	ZDEPARA_STATUS.DESCRICAO_PARA                                                  AS STATUS,
	ISNULL(CAST(SOPHIA.MATRICULA.DATA_MATRICULA AS DATE),NULL)                     AS DTMATRICULA,
	SOPHIA.MATRICULA.NUM_CHAMADA                                                   AS NUMALUNO
	
 FROM 
      SOPHIA.TURMAS
	  LEFT JOIN SOPHIA.CURRICULO
	    ON SOPHIA.CURRICULO.CODIGO = SOPHIA.TURMAS.CURRICULO
	  LEFT JOIN SOPHIA.MATRICULA
	       LEFT JOIN ZDEPARA_SALUNO_RA
		     ON ZDEPARA_SALUNO_RA.FISICA = SOPHIA.MATRICULA.FISICA
	       LEFT JOIN SOPHIA.FISICA
		     ON SOPHIA.FISICA.CODIGO = SOPHIA.MATRICULA.FISICA
		   LEFT JOIN SOPHIA.SITUACAO_MATRICULA
		        LEFT JOIN ZDEPARA_STATUS
				  ON ZDEPARA_STATUS.CODIGO = SOPHIA.SITUACAO_MATRICULA.ID_SITUACAO_MATRICULA
		     ON SOPHIA.SITUACAO_MATRICULA.ID_SITUACAO_MATRICULA = SOPHIA.MATRICULA.STATUS
		   LEFT JOIN SOPHIA.SITUACAO_ALUNO
		     ON SOPHIA.SITUACAO_ALUNO.ID_SITUACAO_ALUNO = SOPHIA.MATRICULA.SIT_FINAL
		   JOIN SOPHIA.PERIODOS
		     ON SOPHIA.PERIODOS.CODIGO = SOPHIA.MATRICULA.PERIODO
	    ON SOPHIA.MATRICULA.TURMA_REGULAR = SOPHIA.TURMAS.CODIGO
	  LEFT JOIN SOPHIA.TURNOS
	       LEFT JOIN ZDEPARA_STURNO
		     ON ZDEPARA_STURNO.CODIGO = SOPHIA.TURNOS.CODIGO
	    ON SOPHIA.TURNOS.CODIGO = SOPHIA.TURMAS.TURNO
	  JOIN ZDEPARA_SHABILITACAOFILIAL
	       JOIN ZDEPARA_SGRADE
                JOIN ZDEPARA_SPLETIVO
		          ON ZDEPARA_SPLETIVO.CODIGO_DE = ZDEPARA_SGRADE.CODANO
	         ON ZDEPARA_SGRADE.CODCURSO       = ZDEPARA_SHABILITACAOFILIAL.COD_CURSO
	        AND ZDEPARA_SGRADE.CODHABILITACAO = ZDEPARA_SHABILITACAOFILIAL.COD_MATRIZ
	        AND ZDEPARA_SGRADE.CODGRADE       = ZDEPARA_SHABILITACAOFILIAL.CODIGO
		    AND ZDEPARA_SGRADE.CODIGO_SERIE   = ZDEPARA_SHABILITACAOFILIAL.COD_SERIE    
		    AND ZDEPARA_SGRADE.ANO            = ZDEPARA_SHABILITACAOFILIAL.ANO
	    ON ZDEPARA_SHABILITACAOFILIAL.COD_CURSO  = SOPHIA.TURMAS.CURSO
	   AND ZDEPARA_SHABILITACAOFILIAL.COD_MATRIZ = SOPHIA.CURRICULO.CODIGO
	   AND ZDEPARA_SHABILITACAOFILIAL.COD_SERIE  = SOPHIA.TURMAS.SERIE
	   AND ZDEPARA_SHABILITACAOFILIAL.COD_TURNO  = SOPHIA.TURMAS.TURNO
	   AND ZDEPARA_SPLETIVO.CODIGO_DE = SOPHIA.PERIODOS.CODIGO
	   AND ZDEPARA_SHABILITACAOFILIAL.CODCOLIGADA    = ZDEPARA_STATUS.CODCOLIGADA
	   AND ZDEPARA_SHABILITACAOFILIAL.CODFILIAL_PARA = ZDEPARA_STATUS.CODFILIAL
	   AND ZDEPARA_SHABILITACAOFILIAL.NIVELENSINO    = ZDEPARA_STATUS.NIVELENSINO
 --WHERE
 --     ZDEPARA_SALUNO_RA.BASE = 'PLE'
 -- AND ZDEPARA_SHABILITACAOFILIAL.CODCURSO_PARA = 'ESAD'     
 GROUP BY 
      ZDEPARA_SHABILITACAOFILIAL.CODCOLIGADA,        
	  ZDEPARA_SHABILITACAOFILIAL.COD_CURSO,          
	  ZDEPARA_SHABILITACAOFILIAL.CODCURSO_PARA,      
	  ZDEPARA_SHABILITACAOFILIAL.COD_MATRIZ,         
	  ZDEPARA_SHABILITACAOFILIAL.CODHABILITACAO_PARA,
	  ZDEPARA_SHABILITACAOFILIAL.CODGRADE_PARA,      
	  ZDEPARA_SHABILITACAOFILIAL.CODGRADE_PARA,      
	  ZDEPARA_STURNO.CODIGO,                         
	  ZDEPARA_STURNO.DESCRICAO,                      
	  ZDEPARA_STURNO.DESCRICAO_PARA,                 
	  ZDEPARA_SHABILITACAOFILIAL.CODFILIAL_PARA,     
	  ZDEPARA_SHABILITACAOFILIAL.NIVELENSINO,        
	  SOPHIA.TURMAS.CODIGO,                          
	  ZDEPARA_SPLETIVO.CODIGO_PARA,                  
	  SOPHIA.MATRICULA.FISICA,                      
	  SOPHIA.MATRICULA.CODIGO,                       
	  SOPHIA.MATRICULA.PERIODO,                      
	  ZDEPARA_SALUNO_RA.RA,                          
	  ZDEPARA_STATUS.DESCRICAO_PARA,                 
	  ZDEPARA_STATUS.DESCRICAO_PARA,                 
	  SOPHIA.MATRICULA.DATA_MATRICULA,
	  SOPHIA.MATRICULA.NUM_CHAMADA,
	  ZDEPARA_SGRADE.CODGRADE,
	  ZDEPARA_SHABILITACAOFILIAL.COD_SERIE	  
) AS DADOS ;

SELECT * FROM ZMIGRA_BASE_ESAD ;
