IF OBJECT_ID ('ZINSERT_SPROFESSORFILIAL') IS NOT NULL
DROP TABLE ZINSERT_SPROFESSORFILIAL ; 

SELECT 
      Z.CODCOLIGADA,
      Z.CODFILIAL,
      Z.CODPROF,
      'NULL' AS MATRICULAPROTHEUS,
      'NULL' AS CHAPA,
      'S' AS ATIVO,
      ROW_NUMBER() OVER (ORDER BY Z.CODPROF) AS IDPROFESSORFILIAL
      INTO ZINSERT_SPROFESSORFILIAL
  FROM 
      ZMIGRA_SHORARIOBASE Z
 WHERE 
      Z.CODPROF IS NOT NULL
GROUP BY 
    Z.CODCOLIGADA,
    Z.CODFILIAL,
    Z.CODPROF;

SELECT * FROM ZINSERT_SPROFESSORFILIAL;

--SP_GENERATEINSERT ZINSERT_SPROFESSORFILIAL, SPROFESSORFILIAL

