IF OBJECT_ID('ZMIGRA_STURMA') IS NOT NULL
    DROP TABLE ZMIGRA_STURMA;
GO

IF OBJECT_ID('dbo.fn_RemoveAcentos', 'FN') IS NOT NULL
    DROP FUNCTION dbo.fn_RemoveAcentos;
GO

CREATE FUNCTION dbo.fn_RemoveAcentos
(
    @Texto NVARCHAR(MAX)
)
RETURNS NVARCHAR(MAX)
AS
BEGIN
    RETURN TRANSLATE
    (
        @Texto,
        N'ÁÀÃÂÄáàãâäÉÈÊËéèêëÍÌÎÏíìîïÓÒÕÔÖóòõôöÚÙÛÜúùûüÇçÑñÝŸýÿ',
        N'AAAAAaaaaaEEEEeeeeIIIIiiiiOOOOOoooooUUUUuuuuCcNnYYyy'
    );
END;
GO

DECLARE @ANOLETIVO INT = 2026;

DECLARE @CODPERIODO INT =
(
    SELECT TOP (1) CODIGO_DE
    FROM ZDEPARA_SPLETIVO
    WHERE DESCRICAO = @ANOLETIVO
);

WITH DADOS AS
(
    SELECT
        ZMIGRA_BASE.CODCOLIGADA,
        ZMIGRA_BASE.CODCURSO,
        ZMIGRA_BASE.CODHABILITACAO,
        ZMIGRA_BASE.CODGRADE_PARA AS CODGRADE,
        ZDADOSORI_STURNO.NOME AS TURNO,
        CAST(ZMIGRA_BASE.CODFILIAL AS INT) AS CODFILIAL,
        CAST(ZMIGRA_BASE.CODTIPOCURSO AS INT) AS CODTIPOCURSO,
        CAST(ZMIGRA_BASE.CODPERLET AS INT) AS CODPERLET,
        ZMIGRA_BASE.CODTURMA,
        NULL AS CODDEPARTAMENTO,
        NULL AS CODPREDIO,
        NULL AS CODSALA,
        NULL AS CODCCUSTO,
        REPLACE(dbo.fn_RemoveAcentos(ZMIGRA_BASE.CODTURMA),'º','') AS NOMERED,
        REPLACE(dbo.fn_RemoveAcentos(ZMIGRA_BASE.NOME),'º','') AS NOME,
        TB_TURMA.TUR_MAXVAG AS MAXALUNOS,
        NULL AS DTINICIAL,
        NULL AS DTFINAL,
        NULL AS ALUNOSLABORE,
        NULL AS DTALUNOSLABORE,
        NULL AS CODTURMAPROX,
        NULL AS CODCAMPUS,
        NULL AS CODBLOCO,
        NULL AS TIPOMEDIACAO,

        ROW_NUMBER() OVER
        (
            PARTITION BY
                ZMIGRA_BASE.CODCOLIGADA,
                ZMIGRA_BASE.CODCURSO,
                ZMIGRA_BASE.CODHABILITACAO,
                ZMIGRA_BASE.CODGRADE_PARA,
                ZMIGRA_BASE.CODFILIAL,
                ZMIGRA_BASE.CODTIPOCURSO,
                ZMIGRA_BASE.CODPERLET,
                ZMIGRA_BASE.CODTURMA
            ORDER BY
                TB_TURMA.TUR_MAXVAG DESC
        ) AS RN

    FROM ZMIGRA_BASE

    JOIN ZDADOSORI_STURNO
        ON ZDADOSORI_STURNO.CODCOLIGADA = ZMIGRA_BASE.CODCOLIGADA
       AND ZDADOSORI_STURNO.CODTURNO = ZMIGRA_BASE.CODTURNO_PARA

    LEFT JOIN TB_TURMA
        ON TB_TURMA.TUR_ID = ZMIGRA_BASE.CODTURMA_DE
       AND TB_TURMA.TUR_CURID = ZMIGRA_BASE.CURSO_DE
       AND TB_TURMA.UNIDON = ZMIGRA_BASE.CODFILIAL_DE
       AND TB_TURMA.TUR_TURNO = LEFT(ZMIGRA_BASE.CODTURNO_DE, 1)
       AND TB_TURMA.TUR_FASE = ZMIGRA_BASE.CODHABILITACAO_DE
       AND TB_TURMA.TUR_PERID = @CODPERIODO
)

SELECT
    CODCOLIGADA,
    CODCURSO,
    CODHABILITACAO,
    CODGRADE,
    TURNO,
    CODFILIAL,
    CODTIPOCURSO,
    CODPERLET,
    CODTURMA,
    CODDEPARTAMENTO,
    CODPREDIO,
    CODSALA,
    CODCCUSTO,
    NOMERED,
    NOME,
    MAXALUNOS,
    DTINICIAL,
    DTFINAL,
    ALUNOSLABORE,
    DTALUNOSLABORE,
    CODTURMAPROX,
    CODCAMPUS,
    CODBLOCO,
    TIPOMEDIACAO
INTO ZMIGRA_STURMA
FROM DADOS
WHERE RN = 1;

DROP FUNCTION dbo.fn_RemoveAcentos;
GO

SELECT *
FROM ZMIGRA_STURMA;