IF OBJECT_ID('ZMIGRA_SPROFESSORTURMA') IS NOT NULL
	DROP TABLE ZMIGRA_SPROFESSORTURMA
;

DECLARE @ANOLETIVO AS INTEGER = 2026

SELECT DISTINCT
	CAST(ZMIGRA_BASE.CODCOLIGADA AS INT)           											AS CODCOLIGADA,
	ZMIGRA_BASE.CODCURSO	           														AS CODCURSO,
	ZMIGRA_BASE.CODHABILITACAO           													AS CODHABILITACAO,
	ZMIGRA_BASE.CODGRADE_PARA           													AS CODGRADE,
	ZDADOSORI_STURNO.NOME         															AS TURNO,
	CAST(ZMIGRA_BASE.CODFILIAL AS INT)           											AS CODFILIAL,
	CAST(ZMIGRA_BASE.CODTIPOCURSO AS INT)                									AS CODTIPOCURSO,
	CAST(ZMIGRA_BASE.CODPERLET AS INT)           											AS CODPERLET,
	ZMIGRA_BASE.CODTURMA           															AS CODTURMA,
	ZDEPARA_SDISCIPLINAS.CODIGO_PARA                										AS CODDISC,
	CAST(TB_TURMADISCIP_PROF.TDP_PESID AS INT)		          								AS CODPROF,
	FORMAT(TB_TURMA.TUR_DATINI, 'dd/MM/yyyy')                								AS DTINICIO,
	FORMAT(TB_TURMA.TUR_DATFIN, 'dd/MM/yyyy')												AS DTFIM,
	NULL                																	AS VALORHORA,
	NULL                																	AS AULASSEMANAISPROF,
	NULL                																	AS VALORFIXO,
	'T'                																		AS TIPOPROF,
	'S'                																		AS DESCONSIDERAPONTO,
	NULL                																	AS PERCENTFATURAMENTO,
	NULL                																	AS COMPOESALARIO,
	NULL                																	AS CODTIPOPART,
	NULL                																	AS STATUS
	INTO ZMIGRA_SPROFESSORTURMA
FROM ZMIGRA_BASE
LEFT JOIN TB_TURMA
  ON TB_TURMA.TUR_ID = ZMIGRA_BASE.CODTURMA_DE
  AND TB_TURMA.TUR_CURID = ZMIGRA_BASE.CURSO_DE
  AND TB_TURMA.UNIDON = ZMIGRA_BASE.CODFILIAL_DE
  AND TB_TURMA.TUR_TURNO = LEFT(ZMIGRA_BASE.CODTURNO_DE, 1)
  AND TB_TURMA.TUR_FASE = ZMIGRA_BASE.CODHABILITACAO_DE
  AND TB_TURMA.TUR_PERID = (SELECT TOP 1 CODIGO_DE FROM ZDEPARA_SPLETIVO WHERE DESCRICAO = @ANOLETIVO)
LEFT JOIN TB_TURMA_DISCIP
  ON TB_TURMA_DISCIP.TDI_TURID = TB_TURMA.TUR_ID
  AND TB_TURMA_DISCIP.GRUPO_UNIDON = TB_TURMA.GRUPO_UNIDON
  AND TB_TURMA_DISCIP.UNIDON = TB_TURMA.UNIDON
LEFT JOIN ZDEPARA_SDISCIPLINAS
  ON ZDEPARA_SDISCIPLINAS.CODIGO = TB_TURMA_DISCIP.TDI_DISCID
JOIN TB_TURMADISCIP_PROF
  ON TB_TURMADISCIP_PROF.TDP_TDIID = TB_TURMA_DISCIP.TDI_TURDISID
JOIN ZMIGRA_SPESSOA_SPROFESSOR
  ON ZMIGRA_SPESSOA_SPROFESSOR.CODPROF = TB_TURMADISCIP_PROF.TDP_PESID
JOIN ZDADOSORI_STURNO
  ON ZDADOSORI_STURNO.CODCOLIGADA = ZMIGRA_BASE.CODCOLIGADA
  AND ZDADOSORI_STURNO.CODTURNO = ZMIGRA_BASE.CODTURNO_PARA
WHERE ZDEPARA_SDISCIPLINAS.CODIGO_PARA NOT LIKE 'NÃO IMPORTAR';

SELECT * FROM ZMIGRA_SPROFESSORTURMA ;