IF OBJECT_ID('ZMIGRA_SHORARIOTURMA') IS NOT NULL
	DROP TABLE ZMIGRA_SHORARIOTURMA
;

DECLARE @ANOLETIVO AS INTEGER = 2026

SELECT DISTINCT
	CAST(ZMIGRA_SHORARIOBASE.CODCOLIGADA AS INT)                            AS CODCOLIGADA,
	ZMIGRA_SHORARIOBASE.CODCURSO	                             			AS CODCURSO,
	ZMIGRA_SHORARIOBASE.CODHABILITACAO                              		AS CODHABILITACAO,
	ZMIGRA_SHORARIOBASE.CODGRADE                              				AS CODGRADE,
	ZDADOSORI_STURNO.NOME 	                            					AS TURNO,
	CAST(ZMIGRA_SHORARIOBASE.CODFILIAL AS INT)	                            AS CODFILIAL,
	CAST(ZMIGRA_SHORARIOBASE.NIVELENSINO AS INT)                            AS CODTIPOCURSO,
	CAST(ZMIGRA_SHORARIOBASE.PERIODO_PARA AS INT)                           AS CODPERLET,
	ZMIGRA_SHORARIOBASE.CODTURMA_PARA                     					AS CODTURMA,
	ZDEPARA_SDISCIPLINAS.CODIGO_PARA           								AS CODDISC,
	NULL                                 									AS CODPREDIO,
	NULL                                 									AS CODSALA,
	ZMIGRA_SHORARIOBASE.SEMANA			                         			AS DIASEMANA,
	ZMIGRA_SHORARIOBASE.HORARIO_INICIAL                    					AS HORAINICIAL,
	ZMIGRA_SHORARIOBASE.HORARIO_FINAL		                      			AS HORAFINAL,
	NULL                                 									AS DATAINICIAL,
	NULL                                 									AS DATAFINAL,
	NULL                                 									AS LOCACAO,
	NULL                                 									AS CODBLOCO,
	NULL                                 									AS TIPOSALA
	INTO ZMIGRA_SHORARIOTURMA
FROM ZMIGRA_BASE
JOIN ZMIGRA_SHORARIOBASE
  ON ZMIGRA_SHORARIOBASE.CODCOLIGADA = ZMIGRA_BASE.CODCOLIGADA
  AND ZMIGRA_SHORARIOBASE.CODFILIAL = ZMIGRA_BASE.CODFILIAL
  AND ZMIGRA_SHORARIOBASE.CODCURSO= ZMIGRA_BASE.CODCURSO
  AND ZMIGRA_SHORARIOBASE.CODTURMA_PARA = ZMIGRA_BASE.CODTURMA
JOIN ZDEPARA_SDISCIPLINAS
  ON ZDEPARA_SDISCIPLINAS.CODIGO_PARA = ZMIGRA_SHORARIOBASE.CODDISC_PARA
JOIN ZDADOSORI_STURNO
  ON ZDADOSORI_STURNO.CODCOLIGADA = ZMIGRA_BASE.CODCOLIGADA
  AND ZDADOSORI_STURNO.CODTURNO = ZMIGRA_BASE.CODTURNO_PARA

SELECT * FROM ZMIGRA_SHORARIOTURMA ORDER BY CODFILIAL, CODTURMA, DIASEMANA, HORAINICIAL ;