IF OBJECT_ID('ZMIGRA_SHORARIOPROFESSOR') IS NOT NULL
    DROP TABLE ZMIGRA_SHORARIOPROFESSOR
;

DECLARE @ANOLETIVO AS INTEGER = 2026

SELECT DISTINCT
    CAST(ZMIGRA_SHORARIOBASE.CODCOLIGADA AS INT)                                  AS CODCOLIGADA,
    ZMIGRA_SHORARIOBASE.CODCURSO                                                  AS CODCURSO,
    ZMIGRA_SHORARIOBASE.CODHABILITACAO                                            AS CODHABILITACAO,
    ZMIGRA_SHORARIOBASE.CODGRADE                                                  AS CODGRADE,
    ZDADOSORI_STURNO.NOME                                                         AS TURNO,
    CAST(ZMIGRA_SHORARIOBASE.CODFILIAL AS INT)                                    AS CODFILIAL,
    CAST(ZMIGRA_SHORARIOBASE.NIVELENSINO AS INT)                                  AS CODTIPOCURSO,
    CAST(ZMIGRA_SHORARIOBASE.PERIODO_PARA AS INT)                                 AS CODPERLET,
    ZMIGRA_SHORARIOBASE.CODTURMA_PARA                                             AS CODTURMA,
    ZDEPARA_SDISCIPLINAS.CODIGO_PARA                                              AS CODDISC,
    ZMIGRA_SHORARIOBASE.CODPROF                                                   AS CODPROF,
    CAST(ZMIGRA_SHORARIOBASE.SEMANA AS INT)                                       AS DIASEMANA,
    ZMIGRA_SHORARIOBASE.HORARIO_INICIAL                                           AS HORAINICIAL,
    ZMIGRA_SHORARIOBASE.HORARIO_FINAL                                             AS HORAFINAL,
    'S'                                                                           AS DESCONSIDERAPONTO,
    NULL                                                                          AS DATAINICIAL,
    NULL                                                                          AS DATAFINAL
    INTO ZMIGRA_SHORARIOPROFESSOR
FROM ZMIGRA_BASE
JOIN ZMIGRA_SHORARIOBASE
  ON ZMIGRA_SHORARIOBASE.CODCOLIGADA = ZMIGRA_BASE.CODCOLIGADA
  AND ZMIGRA_SHORARIOBASE.CODFILIAL = ZMIGRA_BASE.CODFILIAL
  AND ZMIGRA_SHORARIOBASE.CODCURSO= ZMIGRA_BASE.CODCURSO
  AND ZMIGRA_SHORARIOBASE.CODTURMA_PARA = ZMIGRA_BASE.CODTURMA
JOIN ZDEPARA_SDISCIPLINAS
  ON ZDEPARA_SDISCIPLINAS.CODIGO_PARA = ZMIGRA_SHORARIOBASE.CODDISC_PARA
JOIN ZDADOSORI_STURNO
  ON ZDADOSORI_STURNO.CODCOLIGADA = ZMIGRA_BASE.CODCOLIGADA
  AND ZDADOSORI_STURNO.CODTURNO = ZMIGRA_BASE.CODTURNO_PARA
WHERE ZDEPARA_SDISCIPLINAS.CODIGO_PARA NOT LIKE 'NÃO IMPORTAR';

SELECT * FROM ZMIGRA_SHORARIOPROFESSOR ORDER BY CODFILIAL, CODTURMA, DIASEMANA, HORAINICIAL;