IF OBJECT_ID('ZMIGRA_SMATRICPL') IS NOT NULL
	DROP TABLE ZMIGRA_SMATRICPL
;

SELECT DISTINCT
	CAST(ZMIGRA_BASE.CODCOLIGADA AS INT)                AS CODCOLIGADA,
	ZMIGRA_BASE.CODCURSO	                     		AS CODCURSO,
	ZMIGRA_BASE.CODHABILITACAO                     		AS CODHABILITACAO,
	ZMIGRA_BASE.CODGRADE_PARA                    		AS CODGRADE,
	ZDADOSORI_STURNO.NOME                     			AS TURNO,
	CAST(ZMIGRA_BASE.CODFILIAL AS INT)                  AS CODFILIAL,
	CAST(ZMIGRA_BASE.CODTIPOCURSO AS INT)               AS CODTIPOCURSO,
	ZMIGRA_BASE.CODTURMA                    			AS CODTURMA,
	CAST(ZMIGRA_BASE.CODPERLET AS INT)                  AS CODPERLET,
	ZMIGRA_BASE.RA                     					AS RA,
	CASE
		WHEN ZMIGRA_BASE.CODTIPOCURSO = 2 THEN 'Cursando'
		ELSE ZMIGRA_BASE.STATUSRES                     			
	END AS STATUSRES,
	CASE
		WHEN ZMIGRA_BASE.CODTIPOCURSO = 2 THEN 'Cursando'
		ELSE ZMIGRA_BASE.STATUS
	END AS STATUS,
	ZMIGRA_BASE.DTMATRICULA                     		AS DTMATRICULA,
	NULL                        						AS DTRESULTADO,
	NULL                        						AS IDENTIFICADOR,
	NULL                        						AS NUMCARTEIRA,
	NULL                        						AS CARTEIRAEMITIDA,
	NULL                        						AS VIACARTEIRA,
	NULL                        						AS PERIODO,
	NULL				                     			AS NUMALUNO,
	NULL                        						AS DESCTIPOMAT,
	NULL                        						AS SELINSTENADE,
	NULL                        						AS SELMECENADE,
	NULL                        						AS DTPROVAENADE,
	NULL                        						AS COMPARECEUENADE,
	NULL                        						AS OBSENADE,
	NULL                        						AS DTMATRICULAENCERRA
	INTO ZMIGRA_SMATRICPL
FROM ZMIGRA_BASE
JOIN ZDADOSORI_STURNO
  ON ZDADOSORI_STURNO.CODCOLIGADA = ZMIGRA_BASE.CODCOLIGADA
  AND ZDADOSORI_STURNO.CODTURNO = ZMIGRA_BASE.CODTURNO_PARA
WHERE ZMIGRA_BASE.STATUS <> 'NÃO IMPORTAR'

SELECT * FROM ZMIGRA_SMATRICPL ;