DECLARE @ANOLETIVO AS INT = 2026;

SELECT DISTINCT
    ZMIGRA_BASE.CODCURSO,
    ZMIGRA_BASE.CODTURMA,
    ZDEPARA_SDISCGRADE.CODDISC_PARA,
    ZMIGRA_BASE.MATRICULA,
    ZMIGRA_BASE.CODPERLET,
    TB_AVAPAR_CADAVA.APC_DESCRI
FROM TB_CONTRATO_FIN 
JOIN TB_TURMA AS TB_TURMA 
  ON TB_CONTRATO_FIN.CFI_TURID = TB_TURMA.TUR_ID
JOIN TB_TURMA_DISCIP AS TB_TURMA_DISCIP 
  ON TB_TURMA.TUR_ID = TB_TURMA_DISCIP.TDI_TURID
JOIN TB_AVAPAR_CADAVA AS TB_AVAPAR_CADAVA 
  ON TB_TURMA_DISCIP.TDI_TURDISID = TB_AVAPAR_CADAVA.APC_TDIID
JOIN ZDEPARA_SDISCIPLINAS AS ZDEPARA_SDISCIPLINAS 
  ON TB_TURMA_DISCIP.TDI_DISCID = ZDEPARA_SDISCIPLINAS.CODIGO
JOIN ZMIGRA_BASE
  ON ZMIGRA_BASE.CURSO_DE = TB_CONTRATO_FIN.CFI_CURID
  AND ZMIGRA_BASE.CODTURMA_DE = TB_TURMA.TUR_ID
  AND ZMIGRA_BASE.MATRICULA = TB_CONTRATO_FIN.CFI_PESID
JOIN ZDEPARA_SDISCGRADE
  ON ZMIGRA_BASE.CODCOLIGADA = ZDEPARA_SDISCGRADE.CODCOLIGADA
  AND ZMIGRA_BASE.CODCURSO = ZDEPARA_SDISCGRADE.CODCURSO_PARA
  AND ZMIGRA_BASE.CODHABILITACAO = ZDEPARA_SDISCGRADE.CODHABILITACAO_PARA
  AND ZMIGRA_BASE.CODGRADE_PARA = ZDEPARA_SDISCGRADE.CODGRADE_PARA
  AND ZMIGRA_BASE.CODPERLET = ZDEPARA_SDISCGRADE.CODPERIODO_PARA
  AND TB_TURMA_DISCIP.TDI_DISCID = ZDEPARA_SDISCGRADE.DISCIPLINA
WHERE TB_CONTRATO_FIN.CFI_PERID = ( SELECT TOP 1 PEL_PERID FROM TB_PERIODO_LETIVO WHERE PEL_ANOREF = @ANOLETIVO )