IF OBJECT_ID('ZMIGRA_SNOTAETAPA') IS NOT NULL
   DROP TABLE ZMIGRA_SNOTAETAPA ;

SELECT
      DADOS.*
	  INTO ZMIGRA_SNOTAETAPA
  FROM (
SELECT DISTINCT
	  ZMIGRA_BASE.CODCOLIGADA                                                               AS CODCOLIGADA,
      ZMIGRA_BASE.CODCURSO                                                                  AS CODCURSO,
      ZMIGRA_BASE.CODHABILITACAO                                                            AS CODHABILITACAO,
      ZMIGRA_BASE.CODGRADE_PARA                                                             AS CODGRADE,
      ZMIGRA_BASE.TURNO                                                                     AS TURNO,
      ZMIGRA_BASE.CODFILIAL                                                                 AS CODFILIAL,
      ZMIGRA_BASE.CODTIPOCURSO                                                              AS CODTIPOCURSO,
      ZMIGRA_BASE.RA                                                                        AS RA,
      ZMIGRA_BASE.CODTURMA                                                                  AS CODTURMA,
      ZMIGRA_BASE.CODPERLET                                                                 AS CODPERLET,
      ZDEPARA_SDISCIPLINAS.CODIGO_PARA                                                      AS CODDISC,
      '100'+CAST(SOPHIA.ETAPAS.NUMERO AS VARCHAR)                                           AS CODETAPA,
      'N'                                                                                   AS TIPOETAPA,
      NULL                                                                                  AS CONCEITO,
      REPLACE(CAST(CASE 
	      WHEN SOPHIA.ETAPAS.NUMERO = 1 THEN (SELECT DISTINCT AC.MEDIA1 FROM SOPHIA.ACADEMIC AS AC WHERE AC.TURMA = SOPHIA.TURMAS.CODIGO AND AC.DISCIPLINA = ZDEPARA_SDISCIPLINAS.CODIGO AND AC.MATRICULA = SOPHIA.MATRICULA.CODIGO)
		  WHEN SOPHIA.ETAPAS.NUMERO = 2 THEN (SELECT DISTINCT AC.MEDIA2 FROM SOPHIA.ACADEMIC AS AC WHERE AC.TURMA = SOPHIA.TURMAS.CODIGO AND AC.DISCIPLINA = ZDEPARA_SDISCIPLINAS.CODIGO AND AC.MATRICULA = SOPHIA.MATRICULA.CODIGO)
		  WHEN SOPHIA.ETAPAS.NUMERO = 3 THEN (SELECT DISTINCT AC.MEDIA3 FROM SOPHIA.ACADEMIC AS AC WHERE AC.TURMA = SOPHIA.TURMAS.CODIGO AND AC.DISCIPLINA = ZDEPARA_SDISCIPLINAS.CODIGO AND AC.MATRICULA = SOPHIA.MATRICULA.CODIGO)
		  WHEN SOPHIA.ETAPAS.NUMERO = 4 THEN (SELECT DISTINCT AC.MEDIA4 FROM SOPHIA.ACADEMIC AS AC WHERE AC.TURMA = SOPHIA.TURMAS.CODIGO AND AC.DISCIPLINA = ZDEPARA_SDISCIPLINAS.CODIGO AND AC.MATRICULA = SOPHIA.MATRICULA.CODIGO)
		  WHEN SOPHIA.ETAPAS.NUMERO = 5 THEN (SELECT DISTINCT AC.MEDIA5 FROM SOPHIA.ACADEMIC AS AC WHERE AC.TURMA = SOPHIA.TURMAS.CODIGO AND AC.DISCIPLINA = ZDEPARA_SDISCIPLINAS.CODIGO AND AC.MATRICULA = SOPHIA.MATRICULA.CODIGO)
		  WHEN SOPHIA.ETAPAS.NUMERO = 6 THEN (SELECT DISTINCT AC.MEDIA6 FROM SOPHIA.ACADEMIC AS AC WHERE AC.TURMA = SOPHIA.TURMAS.CODIGO AND AC.DISCIPLINA = ZDEPARA_SDISCIPLINAS.CODIGO AND AC.MATRICULA = SOPHIA.MATRICULA.CODIGO)
		  WHEN SOPHIA.ETAPAS.NUMERO = 7 THEN (SELECT DISTINCT AC.MEDIA7 FROM SOPHIA.ACADEMIC AS AC WHERE AC.TURMA = SOPHIA.TURMAS.CODIGO AND AC.DISCIPLINA = ZDEPARA_SDISCIPLINAS.CODIGO AND AC.MATRICULA = SOPHIA.MATRICULA.CODIGO)
		  WHEN SOPHIA.ETAPAS.NUMERO = 8 THEN (SELECT DISTINCT AC.MEDIA8 FROM SOPHIA.ACADEMIC AS AC WHERE AC.TURMA = SOPHIA.TURMAS.CODIGO AND AC.DISCIPLINA = ZDEPARA_SDISCIPLINAS.CODIGO AND AC.MATRICULA = SOPHIA.MATRICULA.CODIGO)
		  WHEN SOPHIA.ETAPAS.NUMERO = 9 THEN (SELECT DISTINCT AC.MEDIA9 FROM SOPHIA.ACADEMIC AS AC WHERE AC.TURMA = SOPHIA.TURMAS.CODIGO AND AC.DISCIPLINA = ZDEPARA_SDISCIPLINAS.CODIGO AND AC.MATRICULA = SOPHIA.MATRICULA.CODIGO)
		  WHEN SOPHIA.ETAPAS.NUMERO = 13 THEN (SELECT DISTINCT AC.MEDIA_ANUAL FROM SOPHIA.ACADEMIC AS AC WHERE AC.TURMA = SOPHIA.TURMAS.CODIGO AND AC.DISCIPLINA = ZDEPARA_SDISCIPLINAS.CODIGO AND AC.MATRICULA = SOPHIA.MATRICULA.CODIGO)
		  WHEN SOPHIA.ETAPAS.NUMERO = 14 THEN (SELECT DISTINCT AC.REC_FINAL FROM SOPHIA.ACADEMIC AS AC WHERE AC.TURMA = SOPHIA.TURMAS.CODIGO AND AC.DISCIPLINA = ZDEPARA_SDISCIPLINAS.CODIGO AND AC.MATRICULA = SOPHIA.MATRICULA.CODIGO)
		  WHEN SOPHIA.ETAPAS.NUMERO = 16 THEN (SELECT DISTINCT AC.MEDIA_FINAL FROM SOPHIA.ACADEMIC AS AC WHERE AC.TURMA = SOPHIA.TURMAS.CODIGO AND AC.DISCIPLINA = ZDEPARA_SDISCIPLINAS.CODIGO AND AC.MATRICULA = SOPHIA.MATRICULA.CODIGO)
	   END AS VARCHAR),'.',',')                                                             AS NOTA,
      NULL                                                                                  AS NUMACERTOS
  FROM 
      SOPHIA.TURMAS
      JOIN ZMIGRA_BASE
           JOIN SOPHIA.MATRICULA
		        JOIN SOPHIA.ACADEMIC
				  ON SOPHIA.ACADEMIC.MATRICULA = SOPHIA.MATRICULA.CODIGO
	  	     ON SOPHIA.MATRICULA.CODIGO = ZMIGRA_BASE.MATRICULA
        ON ZMIGRA_BASE.CODTURMA_DE    = SOPHIA.TURMAS.CODIGO 
       AND ZMIGRA_BASE.SOPHIA_PERIODO = SOPHIA.TURMAS.PERIODO
       AND ZMIGRA_BASE.CODTURNO_DE    = SOPHIA.TURMAS.TURNO
       AND ZMIGRA_BASE.CURSO_DE       = SOPHIA.TURMAS.CURSO
       AND ZMIGRA_BASE.RA IS NOT NULL 
      JOIN SOPHIA.QC 
	       JOIN ZDEPARA_SDISCIPLINAS 
	         ON ZDEPARA_SDISCIPLINAS.CODIGO = QC.DISCIPLINA
	      ON SOPHIA.QC.TURMA = SOPHIA.TURMAS.CODIGO
      JOIN SOPHIA.CFG_ACAD 
	         JOIN SOPHIA.ETAPAS
             ON SOPHIA.ETAPAS.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO
	      ON SOPHIA.CFG_ACAD.CODIGO  = SOPHIA.TURMAS.CFG_ACAD
	     AND SOPHIA.ACADEMIC.DISCIPLINA = SOPHIA.QC.DISCIPLINA
 WHERE 
      SOPHIA.QC.TIPO_NOTA = 0
  AND SOPHIA.TURMAS.CURSO IS NOT NULL
  AND SOPHIA.TURMAS.SERIE IS NOT NULL
GROUP BY 
      ZMIGRA_BASE.CODCOLIGADA,          
      ZMIGRA_BASE.CODCURSO,             
      ZMIGRA_BASE.CODHABILITACAO,       
      ZMIGRA_BASE.CODGRADE_PARA,        
      ZMIGRA_BASE.TURNO,                
      ZMIGRA_BASE.CODFILIAL,            
      ZMIGRA_BASE.CODTIPOCURSO,         
      ZMIGRA_BASE.RA,
      ZMIGRA_BASE.CODTURMA,
      TURMAS.CODIGO,                   
      ZMIGRA_BASE.CODPERLET,            
      ZDEPARA_SDISCIPLINAS.CODIGO_PARA,
      SOPHIA.ETAPAS.NUMERO,
	  SOPHIA.CFG_ACAD.CODIGO,
	  SOPHIA.ACADEMIC.MEDIA1,
	  SOPHIA.ACADEMIC.MEDIA2,
	  SOPHIA.ACADEMIC.MEDIA3,
	  SOPHIA.ACADEMIC.MEDIA4,
	  SOPHIA.ACADEMIC.MEDIA5,
	  SOPHIA.ACADEMIC.MEDIA6,
	  SOPHIA.ACADEMIC.MEDIA7,
	  SOPHIA.ACADEMIC.MEDIA8,
	  SOPHIA.ACADEMIC.MEDIA9,
	  SOPHIA.ACADEMIC.MEDIA_ANUAL,
	  SOPHIA.ACADEMIC.REC_FINAL,
	  SOPHIA.ACADEMIC.MEDIA_FINAL,
	  ZDEPARA_SDISCIPLINAS.CODIGO,
	  SOPHIA.MATRICULA.CODIGO
 /*
-- UNION
 
-- SELECT DISTINCT
-- 	  ZMIGRA_BASE.CODCOLIGADA                                                               AS CODCOLIGADA,
--       ZMIGRA_BASE.CODCURSO                                                                  AS CODCURSO,
--       ZMIGRA_BASE.CODHABILITACAO                                                            AS CODHABILITACAO,
--       ZMIGRA_BASE.CODGRADE_PARA                                                             AS CODGRADE,
--       ZMIGRA_BASE.TURNO                                                                     AS TURNO,
--       ZMIGRA_BASE.CODFILIAL                                                                 AS CODFILIAL,
--       ZMIGRA_BASE.CODTIPOCURSO                                                              AS CODTIPOCURSO,
--       ZMIGRA_BASE.RA                                                                        AS RA,
--       TURMAS.CODIGO                                                                         AS CODTURMA,
--       ZMIGRA_BASE.CODPERLET                                                                 AS CODPERLET,
--       ZDEPARA_SDISCIPLINAS.CODIGO_PARA                                                      AS CODDISC,
--       SOPHIA.ETAPAS.NUMERO                                                                  AS CODETAPA,
--       'N'                                                                                   AS TIPOETAPA,
--       CASE
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 1 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA1 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 2 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA2 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 3 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA3 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 4 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA4 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 5 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA5 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 6 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA6 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 7 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA7 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 8 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA8 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 9 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA9 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 13 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA_ANUAL AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 14 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.REC_FINAL AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 16 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA_FINAL AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 	   END AS CONCEITO,
--       NULL                                                                                  AS NOTA,
--       NULL                                                                                  AS NUMACERTOS
--   FROM 
--       SOPHIA.TURMAS (NOLOCK)
--       JOIN ZMIGRA_BASE
--            JOIN SOPHIA.MATRICULA
-- 		        JOIN SOPHIA.ACADEMIC
-- 				  ON SOPHIA.ACADEMIC.MATRICULA = SOPHIA.MATRICULA.CODIGO
-- 	  	     ON SOPHIA.MATRICULA.CODIGO = ZMIGRA_BASE.MATRICULA
--         ON ZMIGRA_BASE.CODTURMA       = SOPHIA.TURMAS.CODIGO 
--        AND ZMIGRA_BASE.SOPHIA_PERIODO = SOPHIA.TURMAS.PERIODO
--        AND ZMIGRA_BASE.CODTURNO_DE    = SOPHIA.TURMAS.TURNO
--        AND ZMIGRA_BASE.CURSO_DE       = SOPHIA.TURMAS.CURSO
--        AND ZMIGRA_BASE.RA IS NOT NULL 
--       JOIN SOPHIA.QC 
-- 	       JOIN ZDEPARA_SDISCIPLINAS (NOLOCK) 
-- 	         ON ZDEPARA_SDISCIPLINAS.CODIGO = QC.DISCIPLINA
-- 	    ON SOPHIA.QC.TURMA = SOPHIA.TURMAS.CODIGO
--       JOIN SOPHIA.CFG_ACAD (NOLOCK) 
-- 	       JOIN SOPHIA.ETAPAS (NOLOCK)
--              ON SOPHIA.ETAPAS.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO
-- 	    ON SOPHIA.CFG_ACAD.CODIGO  = SOPHIA.TURMAS.CFG_ACAD
-- 	AND SOPHIA.ACADEMIC.DISCIPLINA = SOPHIA.QC.DISCIPLINA
--  WHERE 
--       SOPHIA.QC.TIPO_NOTA = 1
--   AND SOPHIA.TURMAS.CURSO IS NOT NULL
--   AND SOPHIA.TURMAS.SERIE IS NOT NULL
-- GROUP BY 
--       ZMIGRA_BASE.CODCOLIGADA,          
--       ZMIGRA_BASE.CODCURSO,             
--       ZMIGRA_BASE.CODHABILITACAO,       
--       ZMIGRA_BASE.CODGRADE_PARA,        
--       ZMIGRA_BASE.TURNO,                
--       ZMIGRA_BASE.CODFILIAL,            
--       ZMIGRA_BASE.CODTIPOCURSO,         
--       ZMIGRA_BASE.RA,                   
--       TURMAS.CODIGO,                   
--       ZMIGRA_BASE.CODPERLET,            
--       ZDEPARA_SDISCIPLINAS.CODIGO_PARA,
--       SOPHIA.ETAPAS.NUMERO,
-- 	  SOPHIA.CFG_ACAD.CODIGO,
-- 	  SOPHIA.ACADEMIC.MEDIA1,
-- 	  SOPHIA.ACADEMIC.MEDIA2,
-- 	  SOPHIA.ACADEMIC.MEDIA3,
-- 	  SOPHIA.ACADEMIC.MEDIA4,
-- 	  SOPHIA.ACADEMIC.MEDIA5,
-- 	  SOPHIA.ACADEMIC.MEDIA6,
-- 	  SOPHIA.ACADEMIC.MEDIA7,
-- 	  SOPHIA.ACADEMIC.MEDIA8,
-- 	  SOPHIA.ACADEMIC.MEDIA9,
-- 	  SOPHIA.ACADEMIC.MEDIA_ANUAL,
-- 	  SOPHIA.ACADEMIC.REC_FINAL,
-- 	  SOPHIA.ACADEMIC.MEDIA_FINAL
--       */
) AS DADOS
WHERE DADOS.CONCEITO IS NOT NULL 
    OR DADOS.NOTA IS NOT NULL;

SELECT * FROM ZMIGRA_SNOTAETAPA ;
