IF OBJECT_ID('ZMIGRA_SNOTAS') IS NOT NULL
   DROP TABLE ZMIGRA_SNOTAS ;

SELECT
    DADOS.*
	INTO ZMIGRA_SNOTAS
FROM (
  SELECT DISTINCT
        ZMIGRA_BASE.CODCOLIGADA                                                                                                               AS CODCOLIGADA,
        ZMIGRA_BASE.CODCURSO                                                                                                                  AS CODCURSO,
        ZMIGRA_BASE.CODHABILITACAO                                                                                                            AS CODHABILITACAO,
        ZMIGRA_BASE.CODGRADE_PARA                                                                                                             AS CODGRADE,
        ZMIGRA_BASE.TURNO                                                                                                                     AS TURNO,
        ZMIGRA_BASE.CODFILIAL                                                                                                                 AS CODFILIAL,
        ZMIGRA_BASE.CODTIPOCURSO                                                                                                              AS CODTIPOCURSO,
        ZMIGRA_BASE.RA                                                                                                                        AS RA,
        TURMAS.CODIGO                                                                                                                         AS CODTURMA,
        ZMIGRA_BASE.CODPERLET                                                                                                                 AS CODPERLET,
        ZDEPARA_SDISCIPLINAS.CODIGO_PARA                                                                                                      AS CODDISC,
        SOPHIA.ETAPAS.NUMERO                                                                                                                  AS CODETAPA,
        'N'                                                                                                                                   AS TIPOETAPA,
        CASE 
            /* CURSOS DO ESEM MAIOR IGUAL A 2021 E MENOR IGUAL A 2023 */
	        WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2021' AND ZMIGRA_BASE.CODPERLET <='2023' AND SOPHIA.AVALS.nome_resum = 'AC'  THEN 1
	        WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2021' AND ZMIGRA_BASE.CODPERLET <='2023' AND SOPHIA.AVALS.nome_resum = 'AF'  THEN 2
	        WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2021' AND ZMIGRA_BASE.CODPERLET <='2023' AND SOPHIA.AVALS.DESCRICAO = 'Avaliação Formativa'  THEN 2
	        WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2021' AND ZMIGRA_BASE.CODPERLET <='2023' AND SOPHIA.AVALS.nome_resum = 'AAF'  THEN 3
	        WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2021' AND ZMIGRA_BASE.CODPERLET <='2023' AND SOPHIA.AVALS.DESCRICAO = 'Recuperação'  THEN 4
	        
	        /* CURSOS DO ESEM MAIOR IGUAL A 2024 */
	        WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2024' AND SOPHIA.AVALS.nome_resum = 'AD'  THEN 1
	        WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2024' AND SOPHIA.AVALS.nome_resum = 'SP'  THEN 2
	        WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2024' AND SOPHIA.AVALS.nome_resum = 'SM'  THEN 3
	        WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2024' AND SOPHIA.AVALS.DESCRICAO = 'Recuperação'  THEN 4
	        
	        /* CURSOS DO ESAD */
	        WHEN ZMIGRA_BASE.CODCURSO = 'ESAD' AND ZMIGRA_BASE.CODPERLET>='2021.2'  THEN 1
         END                                                                                                                                   AS CODPROVA,
        NULL                                                                                                                                   AS CONCEITO,
        REPLACE(CAST(CASE 
	        /* CURSOS DO ESEM MAIOR IGUAL A 2021 E MENOR IGUAL A 2023 */
			WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2021' AND ZMIGRA_BASE.CODPERLET <='2023' AND SOPHIA.AVALS.nome_resum = 'AC' THEN (SELECT DISTINCT AV.NOTA FROM SOPHIA.AVALUNO AS AV WHERE AV.MATRICULA = SOPHIA.MATRICULA.CODIGO AND AV.AVALIACAO = sophia.AVALS.CODIGO)
			WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2021' AND ZMIGRA_BASE.CODPERLET <='2023' AND SOPHIA.AVALS.nome_resum = 'AF' THEN (SELECT DISTINCT AV.NOTA FROM SOPHIA.AVALUNO AS AV WHERE AV.MATRICULA = SOPHIA.MATRICULA.CODIGO AND AV.AVALIACAO = sophia.AVALS.CODIGO)
			WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2021' AND ZMIGRA_BASE.CODPERLET <='2023' AND SOPHIA.AVALS.DESCRICAO = 'Avaliação Formativa' THEN (SELECT DISTINCT AV.NOTA FROM SOPHIA.AVALUNO AS AV WHERE AV.MATRICULA = SOPHIA.MATRICULA.CODIGO AND AV.AVALIACAO = sophia.AVALS.CODIGO)
			WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2021' AND ZMIGRA_BASE.CODPERLET <='2023' AND SOPHIA.AVALS.nome_resum = 'AAF' THEN (SELECT DISTINCT AV.NOTA FROM SOPHIA.AVALUNO AS AV WHERE AV.MATRICULA = SOPHIA.MATRICULA.CODIGO AND AV.AVALIACAO = sophia.AVALS.CODIGO)
			WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2021' AND ZMIGRA_BASE.CODPERLET <='2023' AND SOPHIA.AVALS.DESCRICAO = 'Recuperação' THEN (SELECT DISTINCT AV.NOTA FROM SOPHIA.AVALUNO AS AV WHERE AV.MATRICULA = SOPHIA.MATRICULA.CODIGO AND AV.AVALIACAO = sophia.AVALS.CODIGO)
			
			/* CURSOS DO ESEM MAIOR IGUAL A 2024 */
			WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2024' AND SOPHIA.AVALS.nome_resum = 'AD' THEN (SELECT DISTINCT AV.NOTA FROM SOPHIA.AVALUNO AS AV WHERE AV.MATRICULA = SOPHIA.MATRICULA.CODIGO AND AV.AVALIACAO = sophia.AVALS.CODIGO)
			WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2024' AND SOPHIA.AVALS.nome_resum = 'SP'  THEN (SELECT DISTINCT AV.NOTA FROM SOPHIA.AVALUNO AS AV WHERE AV.MATRICULA = SOPHIA.MATRICULA.CODIGO AND AV.AVALIACAO = sophia.AVALS.CODIGO)
			WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2024' AND SOPHIA.AVALS.nome_resum = 'SM' THEN (SELECT DISTINCT AV.NOTA FROM SOPHIA.AVALUNO AS AV WHERE AV.MATRICULA = SOPHIA.MATRICULA.CODIGO AND AV.AVALIACAO = sophia.AVALS.CODIGO)
			WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2024' AND SOPHIA.AVALS.DESCRICAO = 'Recuperação' THEN (SELECT DISTINCT AV.NOTA FROM SOPHIA.AVALUNO AS AV WHERE AV.MATRICULA = SOPHIA.MATRICULA.CODIGO AND AV.AVALIACAO = sophia.AVALS.CODIGO)

			/* CURSOS DO ESAD */
			WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2024' AND SOPHIA.AVALS.nome_resum = 'AD' THEN (SELECT DISTINCT AV.NOTA FROM SOPHIA.AVALUNO AS AV WHERE AV.MATRICULA = SOPHIA.MATRICULA.CODIGO AND AV.AVALIACAO = sophia.AVALS.CODIGO)

	     END AS VARCHAR),'.',',')                                                                                                              AS NOTA,
        NULL                                                                                                                                   AS NUMACERTOS
  FROM 
      SOPHIA.TURMAS (NOLOCK)
      JOIN ZMIGRA_BASE
           JOIN SOPHIA.MATRICULA
		        JOIN SOPHIA.ACADEMIC
				  ON SOPHIA.ACADEMIC.MATRICULA = SOPHIA.MATRICULA.CODIGO
	  	     ON SOPHIA.MATRICULA.CODIGO = ZMIGRA_BASE.MATRICULA
        ON ZMIGRA_BASE.CODTURMA       = SOPHIA.TURMAS.TURMA 
       AND ZMIGRA_BASE.SOPHIA_PERIODO = SOPHIA.TURMAS.PERIODO
       AND ZMIGRA_BASE.CODTURNO_DE    = SOPHIA.TURMAS.TURNO
       AND ZMIGRA_BASE.CURSO_DE       = SOPHIA.TURMAS.CURSO
       AND ZMIGRA_BASE.RA IS NOT NULL 
      JOIN SOPHIA.QC 
	       JOIN ZDEPARA_SDISCIPLINAS (NOLOCK) 
	         ON ZDEPARA_SDISCIPLINAS.CODIGO = QC.DISCIPLINA
	    ON SOPHIA.QC.TURMA = SOPHIA.TURMAS.CODIGO
      JOIN SOPHIA.CFG_ACAD (NOLOCK) 
	       JOIN SOPHIA.ETAPAS (NOLOCK)
                JOIN SOPHIA.AVALS (NOLOCK) 
				     JOIN SOPHIA.AVALUNO (NOLOCK)
                       ON SOPHIA.AVALUNO.AVALIACAO = SOPHIA.AVALS.CODIGO
					  AND SOPHIA.AVALUNO.NOTA IS NOT NULL
	  	          ON SOPHIA.AVALS.ETAPA = SOPHIA.ETAPAS.CODIGO 
             ON SOPHIA.ETAPAS.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO
	    ON SOPHIA.CFG_ACAD.CODIGO  = SOPHIA.TURMAS.CFG_ACAD
	   AND SOPHIA.AVALS.DISCIPLINA = SOPHIA.QC.DISCIPLINA
	   AND SOPHIA.AVALS.TURMA      = SOPHIA.TURMAS.CODIGO
	   AND SOPHIA.ACADEMIC.DISCIPLINA = SOPHIA.QC.DISCIPLINA
 WHERE 
      SOPHIA.AVALS.TURMA      = SOPHIA.TURMAS.CODIGO
  AND SOPHIA.AVALS.DISCIPLINA = SOPHIA.QC.DISCIPLINA
  AND SOPHIA.QC.TIPO_NOTA     = 0
/*
-- UNION

-- SELECT DISTINCT
--       ZMIGRA_BASE.CODCOLIGADA                                                                                                               AS CODCOLIGADA,
--       ZMIGRA_BASE.CODCURSO                                                                                                                  AS CODCURSO,
--       ZMIGRA_BASE.CODHABILITACAO                                                                                                            AS CODHABILITACAO,
--       ZMIGRA_BASE.CODGRADE_PARA                                                                                                             AS CODGRADE,
--       ZMIGRA_BASE.TURNO                                                                                                                     AS TURNO,
--       ZMIGRA_BASE.CODFILIAL                                                                                                                 AS CODFILIAL,
--       ZMIGRA_BASE.CODTIPOCURSO                                                                                                              AS CODTIPOCURSO,
--       ZMIGRA_BASE.RA                                                                                                                        AS RA,
--       TURMAS.CODIGO                                                                                                                         AS CODTURMA,
--       ZMIGRA_BASE.CODPERLET                                                                                                                 AS CODPERLET,
--       ZDEPARA_SDISCIPLINAS.CODIGO_PARA                                                                                                      AS CODDISC,
--       SOPHIA.ETAPAS.NUMERO                                                                                                                  AS CODETAPA,
--       'N'                                                                                                                                   AS TIPOETAPA,
--       CASE 
--           /* CURSOS DO ESEM MAIOR IGUAL A 2021 E MENOR IGUAL A 2023 */
-- 	      WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2021' AND ZMIGRA_BASE.CODPERLET <='2023' AND SOPHIA.AVALS.nome_resum = 'AC'  THEN 1
-- 	      WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2021' AND ZMIGRA_BASE.CODPERLET <='2023' AND SOPHIA.AVALS.nome_resum = 'AF'  THEN 2
-- 	      WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2021' AND ZMIGRA_BASE.CODPERLET <='2023' AND SOPHIA.AVALS.DESCRICAO = 'Avaliação Formativa'  THEN 2
-- 	      WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2021' AND ZMIGRA_BASE.CODPERLET <='2023' AND SOPHIA.AVALS.nome_resum = 'AAF'  THEN 3
-- 	      WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2021' AND ZMIGRA_BASE.CODPERLET <='2023' AND SOPHIA.AVALS.DESCRICAO = 'Recuperação'  THEN 4
	      
-- 	      /* CURSOS DO ESEM MAIOR IGUAL A 2024 */
-- 	      WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2024' AND SOPHIA.AVALS.nome_resum = 'AD'  THEN 1
-- 	      WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2024' AND SOPHIA.AVALS.nome_resum = 'SP'  THEN 2
-- 	      WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2024' AND SOPHIA.AVALS.nome_resum = 'SM'  THEN 3
-- 	      WHEN ZMIGRA_BASE.CODCURSO = 'ESEM' AND ZMIGRA_BASE.CODPERLET>='2024' AND SOPHIA.AVALS.DESCRICAO = 'Recuperação'  THEN 4
	      
-- 	      /* CURSOS DO ESAD */
-- 	      WHEN ZMIGRA_BASE.CODCURSO = 'ESAD' AND ZMIGRA_BASE.CODPERLET>='2021.2'  THEN 1
--        END                                                                                                                                    AS CODPROVA,
--       CASE
-- 	      WHEN SOPHIA.ETAPAS.NUMERO = 1 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA1 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 2 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA2 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 3 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA3 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 4 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA4 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 5 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA5 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 6 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA6 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 7 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA7 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 8 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA8 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 		  WHEN SOPHIA.ETAPAS.NUMERO = 9 THEN (SELECT TOP 1 C.CODCONCEITO FROM ZDEPARA_CONCEITO C JOIN SOPHIA.ACADEMIC AS AC ON AC.CODIGO = C.CFG_ACAD WHERE C.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO AND AC.CODIGO = SOPHIA.CFG_ACAD.CODIGO  AND CAST(SOPHIA.ACADEMIC.MEDIA9 AS FLOAT) <= CAST(C.VALOR AS FLOAT) ORDER BY CAST(C.VALOR AS FLOAT) ASC)
-- 	   END AS CONCEITO,
--       NULL                                                                                                                                   AS NOTA,
--       NULL                                                                                                                                   AS NUMACERTOS
--   FROM 
--       SOPHIA.TURMAS (NOLOCK)
--       JOIN ZMIGRA_BASE
--            JOIN SOPHIA.MATRICULA
-- 		        JOIN SOPHIA.ACADEMIC
-- 				  ON SOPHIA.ACADEMIC.MATRICULA = SOPHIA.MATRICULA.CODIGO
-- 	  	     ON SOPHIA.MATRICULA.CODIGO = ZMIGRA_BASE.MATRICULA
--         ON ZMIGRA_BASE.CODTURMA       = SOPHIA.TURMAS.CODIGO 
--        AND ZMIGRA_BASE.SOPHIA_PERIODO = SOPHIA.TURMAS.PERIODO
--        AND ZMIGRA_BASE.CODTURNO_DE    = SOPHIA.TURMAS.TURNO
--        AND ZMIGRA_BASE.CURSO_DE       = SOPHIA.TURMAS.CURSO
--        AND ZMIGRA_BASE.RA IS NOT NULL 
--       JOIN SOPHIA.QC 
-- 	       JOIN ZDEPARA_SDISCIPLINAS (NOLOCK) 
-- 	         ON ZDEPARA_SDISCIPLINAS.CODIGO = QC.DISCIPLINA
-- 	    ON SOPHIA.QC.TURMA = SOPHIA.TURMAS.CODIGO
--       JOIN SOPHIA.CFG_ACAD (NOLOCK) 
-- 	       JOIN SOPHIA.ETAPAS (NOLOCK)
--                 JOIN SOPHIA.AVALS (NOLOCK) 
-- 				     JOIN SOPHIA.AVALUNO (NOLOCK)
--                        ON SOPHIA.AVALUNO.AVALIACAO = SOPHIA.AVALS.CODIGO
-- 					  AND SOPHIA.AVALUNO.NOTA IS NOT NULL
-- 	  	          ON SOPHIA.AVALS.ETAPA = SOPHIA.ETAPAS.CODIGO 
--              ON SOPHIA.ETAPAS.CFG_ACAD = SOPHIA.CFG_ACAD.CODIGO
-- 	    ON SOPHIA.CFG_ACAD.CODIGO  = SOPHIA.TURMAS.CFG_ACAD
-- 	   AND SOPHIA.AVALS.DISCIPLINA = SOPHIA.QC.DISCIPLINA
-- 	   AND SOPHIA.AVALS.TURMA      = SOPHIA.TURMAS.CODIGO
-- 	   AND SOPHIA.ACADEMIC.DISCIPLINA = SOPHIA.QC.DISCIPLINA
--  WHERE 
--       SOPHIA.AVALS.TURMA      = SOPHIA.TURMAS.CODIGO
--   AND SOPHIA.AVALS.DISCIPLINA = SOPHIA.QC.DISCIPLINA
--   AND SOPHIA.QC.TIPO_NOTA     = 1
--   */
) AS DADOS
WHERE 
    DADOS.CONCEITO IS NOT NULL 
    OR DADOS.NOTA IS NOT NULL
GROUP BY 
    DADOS.CODCOLIGADA,
	DADOS.CODCURSO,
	DADOS.CODHABILITACAO,
    DADOS.CODGRADE,
	DADOS.TURNO,
	DADOS.CODFILIAL,
	DADOS.CODTIPOCURSO,
    DADOS.RA,
	DADOS.CODTURMA,
	DADOS.CODPERLET,
	DADOS.CODDISC,
	DADOS.CODETAPA,
	DADOS.CODPROVA,
	DADOS.NOTA,
	DADOS.TIPOETAPA,
	DADOS.CONCEITO,
	DADOS.NUMACERTOS ; 

SELECT * FROM ZMIGRA_SNOTAS ;
