IF OBJECT_ID('ZMIGRA_SFREQUENCIA_TEMP') IS NOT NULL
    DROP TABLE ZMIGRA_SFREQUENCIA_TEMP

DECLARE @ANOLETIVO AS INT = 2026
DECLARE @MAXDATA AS DATE = (SELECT TOP 1 MAX(CAD_DATA) FROM TB_CRONOGRAMA_AULA_DATA)

SELECT DISTINCT
    ZMIGRA_BASE.CODCOLIGADA AS CODCOLIGADA,
    ZMIGRA_BASE.CODFILIAL AS CODFILIAL,
    ZMIGRA_BASE.CODTIPOCURSO AS CODTIPOCURSO,
    ZMIGRA_BASE.CODTURMA AS CODTURMA,
    ZMIGRA_SHORARIOBASE.HORARIO_INICIAL AS HORAINICIAL,
    ZMIGRA_SHORARIOBASE.HORARIO_FINAL AS HORAFINAL,
    ZMIGRA_BASE.TURNO_PARA AS NOMETURNO,
    ZMIGRA_SHORARIOBASE.SEMANA AS DIASEMANA,
    ZMIGRA_SHORARIOBASE.AULA AS AULA,
    ZMIGRA_BASE.CODPERLET AS CODPERLET,
    ZDEPARA_SDISCGRADE.CODDISC_PARA AS CODDISC,
    ZMIGRA_BASE.RA AS RA,
    ZMIGRA_SHORARIOBASE.DIA AS DATA,
    CASE WHEN REG_FALTAS.RFA_PESID IS NOT NULL THEN 'F' ELSE 'A' END AS PRESENCA,
    NULL AS JUSTIFICADA,
    NULL AS IDJUSTIFICATIVAFALTA
    INTO ZMIGRA_SFREQUENCIA_TEMP
FROM ZMIGRA_BASE
LEFT JOIN ZDEPARA_SDISCGRADE
  ON ZMIGRA_BASE.CODCOLIGADA = ZDEPARA_SDISCGRADE.CODCOLIGADA
  AND ZMIGRA_BASE.CODCURSO = ZDEPARA_SDISCGRADE.CODCURSO_PARA
  AND ZMIGRA_BASE.CODHABILITACAO = ZDEPARA_SDISCGRADE.CODHABILITACAO_PARA
  AND ZMIGRA_BASE.CODGRADE_PARA = ZDEPARA_SDISCGRADE.CODGRADE_PARA
  AND ZMIGRA_BASE.CODPERLET = ZDEPARA_SDISCGRADE.CODPERIODO_PARA
LEFT JOIN ZMIGRA_SHORARIOBASE
  ON ZMIGRA_BASE.CODCOLIGADA = ZMIGRA_SHORARIOBASE.CODCOLIGADA
  AND ZMIGRA_BASE.CODFILIAL = ZMIGRA_SHORARIOBASE.CODFILIAL
  AND ZMIGRA_BASE.CODCURSO = ZMIGRA_SHORARIOBASE.CODCURSO
  AND ZMIGRA_BASE.CODTURMA = ZMIGRA_SHORARIOBASE.CODTURMA_PARA
  AND ZMIGRA_BASE.TURNO_PARA = ZMIGRA_SHORARIOBASE.TURNO_PARA
  AND ZMIGRA_BASE.CODPERLET = ZMIGRA_SHORARIOBASE.CODPERLET_PARA
  AND ZMIGRA_BASE.CODTIPOCURSO = ZMIGRA_SHORARIOBASE.NIVELENSINO
  AND ZDEPARA_SDISCGRADE.CODDISC_PARA = ZMIGRA_SHORARIOBASE.CODDISC_PARA
LEFT JOIN (
    SELECT DISTINCT
        TB_TURMA.TUR_CURID,
        TB_TURMA.TUR_ID,
        TB_TURMA_DISCIP.TDI_DISCID,
        TB_HORARIO.HOR_HORINI,
        TB_HORARIO.HOR_HORFIN,
        TB_TURMA.TUR_TURNO,
        TB_REGISTRO_FALTAS.RFA_PESID,
        TB_CRONOGRAMA_AULA_DATA.CAD_DIASEM,
        TB_CRONOGRAMA_AULA_DATA.CAD_DATA,
        TB_TURMA.TUR_PERID,
        TB_TURMA.UNIDON
    FROM TB_TURMA
    JOIN TB_TURMA_DISCIP 
    ON TB_TURMA.TUR_ID = TB_TURMA_DISCIP.TDI_TURID
    JOIN TB_CRONOGRAMA_AULA_DATA 
    ON TB_TURMA_DISCIP.TDI_TURDISID = TB_CRONOGRAMA_AULA_DATA.CAD_TDIID
    JOIN TB_CRONOGRAMA_AULA 
    ON TB_CRONOGRAMA_AULA_DATA.CAD_ID = TB_CRONOGRAMA_AULA.CAU_CADID
    JOIN TB_REGISTRO_FALTAS 
    ON TB_CRONOGRAMA_AULA.CAU_ID = TB_REGISTRO_FALTAS.RFA_CAUID
    JOIN TB_HORARIO 
    ON TB_CRONOGRAMA_AULA.CAU_HORID = TB_HORARIO.HOR_ID
) REG_FALTAS
  ON REG_FALTAS.TUR_CURID = ZMIGRA_BASE.CURSO_DE
    AND REG_FALTAS.TUR_ID = ZMIGRA_BASE.CODTURMA_DE
    AND REG_FALTAS.TDI_DISCID = ZDEPARA_SDISCGRADE.DISCIPLINA
    AND FORMAT(REG_FALTAS.HOR_HORINI, 'HH:mm') = ZMIGRA_SHORARIOBASE.HORARIO_INICIAL
    AND FORMAT(REG_FALTAS.HOR_HORFIN, 'HH:mm') = ZMIGRA_SHORARIOBASE.HORARIO_FINAL
    AND REG_FALTAS.TUR_TURNO = LEFT(ZMIGRA_BASE.CODTURNO_DE, 1)
    AND REG_FALTAS.RFA_PESID = ZMIGRA_BASE.MATRICULA
    AND REG_FALTAS.CAD_DIASEM = ZMIGRA_SHORARIOBASE.SEMANA
    AND CAST(REG_FALTAS.CAD_DATA AS DATE) = ZMIGRA_SHORARIOBASE.DIA
    AND REG_FALTAS.TUR_PERID = ( SELECT TOP 1 CODIGO_DE FROM ZDEPARA_SPLETIVO WHERE DESCRICAO = @ANOLETIVO )
JOIN ZMIGRA_SPLANOAULA
  ON ZMIGRA_SPLANOAULA.CODCOLIGADA = ZMIGRA_SHORARIOBASE.CODCOLIGADA
  AND ZMIGRA_SPLANOAULA.CODFILIAL = ZMIGRA_SHORARIOBASE.CODFILIAL
  AND ZMIGRA_SPLANOAULA.CODTURMA = ZMIGRA_SHORARIOBASE.CODTURMA_PARA
  AND ZMIGRA_SPLANOAULA.CODTIPOCURSO = ZMIGRA_SHORARIOBASE.NIVELENSINO
  AND ZMIGRA_SPLANOAULA.NOMETURNO = ZMIGRA_SHORARIOBASE.TURNO_PARA
  AND ZMIGRA_SPLANOAULA.CODPERLET = ZMIGRA_SHORARIOBASE.CODPERLET_PARA
  AND ZMIGRA_SPLANOAULA.AULA = ZMIGRA_SHORARIOBASE.AULA
  AND ZMIGRA_SPLANOAULA.DATA = ZMIGRA_SHORARIOBASE.DIA
  AND ZMIGRA_SPLANOAULA.HORAINICIAL = ZMIGRA_SHORARIOBASE.HORARIO_INICIAL
  AND ZMIGRA_SPLANOAULA.HORAFINAL = ZMIGRA_SHORARIOBASE.HORARIO_FINAL
  AND ZDEPARA_SDISCGRADE.CODDISC_PARA = ZMIGRA_SPLANOAULA.CODDISC

IF OBJECT_ID('ZMIGRA_SFREQUENCIA') IS NOT NULL
    DROP TABLE ZMIGRA_SFREQUENCIA

SELECT DISTINCT * 
INTO ZMIGRA_SFREQUENCIA
FROM ZMIGRA_SFREQUENCIA_TEMP
WHERE DATA <= @MAXDATA 
ORDER BY CODFILIAL,
         RA,
         DATA,
         AULA, 
         DIASEMANA 

DROP TABLE ZMIGRA_SFREQUENCIA_TEMP;
GO

SELECT * FROM ZMIGRA_SFREQUENCIA;