IF OBJECT_ID('ZMIGRA_SHISTALUNOCOL') IS NOT NULL
    DROP TABLE ZMIGRA_SHISTALUNOCOL;
GO

DECLARE @CODCOLIGADA INT = 13;

SELECT DISTINCT
    @CODCOLIGADA                              AS CODCOLIGADA,
    ZDEPARA_SALUNO_RA.RA                      AS RA,
    TB_PERIODO_LETIVO.PEL_ANOREF              AS ANO,

    CASE
        WHEN (
                ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%1º%'
             OR ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%2º%'
             OR ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%3º%'
             OR ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%4º%'
             OR ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%5º%'
             )
             AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%'
            THEN 'Ensino Fundamental I - Anos Iniciais'

        WHEN (
                ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%6º%'
             OR ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%7º%'
             OR ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%8º%'
             OR ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%9º%'
             )
             AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%'
            THEN 'Ensino Fundamental II - Anos Finais'

        WHEN (
                ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%MÉDIO%'
             OR ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%MEDIO%'
             )
             THEN 'Ensino Médio'

        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%INFANTIL%' THEN 'Ensino Infantil'

        ELSE ZDEPARA_SCURSO.NOME_PARA_HIST
    END AS CURSOHIST,

    ZDEPARA_SHABILITACAO.DESCRICAO_PARA                                         AS SERIEHIST,
    ZDEPARA_SINSTITUICAO.NOME_PARA                                              AS INSTITUICAO,
    CASE
        WHEN TB_INGRESSO.ING_STATUS = 'ATIVO' AND ZDEPARA_SCURSO.NIVEL_ENSINO = 1 THEN 'Concluinte'
        WHEN TB_INGRESSO.ING_STATUS = 'ATIVO' AND ZDEPARA_SCURSO.NIVEL_ENSINO = 2 THEN 'Concluinte'
        WHEN TB_INGRESSO.ING_STATUS = 'CANCEL' AND ZDEPARA_SCURSO.NIVEL_ENSINO = 1 THEN 'Não Concluinte'
        WHEN TB_INGRESSO.ING_STATUS = 'CANCEL' AND ZDEPARA_SCURSO.NIVEL_ENSINO = 2 THEN 'Não Concluinte'
    END                                                                         AS STATUS,
    NULL                                                                        AS DIASLETIVOS,
    SUM(TB_TURMA_DISCIP.TDI_CH_TOTAL / 60)                                      AS CARGAHORARIA,
    NULL                                                                        AS OBS,
    NULL                                                                        AS MINAPROV,
    NULL                                                                        AS DIRETOR,
    CAST(ZDEPARA_SCURSO.NIVEL_ENSINO AS INT)                                    AS CODTIPOCURSO,
    TB_INGRESSO.ING_CURID AS TESTE,
    CAST(ZDEPARA_SINSTITUICAO.CODIGO_PARA AS INT)                               AS CODINSTITUICAO,
    CASE
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%1º%' THEN 'EFI'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%2º%' THEN 'EFI'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%3º%' THEN 'EFI'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%4º%' THEN 'EFI'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%5º%' THEN 'EFI'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%6º%' THEN 'EFII'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%7º%' THEN 'EFII'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%8º%' THEN 'EFII'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%9º%' THEN 'EFII'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%MÉDIO%'      THEN 'EM'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%INFANTIL%'   THEN 'EI'
        ELSE ZDEPARA_SHABILITACAO.CODIGO_PARA
    END AS CODCURSOHISTORICO,
    CASE
        WHEN ZDEPARA_SCURSO.NIVEL_ENSINO = 1 THEN ZDEPARA_SHABILITACAO.COD_SERIE_DE
        ELSE 1                                                   
    END AS CODSERIEHISTORICO,
    NULL                                                                        AS FALTAS,
    NULL                                                                        AS PERCENTFREQ,
    NULL                                                                        AS MINAPROVCONCEITO

INTO ZMIGRA_SHISTALUNOCOL

FROM TB_PESSOA

JOIN TB_INGRESSO
    ON TB_INGRESSO.ING_PESID = TB_PESSOA.PES_ID

JOIN TB_MESTRE_ALUNO
    ON TB_MESTRE_ALUNO.MAL_ID = TB_INGRESSO.ING_MALID

JOIN TB_SITUACAO_RESULTADO
  ON TB_SITUACAO_RESULTADO.SRD_ID = TB_MESTRE_ALUNO.MAL_RESID

JOIN ZDEPARA_RESULTADO_HISTORICO
  ON TB_SITUACAO_RESULTADO.SRD_DESRES = ZDEPARA_RESULTADO_HISTORICO.RESULTADO

JOIN TB_MESTRE_DISCIPLINA
    ON TB_MESTRE_DISCIPLINA.MDI_MALID = TB_MESTRE_ALUNO.MAL_ID

JOIN TB_TURMA_DISCIP
    ON TB_TURMA_DISCIP.TDI_TURDISID = TB_MESTRE_DISCIPLINA.MDI_TURDISID

JOIN TB_HISTORICO
    ON TB_HISTORICO.HIS_MDIID = TB_MESTRE_DISCIPLINA.MDI_ID

JOIN ZDEPARA_SALUNO_RA
    ON ZDEPARA_SALUNO_RA.MATRICULA = TB_PESSOA.PES_ID

JOIN TB_PERIODO_LETIVO
    ON TB_PERIODO_LETIVO.PEL_PERID = TB_INGRESSO.ING_PELID

JOIN ZDEPARA_SCURSO
    ON ZDEPARA_SCURSO.COD_CURSO_DE = TB_INGRESSO.ING_CURID

JOIN ZDEPARA_SHABILITACAO
    ON ZDEPARA_SHABILITACAO.COD_CURSO = TB_INGRESSO.ING_CURID
   AND ZDEPARA_SHABILITACAO.COD_SERIE_DE = TB_MESTRE_ALUNO.MAL_FASE

JOIN ZDEPARA_SINSTITUICAO
    ON ZDEPARA_SINSTITUICAO.CODIGO = TB_PESSOA.UNIDON

WHERE
    -- LEN(TB_TURMA_DISCIP.TDI_CH_TOTAL) > 1
    ZDEPARA_SINSTITUICAO.CODIGO_PARA NOT LIKE 'NÃO IMPORTAR'
    AND ZDEPARA_SCURSO.NOME_PARA NOT LIKE 'NÃO IMPORTAR'
    AND ZDEPARA_SHABILITACAO.CODIGO_PARA NOT LIKE 'NÃO IMPORTAR'
    AND TB_INGRESSO.ING_STATUS NOT LIKE 'TRAEXT'

GROUP BY
    ZDEPARA_SALUNO_RA.RA,
    TB_PERIODO_LETIVO.PEL_ANOREF,
    CASE
        WHEN (
                ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%1º%'
             OR ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%2º%'
             OR ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%3º%'
             OR ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%4º%'
             OR ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%5º%'
             )
             AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%'
            THEN 'Ensino Fundamental I - Anos Iniciais'

        WHEN (
                ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%6º%'
             OR ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%7º%'
             OR ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%8º%'
             OR ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%9º%'
             )
             AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%'
            THEN 'Ensino Fundamental II - Anos Finais'

        WHEN (
                ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%MÉDIO%'
             OR ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%MEDIO%'
             )
            THEN 'Ensino Médio'

        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%INFANTIL%'
            THEN 'Ensino Infantil'
        
        ELSE ZDEPARA_SCURSO.NOME_PARA_HIST
    END,
    ZDEPARA_SHABILITACAO.DESCRICAO_PARA,
    ZDEPARA_SINSTITUICAO.NOME_PARA,
    TB_INGRESSO.ING_STATUS,
    ZDEPARA_SCURSO.NIVEL_ENSINO,
    ZDEPARA_SINSTITUICAO.CODIGO_PARA,
    ZDEPARA_SCURSO.CURSO_PARA_HIST,
    TB_INGRESSO.ING_CURID,
    ZDEPARA_SHABILITACAO.CODIGO_PARA,
    ZDEPARA_SHABILITACAO.COD_SERIE_DE,
    ZDEPARA_SCURSO.NOME_PARA_HIST,
    TB_INGRESSO.ING_CURID,
    CASE
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%1º%' THEN 'EFI'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%2º%' THEN 'EFI'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%3º%' THEN 'EFI'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%4º%' THEN 'EFI'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%5º%' THEN 'EFI'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%6º%' THEN 'EFII'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%7º%' THEN 'EFII'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%8º%' THEN 'EFII'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%FUNDAMENTAL%' AND ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%9º%' THEN 'EFII'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%MÉDIO%'      THEN 'EM'
        WHEN ZDEPARA_SHABILITACAO.DESCRICAO LIKE '%INFANTIL%'   THEN 'EI'
        ELSE ZDEPARA_SHABILITACAO.CODIGO_PARA
    END;

SELECT * FROM ZMIGRA_SHISTALUNOCOL ORDER BY RA, ANO;