IF OBJECT_ID('ZINSTITUICAO') IS NOT NULL
   DROP TABLE ZINSTITUICAO;

SELECT 
      RIGHT('000000' + CAST(140000 + ROW_NUMBER() OVER (ORDER BY CODIGO) AS VARCHAR), 6) AS CODINST,
      ZDEPARA_SINSTITUICAO.NOMEFANTASIA AS NOME,
      ZDEPARA_SINSTITUICAO.NOMEFANTASIA,
      NULL AS CIDADE,
      NULL AS UF,
      NULL AS DIRETOR,
      NULL AS CONVENIADA,
      NULL AS TIPOINST,
      NULL AS CODEMEC,
      NULL AS CODINSTMANTENEDORA
      INTO ZINSTITUICAO
  FROM 
      ZDEPARA_SINSTITUICAO  
--  WHERE
--       ZDEPARA_SINSTITUICAO.CODIGO_PARA <> 'NÃO IMPORTAR';

SELECT * FROM ZINSTITUICAO ORDER BY 1;

-- SP_GENERATEINSERT ZINSTITUICAO, SINSTITUICAO   

-- select * from ZDEPARA_SINSTITUICAO