IF OBJECT_ID('ZMIGRA_SHISTDISCCOL') IS NOT NULL
	DROP TABLE ZMIGRA_SHISTDISCCOL
;

DECLARE @CODCOLIGADA AS INTEGER = 13
DECLARE @DIASLETIVO AS INTEGER = 200

SELECT DISTINCT
	@CODCOLIGADA														AS CODCOLIGADA,
	ZDEPARA_SALUNO_RA.RA												AS RA,
	TB_PERIODO_LETIVO.PEL_ANOREF										AS ANO,
	ZDEPARA_SCURSO.CURSO_PARA_HIST										AS CURSOHIST,
	CAST(TB_RESULTADO_FASE.REF_FASE AS VARCHAR)							AS SERIEHIST,
	ZDEPARA_SDISCIPLINAS.NOME										    AS DISCIPLINA,
	CASE
		WHEN TB_SITUACAO_RESULTADO.SRD_DESRES = 'Aprovado' 													   	THEN 'Aprovado'
		WHEN TB_SITUACAO_RESULTADO.SRD_DESRES = 'Aprovado pelo Conselho' 									   	THEN 'Aprovado em conselho'
		WHEN TB_SITUACAO_RESULTADO.SRD_DESRES = 'Cursando' 													   	THEN 'Cursando'
		WHEN TB_SITUACAO_RESULTADO.SRD_DESRES = 'Não concluiu' AND ZDEPARA_SCURSO.NIVEL_ENSINO = 1 			   	THEN 'Não concluiu'
		WHEN TB_SITUACAO_RESULTADO.SRD_DESRES = 'Não concluiu' AND ZDEPARA_SCURSO.NIVEL_ENSINO = 2			   	THEN 'Não concluinte'
		WHEN TB_SITUACAO_RESULTADO.SRD_DESRES = 'Não concluiu' AND ZDEPARA_SCURSO.NIVEL_ENSINO = 2			   	THEN 'Não concluinte'
		WHEN TB_SITUACAO_RESULTADO.SRD_DESRES = 'Reprovado'													   	THEN 'Reprovado'
		WHEN TB_SITUACAO_RESULTADO.SRD_DESRES = 'Reprovado por Frequencia' AND ZDEPARA_SCURSO.NIVEL_ENSINO = 1 	THEN 'Reprovado por Frequência'
		WHEN TB_SITUACAO_RESULTADO.SRD_DESRES = 'Reprovado por Frequencia' AND ZDEPARA_SCURSO.NIVEL_ENSINO = 2 	THEN 'Reprovado por Frequencia'
		WHEN TB_SITUACAO_RESULTADO.SRD_DESRES = 'Transferido' 													THEN 'Transferência Externa'
	END AS STATUS,
	@DIASLETIVO															AS DIASLETIVOS,
	CAST(CH.CHTOTAL AS INT)										        AS CARGAHORARIA,
	NULL																AS OBS,
	NULL																AS MINAPROV,
	NULL																AS DIRETOR,
	CAST(ZDEPARA_SCURSO.NIVEL_ENSINO AS INT)							AS CODTIPOCURSO,
	NULL																AS CODINSTITUICAO,
	ZDEPARA_SCURSO.CURSO_PARA_HIST										AS CODCURSOHISTORICO,
	CAST(TB_RESULTADO_FASE.REF_FASE AS INT)								AS CODSERIEHISTORICO,
	NULL																AS FALTAS,
	NULL																AS PERCENTFREQ,
	NULL																AS MINAPROVCONCEITO
	INTO ZMIGRA_SHISTDISCCOL
FROM ZDEPARA_SCURSO
JOIN TB_INGRESSO
  ON ZDEPARA_SCURSO.COD_CURSO_DE = TB_INGRESSO.ING_CURID
JOIN TB_RESULTADO_FASE 
  ON TB_INGRESSO.ING_ID = TB_RESULTADO_FASE.REF_INGID
JOIN TB_SITUACAO_RESULTADO 
  ON TB_RESULTADO_FASE.REF_RESID = TB_SITUACAO_RESULTADO.SRD_ID
JOIN ZDEPARA_SINSTITUICAO
  ON ZDEPARA_SINSTITUICAO.CODIGO = TB_RESULTADO_FASE.UNIDON
JOIN ZDEPARA_SALUNO_RA
  ON ZDEPARA_SALUNO_RA.MATRICULA = TB_INGRESSO.ING_PESID
JOIN TB_PERIODO_LETIVO
  ON TB_PERIODO_LETIVO.PEL_PERID = TB_INGRESSO.ING_PELID
JOIN (
	SELECT *
	FROM (
		SELECT
			DENSE_RANK() 
			OVER(PARTITION BY TUR_CURID, TUR_PERID, UNIDON, TDI_FASDIS ORDER BY CHTOTAL DESC) AS 'RANK',
			X.*
		FROM (
			SELECT DISTINCT
				TB_TURMA.TUR_CURID,
				TB_TURMA.TUR_PERID,
				TB_TURMA.UNIDON,
				TB_TURMA_DISCIP.TDI_FASDIS,
                TB_TURMA_DISCIP.TDI_DISCID,
				SUM(TB_TURMA_DISCIP.TDI_CH_TOTAL) AS CHTOTAL
			FROM TB_TURMA
			JOIN TB_TURMA_DISCIP
			ON TB_TURMA_DISCIP.TDI_TURID = TB_TURMA.TUR_ID
			GROUP BY
				TB_TURMA.TUR_ID,
				TB_TURMA.TUR_CURID,
				TB_TURMA.TUR_PERID,
				TB_TURMA.UNIDON,
				TB_TURMA_DISCIP.TDI_FASDIS,
                TB_TURMA_DISCIP.TDI_DISCID
			HAVING SUM(TB_TURMA_DISCIP.TDI_CH_TOTAL) > 0
		) X
	) Y
	WHERE RANK = 1
) CH
  ON CH.TUR_CURID = ZDEPARA_SCURSO.COD_CURSO_DE
  AND CH.TUR_PERID = TB_PERIODO_LETIVO.PEL_PERID
  AND CH.TDI_FASDIS = TB_RESULTADO_FASE.REF_FASE
JOIN ZDEPARA_SDISCIPLINAS
  ON ZDEPARA_SDISCIPLINAS.CODIGO = CH.TDI_DISCID
WHERE ZDEPARA_SCURSO.CURSO_PARA_HIST NOT LIKE 'NÃO IMPORTAR'
ORDER BY 2, 3, 8 DESC

SELECT * FROM ZMIGRA_SHISTDISCCOL ;