----------------------------------------------------------------------------------------------------      
-- Script:				  032 - SCRIPT UPDATE DE CAMPOS COMPL MULTI
-- Última Alteração:		  30/06/2025
-- Versão:				  1  
-- Origem:				  Sistema Sophia
-- Autor Alteração:			  Pedro Andresen
----------------------------------------------------------------------------------------------------       

/* GERA DADOS PARA UPDATE EM BASE RM MULTIDADOS / SIM/NÃO E ETC E TAMBEM PRECISA SER GERADO POR CAMPO */



USE SESC_SOPHIA_PLE
GO

SELECT DISTINCT 
      SOPHIA.FISICA.NOME,
      SOPHIA.CONFIG_TAB_LIVRE.NOME,
      SOPHIA.TAB_DADOS.DESCRICAO,
      ZDADOS_COMPL.CAMPO_PARA,
      'UPDATE SALUNOCOMPL  
       SET  
          SALUNOCOMPL.SGPALUNOPCG =''' + CASE WHEN SOPHIA.CONFIG_TAB_LIVRE.NOME = 'Dep. Comerciário' AND SOPHIA.TAB_DADOS.DESCRICAO = 'NÃO' THEN 'N'
                                              WHEN SOPHIA.CONFIG_TAB_LIVRE.NOME = 'Dep. Comerciário' AND SOPHIA.TAB_DADOS.DESCRICAO = 'SIM' THEN 'S'
                                              ELSE 'NULL' END +'''
          WHERE SALUNOCOMPL.RA = ''' + ZDEPARA_SALUNO_RA.RA + ''' 
            AND PFHSTSEC.CODCOLIGADA = ' + '1' + ''  AS UPD_SGPALUNOPCG
  FROM  
      SOPHIA.FISICA
      JOIN ZDEPARA_SALUNO_RA
        ON ZDEPARA_SALUNO_RA.FISICA = SOPHIA.FISICA.CODIGO
      LEFT JOIN SOPHIA.TAB_MULTI_DADOS
           LEFT JOIN SOPHIA.TAB_DADOS
                LEFT JOIN SOPHIA.CONFIG_TAB_LIVRE
                     JOIN ZDADOS_COMPL
                       ON ZDADOS_COMPL.COD_GRUPO_DE = SOPHIA.CONFIG_TAB_LIVRE.IDFK_CONFIG_TAB_LIVRE_GRUPO
                      AND ZDADOS_COMPL.CODIGO_DE    = SOPHIA.CONFIG_TAB_LIVRE.CODIGO
                     LEFT JOIN SOPHIA.CONFIG_TAB_LIVRE_GRUPO
                       ON SOPHIA.CONFIG_TAB_LIVRE_GRUPO.ID_CONFIG_TAB_LIVRE_GRUPO = SOPHIA.CONFIG_TAB_LIVRE.IDFK_CONFIG_TAB_LIVRE_GRUPO
                  ON SOPHIA.CONFIG_TAB_LIVRE.CODIGO = SOPHIA.TAB_DADOS.COD_TAB_LIVRE
             ON SOPHIA.TAB_DADOS.COD_TAB_DADOS = SOPHIA.TAB_MULTI_DADOS.COD_DADOS
        ON SOPHIA.TAB_MULTI_DADOS.FISICA = SOPHIA.FISICA.CODIGO
 WHERE
      ZDEPARA_SALUNO_RA.MATRICULA IN ('2023.0185','2025.0035')--,'2023.0185')
  AND ZDADOS_COMPL.CAMPO_PARA IS NOT NULL
  AND SOPHIA.CONFIG_TAB_LIVRE.NOME = 'Dep. Comerciário'


  /* PARA O CAMPO = UPD_BENEFBOLSAF */ 

USE SESC_SOPHIA_PLE
GO


  SELECT DISTINCT 
      SOPHIA.FISICA.NOME,
      SOPHIA.CONFIG_TAB_LIVRE.NOME,
      SOPHIA.TAB_DADOS.DESCRICAO,
      ZDADOS_COMPL.CAMPO_PARA,
      'UPDATE SALUNOCOMPL  
       SET  
          SALUNOCOMPL.BENEFBOLSAF =''' + CASE WHEN SOPHIA.CONFIG_TAB_LIVRE.NOME = 'Possui Bolsa Família' AND  SOPHIA.TAB_DADOS.DESCRICAO = 'Não possui Bolsa Família' THEN 'N'
                                              WHEN SOPHIA.CONFIG_TAB_LIVRE.NOME = 'Possui Bolsa Família' AND  SOPHIA.TAB_DADOS.DESCRICAO <> 'Não possui Bolsa Família' THEN 'S'
                                              ELSE 'NULL' END +'''
          WHERE SALUNOCOMPL.RA = ''' + ZDEPARA_SALUNO_RA.RA + ''' 
            AND PFHSTSEC.CODCOLIGADA = ' + '1' + ''  AS UPD_BENEFBOLSAF
  FROM  
      SOPHIA.FISICA
      JOIN ZDEPARA_SALUNO_RA
        ON ZDEPARA_SALUNO_RA.FISICA = SOPHIA.FISICA.CODIGO
      LEFT JOIN SOPHIA.TAB_MULTI_DADOS
           LEFT JOIN SOPHIA.TAB_DADOS
                LEFT JOIN SOPHIA.CONFIG_TAB_LIVRE
                     JOIN ZDADOS_COMPL
                       ON ZDADOS_COMPL.COD_GRUPO_DE = SOPHIA.CONFIG_TAB_LIVRE.IDFK_CONFIG_TAB_LIVRE_GRUPO
                      AND ZDADOS_COMPL.CODIGO_DE    = SOPHIA.CONFIG_TAB_LIVRE.CODIGO
                     LEFT JOIN SOPHIA.CONFIG_TAB_LIVRE_GRUPO
                       ON SOPHIA.CONFIG_TAB_LIVRE_GRUPO.ID_CONFIG_TAB_LIVRE_GRUPO = SOPHIA.CONFIG_TAB_LIVRE.IDFK_CONFIG_TAB_LIVRE_GRUPO
                  ON SOPHIA.CONFIG_TAB_LIVRE.CODIGO = SOPHIA.TAB_DADOS.COD_TAB_LIVRE
             ON SOPHIA.TAB_DADOS.COD_TAB_DADOS = SOPHIA.TAB_MULTI_DADOS.COD_DADOS
        ON SOPHIA.TAB_MULTI_DADOS.FISICA = SOPHIA.FISICA.CODIGO
 WHERE
      ZDEPARA_SALUNO_RA.MATRICULA IN ('2023.0185','2025.0035')--,'2023.0185')
  AND ZDADOS_COMPL.CAMPO_PARA IS NOT NULL
  AND SOPHIA.CONFIG_TAB_LIVRE.NOME = 'Possui Bolsa Família'


