----------------------------------------------------------------------------------------------------      
-- Script:				  	  033 - SCRIPT UPDATE DE CAMPOS COMPL TEXTO
-- Última Alteração:		  30/06/2025
-- Versão:					  1  
-- Origem:					  Sistema Sophia
-- Autor Alteração:			  Pedro Andresen
----------------------------------------------------------------------------------------------------       

/* IDEIA É VERIFICAR APENAS O QUE DEVE SER TRAZIDO EM CADA GRUPO. E LIMITAR ISSO NO SELECT. DEVE SER FEITO UM UPDATE PARA CADA GRUPO UMA VEZ QUE OS CAMPOS VAO MUDAR POR GRUPO. AO SABER QUAL CAMPO NÃO PODE SER NULO PARA CADA GRUPO, COLOCAR ISSO NO WHERE*/ 

/* GRUPO 2,4 E 5 */


USE SESC_SOPHIA_PLE
GO

/* CRIAR UPDATE GRUPO 2 */ 

SELECT DISTINCT
      SOPHIA.FISICA.CODIGO,
      SOPHIA.FISICA.NOME,
      SOPHIA.CONFIG_TAB_LIVRE_GRUPO.DESCRICAO AS GRUPO,
      SOPHIA.TAB_DESCRICAO_DADOS.DESCRICAO1 AS NROTABLET,
      CAST(SOPHIA.TAB_DESCRICAO_DADOS.DATA1 AS DATE) AS DATAENTREGATABLET,
      'UPDATE SALUNOCOMPL  
       SET  
          SALUNOCOMPL.NUMTABLET =''' + ISNULL(CAST(CAST(SOPHIA.TAB_DESCRICAO_DADOS.DATA1 AS DATE)AS VARCHAR),0.00)+'''  
          WHERE SALUNOCOMPL.RA = ''' + ZDEPARA_SALUNO_RA.RA + ''' 
            AND PFHSTSEC.CODCOLIGADA = ' + '1' + ''  AS UPD 
FROM  
      SOPHIA.FISICA
      JOIN ZDEPARA_SALUNO_RA
        ON ZDEPARA_SALUNO_RA.FISICA = SOPHIA.FISICA.CODIGO
      JOIN SOPHIA.TAB_DESCRICAO_DADOS
           LEFT JOIN SOPHIA.CONFIG_TAB_LIVRE_GRUPO
                     LEFT JOIN SOPHIA.CONFIG_TAB_LIVRE
                               JOIN ZDADOS_COMPL
                                 ON ZDADOS_COMPL.COD_GRUPO_DE = SOPHIA.CONFIG_TAB_LIVRE.IDFK_CONFIG_TAB_LIVRE_GRUPO
                                AND ZDADOS_COMPL.CODIGO_DE    = SOPHIA.CONFIG_TAB_LIVRE.CODIGO
                       ON SOPHIA.CONFIG_TAB_LIVRE.IDFK_CONFIG_TAB_LIVRE_GRUPO = SOPHIA.CONFIG_TAB_LIVRE_GRUPO.ID_CONFIG_TAB_LIVRE_GRUPO
             ON SOPHIA.CONFIG_TAB_LIVRE_GRUPO.ID_CONFIG_TAB_LIVRE_GRUPO = SOPHIA.TAB_DESCRICAO_DADOS.IDFK_CONFIG_TAB_LIVRE_GRUPO
        ON SOPHIA.TAB_DESCRICAO_DADOS.FISICA = SOPHIA.FISICA.CODIGO
      
WHERE
      ZDEPARA_SALUNO_RA.MATRICULA IN ('2023.0185','2025.0035')--,'2023.0185')
  AND SOPHIA.CONFIG_TAB_LIVRE.CLIENTE = 1
  AND SOPHIA.CONFIG_TAB_LIVRE.HABILITADO = 1 
  AND SOPHIA.CONFIG_TAB_LIVRE.IDFK_CONFIG_TAB_LIVRE_GRUPO = 2
  AND NOT EXISTS (SELECT 1 FROM SOPHIA.TAB_MULTI_DADOS AS Z WHERE Z.TABELA = SOPHIA.CONFIG_TAB_LIVRE.CODIGO)
  AND ZDADOS_COMPL.CAMPO_PARA IS NOT NULL
  AND (
      SOPHIA.TAB_DESCRICAO_DADOS.DESCRICAO1 IS NOT NULL

   )

/* CRIA UPDATE GRUPO 4 */ 

SELECT DISTINCT
      SOPHIA.FISICA.CODIGO,
      SOPHIA.FISICA.NOME,
      SOPHIA.CONFIG_TAB_LIVRE_GRUPO.DESCRICAO AS GRUPO,
      SOPHIA.TAB_DESCRICAO_DADOS.DESCRICAO1 AS NROTABLET,
      CAST(SOPHIA.TAB_DESCRICAO_DADOS.DATA1 AS DATE) AS DATAENTREGATABLET,
      'UPDATE SALUNOCOMPL  
       SET  
          SALUNOCOMPL.NUMTABLET =''' + ISNULL(CAST(CAST(SOPHIA.TAB_DESCRICAO_DADOS.DATA1 AS DATE)AS VARCHAR),0.00)+'''  
          WHERE SALUNOCOMPL.RA = ''' + ZDEPARA_SALUNO_RA.RA + ''' 
            AND PFHSTSEC.CODCOLIGADA = ' + '1' + ''  AS UPD 
FROM  
      SOPHIA.FISICA
      JOIN ZDEPARA_SALUNO_RA
        ON ZDEPARA_SALUNO_RA.FISICA = SOPHIA.FISICA.CODIGO
      JOIN SOPHIA.TAB_DESCRICAO_DADOS
           LEFT JOIN SOPHIA.CONFIG_TAB_LIVRE_GRUPO
                     LEFT JOIN SOPHIA.CONFIG_TAB_LIVRE
                               JOIN ZDADOS_COMPL
                                 ON ZDADOS_COMPL.COD_GRUPO_DE = SOPHIA.CONFIG_TAB_LIVRE.IDFK_CONFIG_TAB_LIVRE_GRUPO
                                AND ZDADOS_COMPL.CODIGO_DE    = SOPHIA.CONFIG_TAB_LIVRE.CODIGO
                       ON SOPHIA.CONFIG_TAB_LIVRE.IDFK_CONFIG_TAB_LIVRE_GRUPO = SOPHIA.CONFIG_TAB_LIVRE_GRUPO.ID_CONFIG_TAB_LIVRE_GRUPO
             ON SOPHIA.CONFIG_TAB_LIVRE_GRUPO.ID_CONFIG_TAB_LIVRE_GRUPO = SOPHIA.TAB_DESCRICAO_DADOS.IDFK_CONFIG_TAB_LIVRE_GRUPO
        ON SOPHIA.TAB_DESCRICAO_DADOS.FISICA = SOPHIA.FISICA.CODIGO
      
WHERE
      ZDEPARA_SALUNO_RA.MATRICULA IN ('2023.0185','2025.0035')--,'2023.0185')
  AND SOPHIA.CONFIG_TAB_LIVRE.CLIENTE = 1
  AND SOPHIA.CONFIG_TAB_LIVRE.HABILITADO = 1 
  AND SOPHIA.CONFIG_TAB_LIVRE.IDFK_CONFIG_TAB_LIVRE_GRUPO = 4 /* AQUI DETERMINAMOS O GRUPO */ 
  AND NOT EXISTS (SELECT 1 FROM SOPHIA.TAB_MULTI_DADOS AS Z WHERE Z.TABELA = SOPHIA.CONFIG_TAB_LIVRE.CODIGO)
  AND ZDADOS_COMPL.CAMPO_PARA IS NOT NULL
  AND (
      SOPHIA.TAB_DESCRICAO_DADOS.DESCRICAO1 IS NOT NULL

   )


/* CRIA UPDATE GRUPO 5 */ 

SELECT DISTINCT
      SOPHIA.FISICA.CODIGO,
      SOPHIA.FISICA.NOME,
      SOPHIA.CONFIG_TAB_LIVRE_GRUPO.DESCRICAO AS GRUPO,
      SOPHIA.TAB_DESCRICAO_DADOS.DESCRICAO1,
      CAST(SOPHIA.TAB_DESCRICAO_DADOS.DATA1 AS DATE) AS NROTABLET,
      'UPDATE SALUNOCOMPL  
       SET  
          SALUNOCOMPL.NUMTABLET =''' + ISNULL(CAST(CAST(SOPHIA.TAB_DESCRICAO_DADOS.DATA1 AS DATE)AS VARCHAR),0.00)+'''  
          WHERE SALUNOCOMPL.RA = ''' + ZDEPARA_SALUNO_RA.RA + ''' 
            AND PFHSTSEC.CODCOLIGADA = ' + '1' + ''  AS UPD 
FROM  
      SOPHIA.FISICA
      JOIN ZDEPARA_SALUNO_RA
        ON ZDEPARA_SALUNO_RA.FISICA = SOPHIA.FISICA.CODIGO
      JOIN SOPHIA.TAB_DESCRICAO_DADOS
           LEFT JOIN SOPHIA.CONFIG_TAB_LIVRE_GRUPO
                     LEFT JOIN SOPHIA.CONFIG_TAB_LIVRE
                               JOIN ZDADOS_COMPL
                                 ON ZDADOS_COMPL.COD_GRUPO_DE = SOPHIA.CONFIG_TAB_LIVRE.IDFK_CONFIG_TAB_LIVRE_GRUPO
                                AND ZDADOS_COMPL.CODIGO_DE    = SOPHIA.CONFIG_TAB_LIVRE.CODIGO
                       ON SOPHIA.CONFIG_TAB_LIVRE.IDFK_CONFIG_TAB_LIVRE_GRUPO = SOPHIA.CONFIG_TAB_LIVRE_GRUPO.ID_CONFIG_TAB_LIVRE_GRUPO
             ON SOPHIA.CONFIG_TAB_LIVRE_GRUPO.ID_CONFIG_TAB_LIVRE_GRUPO = SOPHIA.TAB_DESCRICAO_DADOS.IDFK_CONFIG_TAB_LIVRE_GRUPO
        ON SOPHIA.TAB_DESCRICAO_DADOS.FISICA = SOPHIA.FISICA.CODIGO
      
WHERE
      ZDEPARA_SALUNO_RA.MATRICULA IN ('2023.0185','2025.0035')--,'2023.0185')
  AND SOPHIA.CONFIG_TAB_LIVRE.CLIENTE = 1
  AND SOPHIA.CONFIG_TAB_LIVRE.HABILITADO = 1 
  AND SOPHIA.CONFIG_TAB_LIVRE.IDFK_CONFIG_TAB_LIVRE_GRUPO = 5
  AND NOT EXISTS (SELECT 1 FROM SOPHIA.TAB_MULTI_DADOS AS Z WHERE Z.TABELA = SOPHIA.CONFIG_TAB_LIVRE.CODIGO)
  AND ZDADOS_COMPL.CAMPO_PARA IS NOT NULL
  AND (
      SOPHIA.TAB_DESCRICAO_DADOS.DESCRICAO1 IS NOT NULL

   )   


SELECT * FROM SOPHIA.CONFIG_TAB_LIVRE_GRUPO