SELECT  
      14 AS CODCOLIGADA, 
      RM_FCFO.CODCFO,
      RM_FCFO.CGCCFO,
      RA.RA, 
       'UPDATE SALUNO SET SALUNO.CODCFO = '''+ISNULL(REPLACE(RM_FCFO.CODCFO,',','.'),'NULL')+''', SALUNO.CODCOLCFO = '+'14'+' WHERE SALUNO.RA = '''+RA.RA+''' AND SALUNO.CODCOLIGADA = '+'14'+';' AS UPD 
  FROM 
      RM_FCFO
      JOIN ZDADOS_FCFO
           JOIN ZDEPARA_SALUNO_RA AS RA
             ON RA.MATRICULA = ZDADOS_FCFO.MATRICULA
        ON REPLACE(REPLACE(RM_FCFO.CGCCFO,'.',''),'-','') = ZDADOS_FCFO.CGCCFO
 --WHERE ZDADOS_FCFO.PLT_COD = (SELECT MAX(Z.PLT_COD) FROM ZDADOS_FCFO AS Z WHERE Z.MATRICULA = ZDADOS_FCFO.MATRICULA)