--### AJUSTE MIGRAÇÃO SESC SC! AJUSTE PESSOAS

-- COPIAR DADOS DAS PESSOAS, CODIGO, CPF E NOME PARA UMA TABELA CHAMADA ZDADOSPESSOAS E VERIFICAR AS PESSOAS COM ERROS. PARA ALGUMAS LINHAS NECESSÁRIO 

--SELECT * FROM ZPESSOA WHERE NOT EXISTS (SELECT 1 FROM ZDADOSPESSOAS AS Z WHERE Z.CPF = ZPESSOA.CPF)
    
--UPDATE ZPESSOA SET UFCARTIDENT = NULL, EMAIL = NULL, ORGEMISSORIDENT = null, CARTIDENTIDADE = NULL, DTEMISSPASSAPORTE = NULL WHERE NOT EXISTS (SELECT 1 FROM ZDADOSPESSOAS AS Z WHERE Z.CPF = ZPESSOA.CPF);