/* RA */
UPDATE GAUTOINC SET VALAUTOINC=(SELECT MAX(RA)+1 FROM SALUNO) WHERE CODSISTEMA = 'S' AND CODAUTOINC = 'RA' AND NOMETABELA = 'SALUNO' AND CODCOLIGADA = 0

/* PPESSOA */ 
UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(CODIGO)+1 FROM PPESSOA) WHERE CODAUTOINC = 'CODPESSOA' AND NOMETABELA = 'PPESSOA' AND CODCOLIGADA = 0