-- Consulta complementar: retorna somente sindicatos ainda nao existentes no DE-PARA anterior.
;WITH NOVO_DEPARA AS
(
    SELECT DISTINCT
           EMP.CODIGO AS EMPRESA_DE,
           SIN.CODIGO AS CODIGO_DE,
           SIN.NOME AS NOME_DE,
           SIN.CNPJ AS CNPJ,
           COLIGADA.CODCOLIGADA AS COLIGADA_PARA,
           CAST('' AS VARCHAR(10)) AS CODIGO_PARA
      FROM SIN
      JOIN SEP
        ON SEP.SIN_CODIGO = SIN.CODIGO
      JOIN EMP
        ON EMP.CODIGO = SEP.EMP_CODIGO
      JOIN ZDEPARA_COLIGADAS AS COLIGADA
        ON SEP.EMP_CODIGO = COLIGADA.EMPRESA_DE
)
SELECT NOVO_DEPARA.*
  FROM NOVO_DEPARA
 WHERE NOT EXISTS
       (
           SELECT 1
             FROM ZDEPARA_SINDICATOS AS ANTERIOR
            WHERE ANTERIOR.CODIGO_DE = NOVO_DEPARA.CODIGO_DE
       )
 ORDER BY NOVO_DEPARA.CODIGO_DE;
