-- Consulta complementar: retorna somente secoes ainda nao existentes no DE-PARA anterior.
;WITH NOVO_DEPARA AS
(
    SELECT DISTINCT
           SEP.EMP_CODIGO AS EMPRESA_DE,
           SEP.EST_CODIGO AS FILIAL_DE,
           SEP.LOT_CODIGO AS CODIGO_DE,
           LOT.NOME AS NOME_DE,
           COLIGADA.CODCOLIGADA AS COLIGADA_PARA,
           CAST('' AS VARCHAR(30)) AS FILIAL_PARA,
           CAST('' AS VARCHAR(30)) AS CODIGO_PARA
      FROM SEP
      JOIN ZDEPARA_COLIGADAS AS COLIGADA
        ON SEP.EMP_CODIGO = COLIGADA.EMPRESA_DE
      JOIN EST
        ON EST.EMP_CODIGO = SEP.EMP_CODIGO
       AND EST.CODIGO = SEP.EST_CODIGO
      JOIN LOT
        ON LOT.EMP_CODIGO = SEP.EMP_CODIGO
       AND LOT.CODIGO = SEP.LOT_CODIGO
)
SELECT NOVO_DEPARA.*
  FROM NOVO_DEPARA
 WHERE NOT EXISTS
       (
           SELECT 1
             FROM ZDEPARA_SECOES AS ANTERIOR
            WHERE ANTERIOR.EMPRESA_DE = NOVO_DEPARA.EMPRESA_DE
              AND ANTERIOR.FILIAL_DE = NOVO_DEPARA.FILIAL_DE
              AND ANTERIOR.CODIGO_DE = NOVO_DEPARA.CODIGO_DE
       )
 ORDER BY NOVO_DEPARA.COLIGADA_PARA;
