-- Consulta complementar: retorna somente bancos/agencias ainda nao existentes no DE-PARA anterior.
-- O nome ZDEPARA_BANCO (singular) segue a tabela criada pelo script-base 006.
;WITH NOVO_DEPARA AS
(
    SELECT DISTINCT
           EPG.EMP_CODIGO AS EMPRESA_DE,
           EPG.AGE_BAN_CODIGO AS CODIGO_BANCO_DE,
           EPG.AGE_CODIGO AS CODIGO_AGENCIA_DE,
           BAN.NUMERO AS NUMBANCO_DE,
           BAN.NOME AS NOME_BANCO_DE,
           AGE.NUMERO AS NUMAGENCIA_DE,
           AGE.NOME AS NOME_AGENCIA_DE,
           CASE
               WHEN BAN.NUMERO = '122' THEN '104'
               ELSE CAST(BAN.NUMERO AS VARCHAR(5))
           END AS CODIGO_BANCO_PARA,
           RIGHT('00000' + CAST(REPLACE(LEFT(AGE.NUMERO, 5), '-', '') AS VARCHAR(5)), 5) AS CODIGO_AGENCIA_PARA,
           CASE
               WHEN BAN.NOME LIKE '%CAIXA%' OR BAN.NOME LIKE '%CEF%' THEN ''
               ELSE RIGHT('0' + CAST(REPLACE(RIGHT(AGE.NUMERO, 1), '-', '') AS VARCHAR(1)), 1)
           END AS DIGITO_AGENCIA_PARA
      FROM EPG
      JOIN ZDEPARA_COLIGADAS AS COLIGADA
        ON EPG.EMP_CODIGO = COLIGADA.CODCOLIGADA
      JOIN BAN
        ON BAN.CODIGO = EPG.AGE_BAN_CODIGO
      JOIN AGE
        ON AGE.BAN_CODIGO = EPG.AGE_BAN_CODIGO
       AND AGE.CODIGO = EPG.AGE_CODIGO
)
SELECT NOVO_DEPARA.*
  FROM NOVO_DEPARA
 WHERE NOT EXISTS
       (
           SELECT 1
             FROM ZDEPARA_BANCO AS ANTERIOR
            WHERE ANTERIOR.EMPRESA_DE = NOVO_DEPARA.EMPRESA_DE
              AND ANTERIOR.CODIGO_BANCO_DE = NOVO_DEPARA.CODIGO_BANCO_DE
              AND ANTERIOR.CODIGO_AGENCIA_DE = NOVO_DEPARA.CODIGO_AGENCIA_DE
       )
 ORDER BY NOVO_DEPARA.CODIGO_BANCO_DE,
          NOVO_DEPARA.CODIGO_AGENCIA_DE;
