-- Consulta complementar: retorna somente periodos ainda nao existentes no DE-PARA anterior.
;WITH NOVO_DEPARA AS
(
    SELECT DISTINCT
           TFO.CODIGO AS CODIGO_PERIODO_DE,
           TFO.DESCRICAO AS TIPO_FOLHA_DE,
           TFO.PREFIXOESOCIAL AS PREFIXO_ESOCIAL,
           CASE
               WHEN TFO.CODIGO BETWEEN 14 AND 19 THEN 'IGNORAR'
               ELSE CAST(TFO.CODIGO AS VARCHAR(2))
           END AS NROPERIODO_PARA
      FROM TFO
)
SELECT NOVO_DEPARA.*
  FROM NOVO_DEPARA
 WHERE NOT EXISTS
       (
           SELECT 1
             FROM ZDEPARA_PERIODO_FOLHA AS ANTERIOR
            WHERE ANTERIOR.CODIGO_PERIODO_DE = NOVO_DEPARA.CODIGO_PERIODO_DE
       )
 ORDER BY NOVO_DEPARA.CODIGO_PERIODO_DE;
