IF OBJECT_ID('ZDEPARA_SCURSOCOMPL') IS NOT NULL
   DROP TABLE ZDEPARA_SCURSOCOMPL;

SELECT 
	  SOPHIA.CURSOS.PRODUTO AS COD_CURSO_DE, 
	  SOPHIA.CURSOS.NOME    AS CURSO,
	  14                    AS CODCOLIGADA,
	  ''                    AS CODIGO_PARA,
	  ''                    AS NIVEL_ENSINO,
	  ''                    AS NOME_PARA,
	  ''                    AS CURSO_PARA_HIST,
	  ''                    AS NOME_PARA_HIST
	  INTO ZDEPARA_SCURSOCOMPL
  FROM 
      SOPHIA.CURSOS (NOLOCK) 
 WHERE 
      NOT EXISTS (SELECT 1 FROM ZDEPARA_SCURSO AS Z WHERE Z.COD_CURSO_DE = SOPHIA.CURSOS.PRODUTO AND Z.CURSO = SOPHIA.CURSOS.NOME AND Z.CODCOLIGADA = 14)	  
ORDER BY  
      SOPHIA.CURSOS.PRODUTO;

SELECT * FROM ZDEPARA_SCURSOCOMPL;
