IF OBJECT_ID('ZDEPARA_SHABILITACAO_COMPL') IS NOT NULL
   DROP TABLE ZDEPARA_SHABILITACAO_COMPL;

SELECT 
      SOPHIA.SERIE.CURSO      AS COD_CURSO, 
	  ZDEPARA_SCURSO.CURSO    AS CURSO, 
	  SOPHIA.SERIE.CODIGO     AS COD_SERIE_DE,
	  SOPHIA.SERIE.DESCRICAO  AS NOME_SERIE, 
	  SOPHIA.SERIE.ORDEM      AS ORDEM,
	  SOPHIA.SERIE.DESCRICAO  AS DESCRICAO,
	  14                      AS CODCOLIGADA, 
	  ''                      AS CODCURSO_PARA,
	  ''                      AS CODIGO_PARA,
	  ''                      AS DESCRICAO_PARA
	  INTO ZDEPARA_SHABILITACAO_COMPL
  FROM 
      SOPHIA.SERIE (NOLOCK)  
      LEFT JOIN ZDEPARA_SCURSO (NOLOCK)  
	         ON ZDEPARA_SCURSO.COD_CURSO_DE = SOPHIA.SERIE.CURSO 
WHERE NOT EXISTS (SELECT 1 FROM ZDEPARA_SHABILITACAO AS Z WHERE Z.COD_CURSO = SOPHIA.SERIE.CURSO AND Z.CURSO = ZDEPARA_SCURSO.CURSO);

SELECT * FROM ZDEPARA_SHABILITACAO_COMPL;

