IF OBJECT_ID('ZDEPARA_SPLETIVO_COMPL') IS NOT NULL
   DROP TABLE ZDEPARA_SPLETIVO_COMPL;

SELECT 
      SOPHIA.PERIODOS.CODIGO                AS CODIGO_DE,
	  SOPHIA.PERIODOS.DESCRICAO             AS DESCRICAO,
      CAST(SOPHIA.PERIODOS.INICIO AS DATE)  AS INICIO, 
      CAST(SOPHIA.PERIODOS.TERMINO AS DATE) AS TERMINO, 
	  14                                    AS CODCOLIGADA,
	  U.UNIDADE                             AS CODFILIAL,
	  ''                                    AS CODFILIAL_PARA,
	  ''                                    AS NIVELENSINO,
	  ''                                    AS CODIGO_PARA
	  INTO ZDEPARA_SPLETIVO_COMPL
  FROM 
      SOPHIA.PERIODOS (NOLOCK)
	  CROSS JOIN (
	              SELECT UNIDADE FROM SOPHIA.MATRICULA GROUP BY UNIDADE ) AS U
 WHERE
      YEAR(SOPHIA.PERIODOS.INICIO) = '2026'
  AND NOT EXISTS (SELECT 1 FROM ZDEPARA_SPLETIVO AS Z WHERE Z.CODIGO_DE = SOPHIA.PERIODOS.CODIGO AND Z.CODFILIAL = U.UNIDADE)
ORDER BY 
      SOPHIA.PERIODOS.CODIGO;

SELECT * FROM ZDEPARA_SPLETIVO_COMPL;
