IF OBJECT_ID('ZDEPARA_STURNO_COMPL') IS NOT NULL
   DROP TABLE ZDEPARA_STURNO_COMPL;

SELECT 
	  SOPHIA.TURNOS.CODIGO               AS CODIGO, 
	  SOPHIA.CATEGORIAS_TURNOS.DESCRICAO AS TURNO,
	  SOPHIA.TURNOS.DESCRICAO            AS DESCRICAO, 
	  SOPHIA.TURNOS.NUM_AULAS            AS NUM_AULAS,
	  SOPHIA.TURNOS.DURACAO              AS DURACAO,
	  14                                 AS CODCOLIGADA,
	  SOPHIA.TURMAS.UNIDADE              AS CODFILIAL,
	  ''                                 AS CODFILIAL_PARA,
	  ''                                 AS NIVELENSINO,
	  ''                                 AS CODIGO_PARA,
	  ''                                 AS DESCRICAO_PARA
	  INTO ZDEPARA_STURNO_COMPL
  FROM 
      SOPHIA.TURNOS (NOLOCK)
	  JOIN SOPHIA.TURMAS (NOLOCK)
	       JOIN SOPHIA.UNIDADES (NOLOCK)
	         ON SOPHIA.UNIDADES.CODIGO = SOPHIA.TURMAS.UNIDADE
		   JOIN SOPHIA.PERIODOS (NOLOCK)
		     ON SOPHIA.PERIODOS.CODIGO = SOPHIA.TURMAS.PERIODO
	    ON SOPHIA.TURMAS.TURNO = SOPHIA.TURNOS.CODIGO
      LEFT JOIN SOPHIA.CATEGORIAS_TURNOS (NOLOCK) 
	         ON SOPHIA.CATEGORIAS_TURNOS.CODIGO = SOPHIA.TURNOS.CATEGORIA 
 WHERE
      YEAR(SOPHIA.PERIODOS.INICIO) = '2026'
  AND EXISTS (SELECT 1 
	            FROM 
				    SOPHIA.TURMAS
				    JOIN ZDEPARA_SPLETIVO
					  ON ZDEPARA_SPLETIVO.CODIGO_DE = SOPHIA.TURMAS.PERIODO
			   WHERE
			        SOPHIA.TURMAS.TURNO = SOPHIA.TURNOS.CODIGO)
  AND NOT EXISTS (SELECT 1 FROM ZDEPARA_STURNO AS Z WHERE Z.CODIGO = SOPHIA.TURNOS.CODIGO AND Z.TURNO = SOPHIA.CATEGORIAS_TURNOS.DESCRICAO AND Z.CODFILIAL = SOPHIA.TURMAS.UNIDADE)
GROUP BY 
     SOPHIA.TURNOS.CODIGO,              
	 SOPHIA.CATEGORIAS_TURNOS.DESCRICAO,
	 SOPHIA.TURNOS.DESCRICAO,           
	 SOPHIA.TURNOS.NUM_AULAS,          
	 SOPHIA.TURNOS.DURACAO,             
	 SOPHIA.TURMAS.UNIDADE
ORDER BY
    SOPHIA.TURMAS.UNIDADE,
	SOPHIA.TURNOS.CODIGO;             

SELECT * FROM ZDEPARA_STURNO_COMPL ORDER BY CODFILIAL, CODIGO;

