IF OBJECT_ID('ZDEPARA_SHORARIO') IS NOT NULL
   DROP TABLE ZDEPARA_SHORARIO
GO

SELECT 
      SOPHIA.TURNOS.CODIGO                            AS CODTURNO, 
	  SOPHIA.TURNOS.DESCRICAO                         AS DESCRICAO, 
	  SOPHIA.TURNOS.MANHA                             AS MANHA,
	  SOPHIA.TURNOS.TARDE                             AS TARDE,
	  SOPHIA.TURNOS.NOITE                             AS NOITE, 
	  SOPHIA.TURNOS.NUM_AULAS                         AS NUM_AULAS,
	  SOPHIA.TURNOS.DURACAO                           AS DURACAO,
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO01, 108) AS INICIO01, 
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO02, 108) AS INICIO02, 
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO03, 108) AS INICIO03, 
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO04, 108) AS INICIO04, 
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO05, 108) AS INICIO05, 
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO06, 108) AS INICIO06, 
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO07, 108) AS INICIO07, 
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO08, 108) AS INICIO08, 
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO09, 108) AS INICIO09,
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO10, 108) AS INICIO10,
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO11, 108) AS INICIO11,
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO12, 108) AS INICIO12,
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO13, 108) AS INICIO13,
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO14, 108) AS INICIO14,
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO15, 108) AS INICIO15,
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO16, 108) AS INICIO16,
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO17, 108) AS INICIO17,
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO18, 108) AS INICIO18,
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO19, 108) AS INICIO19,
      CONVERT(VARCHAR(5),SOPHIA.TURNOS.INICIO20, 108) AS INICIO20,
	  1                                               AS CODCOLIGADA,
	  ''                                              AS CODIGO_PARA ,
	  ''                                              AS DIA_SEMANA
	  INTO ZDEPARA_SHORARIO
  FROM 
      SOPHIA.TURNOS (NOLOCK) 
      LEFT JOIN SOPHIA.CATEGORIAS_TURNOS (NOLOCK) 
	         ON  SOPHIA.CATEGORIAS_TURNOS.CODIGO = SOPHIA.TURNOS.CATEGORIA 
 WHERE
      EXISTS (SELECT 1 
	            FROM 
				    SOPHIA.TURMAS
				    JOIN ZDEPARA_SPLETIVO
					  ON ZDEPARA_SPLETIVO.CODIGO_DE = SOPHIA.TURMAS.PERIODO
			   WHERE
			        SOPHIA.TURMAS.TURNO = SOPHIA.TURNOS.CODIGO)

SELECT * FROM ZDEPARA_SHORARIO

--SELECT * FROM SOPHIA.TURNOS

SELECT * FROM CORPORERM.DBO.SHORARIO