IF OBJECT_ID('ZDEPARA_SDISCIPLINAS_COMPL') IS NOT NULL
   DROP TABLE ZDEPARA_SDISCIPLINAS_COMPL;

SELECT 
      SOPHIA.DISCIPLINAS.CODIGO           AS CODIGO,
	  SOPHIA.DISCIPLINAS.NOME             AS NOME, 
	  SOPHIA.DISCIPLINAS.NOME_RESUM       AS NOM_RESUM, 
	  REPLACE(CAST(SOPHIA.DISCIPLINAS.CH_N_PRESENCIAL AS NUMERIC(10,1)),'.',',')  AS CH_N_PRESENCIAL, 
	  REPLACE(CAST(SOPHIA.DISCIPLINAS.CH AS NUMERIC (10,1)),'.',',')               AS CH,  
	  REPLACE(CAST(SOPHIA.DISCIPLINAS.CREDITOS AS NUMERIC (10,1)),'.',',')        AS CREDITO, 
	  14                                  AS CODCOLIGADA,
	  ''                                   AS NIVELENSINO,
	  ''                                  AS CODIGO_PARA,
	  ''                                  AS CODIGO_PARA_DISC_HISTORICO
	  INTO ZDEPARA_SDISCIPLINAS_COMPL
  FROM 
      SOPHIA.DISCIPLINAS
 WHERE 
      NOT EXISTS (SELECT 1 FROM ZDEPARA_SDISCIPLINAS AS Z WHERE Z.CODIGO = SOPHIA.DISCIPLINAS.CODIGO AND Z.NOME = SOPHIA.DISCIPLINAS.NOME AND Z.CH = CAST(SOPHIA.DISCIPLINAS.CH AS MONEY))	  ;

SELECT * FROM ZDEPARA_SDISCIPLINAS_COMPL;
