IF OBJECT_ID('ZDEPARA_SDOCUMENTO_COMPL') IS NOT NULL
   DROP TABLE ZDEPARA_SDOCUMENTO_COMPL;

SELECT 
      SOPHIA.DOCUMENTOS.CODIGO    AS CODIGO,
	  SOPHIA.DOCUMENTOS.DESCRICAO AS DESCRICAO, 
	  ''                          AS CODIGO_PARA,
	  ''                          AS DESCRICAO_PARA
	  INTO ZDEPARA_SDOCUMENTO_COMPL
  FROM 
      SOPHIA.DOCUMENTOS
 WHERE
      NOT EXISTS (SELECT 1 FROM ZDEPARA_SDOCUMENTO AS Z WHERE Z.CODIGO = SOPHIA.DOCUMENTOS.CODIGO AND Z.DESCRICAO = SOPHIA.DOCUMENTOS.DESCRICAO)      ;


SELECT * FROM ZDEPARA_SDOCUMENTO_COMPL;
