IF OBJECT_ID('ZDEPARA_SGRADE_COMPL') IS NOT NULL
   DROP TABLE ZDEPARA_SGRADE_COMPL;

SELECT 
      DADOS.*
	  INTO ZDEPARA_SGRADE_COMPL
FROM
(
SELECT DISTINCT
      SOPHIA.TURMAS.CURSO                AS CODCURSO,
      SOPHIA.MATRIZ_CURRICULAR.CODIGO    AS CODHABILITACAO,
      SOPHIA.MATRIZ_CURRICULAR.CODIGO    AS CODGRADE,
	  SOPHIA.PERIODOS.CODIGO             AS CODANO,
	  SOPHIA.PERIODOS.DESCRICAO          AS ANO,
	  SOPHIA.CURSOS.NOME                 AS NOME_CURSO,
	  SOPHIA.MATRIZ_CURRICULAR.DESCRICAO AS NOME_MATRIZ,
	  SOPHIA.SERIE.CODIGO                AS CODIGO_SERIE,
	  SOPHIA.SERIE.DESCRICAO             AS SERIE,
	  14                                 AS CODCOLIGADA,
	  ''                                 AS CODCURSO_PARA,
	  ''                                 AS CODHABILITACAO_PARA,
      ''                                 AS CODIGO_PARA,
	  ''                                 AS PERIODO_GRADE
  FROM 
      SOPHIA.MATRICULA
	  JOIN SOPHIA.PERIODOS
		ON SOPHIA.PERIODOS.CODIGO = SOPHIA.MATRICULA.PERIODO
	  JOIN SOPHIA.INSCRICAO
		   JOIN SOPHIA.MATRIZ_CURRICULAR (NOLOCK)
		        JOIN SOPHIA.CURSOS
		          ON SOPHIA.CURSOS.PRODUTO = SOPHIA.MATRIZ_CURRICULAR.CURSO
		     ON SOPHIA.MATRIZ_CURRICULAR.CODIGO = SOPHIA.INSCRICAO.MATRIZ_CURRICULAR
		    AND SOPHIA.MATRIZ_CURRICULAR.CURSO  = SOPHIA.INSCRICAO.CURSO
		ON SOPHIA.INSCRICAO.CODIGO = SOPHIA.MATRICULA.inscricao
	   AND SOPHIA.INSCRICAO.CURSO  = SOPHIA.MATRICULA.CURSO
	  JOIN SOPHIA.TURMAS
	    ON SOPHIA.TURMAS.CODIGO = SOPHIA.MATRICULA.TURMA_REGULAR
	  JOIN SOPHIA.SERIE
        ON SOPHIA.SERIE.CURSO  = SOPHIA.TURMAS.CURSO  
	   AND SOPHIA.SERIE.CODIGO = SOPHIA.TURMAS.SERIE
 WHERE
      YEAR(SOPHIA.PERIODOS.INICIO) = '2026'
GROUP BY 
     SOPHIA.TURMAS.CURSO,    
	 SOPHIA.MATRIZ_CURRICULAR.CODIGO,   
	 SOPHIA.MATRIZ_CURRICULAR.CODIGO,   
	 SOPHIA.PERIODOS.CODIGO,            
	 SOPHIA.PERIODOS.DESCRICAO,         
	 SOPHIA.CURSOS.NOME,                
	 SOPHIA.MATRIZ_CURRICULAR.DESCRICAO,
	 SOPHIA.SERIE.CODIGO,
	 SOPHIA.TURMAS.UNIDADE,
	 SOPHIA.SERIE.DESCRICAO,
	 SOPHIA.TURMAS.NOME        

UNION

 --NIVEL SUPERIOR 

SELECT DISTINCT
      SOPHIA.TURMAS.CURSO                AS CODCURSO,
      SOPHIA.CURRICULO.CODIGO            AS CODHABILITACAO,
      SOPHIA.CURRICULO.CODIGO            AS CODGRADE,
	  SOPHIA.PERIODOS.CODIGO             AS CODANO,
	  SOPHIA.PERIODOS.DESCRICAO          AS ANO,
	  SOPHIA.CURSOS.NOME                 AS NOME_CURSO,
	  SOPHIA.CURRICULO.DESCRICAO         AS NOME_MATRIZ,
	  SOPHIA.SERIE.CODIGO                AS CODIGO_SERIE,
	  SOPHIA.SERIE.DESCRICAO             AS SERIE,
	  14                                 AS CODCOLIGADA,
	  ''                                 AS CODCURSO_PARA,
	  ''                                 AS CODHABILITACAO_PARA,
      ''                                 AS CODIGO_PARA,
	  ''                                 AS PERIODO_GRADE
  FROM 
      SOPHIA.MATRICULA
	  JOIN SOPHIA.PERIODOS
		ON SOPHIA.PERIODOS.CODIGO = SOPHIA.MATRICULA.PERIODO
	  JOIN SOPHIA.INSCRICAO
		   JOIN SOPHIA.CURRICULO (NOLOCK)
		        JOIN SOPHIA.CURSOS
		          ON SOPHIA.CURSOS.PRODUTO = SOPHIA.CURRICULO.CURSO
		     ON SOPHIA.CURRICULO.CODIGO = SOPHIA.INSCRICAO.CURRICULO
		ON SOPHIA.INSCRICAO.CODIGO = SOPHIA.MATRICULA.inscricao
	   AND SOPHIA.INSCRICAO.CURSO  = SOPHIA.MATRICULA.CURSO
	  JOIN SOPHIA.TURMAS
	    ON SOPHIA.TURMAS.CODIGO = SOPHIA.MATRICULA.TURMA_REGULAR
	  JOIN SOPHIA.SERIE
        ON SOPHIA.SERIE.CURSO  = SOPHIA.TURMAS.CURSO  
	   AND SOPHIA.SERIE.CODIGO = SOPHIA.TURMAS.SERIE
 WHERE
      YEAR(SOPHIA.PERIODOS.INICIO) = '2026'
GROUP BY 
     SOPHIA.TURMAS.CURSO,    
	 SOPHIA.CURRICULO.CODIGO,   
	 SOPHIA.CURRICULO.CODIGO,   
	 SOPHIA.PERIODOS.CODIGO,            
	 SOPHIA.PERIODOS.DESCRICAO,         
	 SOPHIA.CURSOS.NOME,                
	 SOPHIA.CURRICULO.DESCRICAO,
	 SOPHIA.SERIE.CODIGO,
	 SOPHIA.TURMAS.UNIDADE,
	 SOPHIA.SERIE.DESCRICAO,
	 SOPHIA.TURMAS.NOME   ) AS DADOS
WHERE NOT EXISTS (SELECT 1 
                    FROM ZDEPARA_SGRADE AS Z 
				   WHERE Z.CODCURSO       = DADOS.CODCURSO 
				     AND Z.CODHABILITACAO = DADOS.CODHABILITACAO 
					 AND Z.CODGRADE       = DADOS.CODGRADE 
					 AND Z.CODANO         = DADOS.CODANO 
					 AND Z.CODIGO_SERIE   = DADOS.CODIGO_SERIE 
					 AND Z.SERIE          = DADOS.SERIE)	 

ORDER BY 1,2,3,6 ;

SELECT * FROM ZDEPARA_SGRADE_COMPL;