IF OBJECT_ID('ZDEPARA_SINSTITUICAO_COMPL') IS NOT NULL
   DROP TABLE ZDEPARA_SINSTITUICAO_COMPL;

SELECT DISTINCT 
      SOPHIA.JURIDICA.CODIGO       AS CODIGO,
	  SOPHIA.JURIDICA.NOMEFANTASIA AS NOMEFANTASIA, 
	  SOPHIA.JURIDICA.RAZAOSOCIAL  AS RAZAOSICIAL,
	  SOPHIA.JURIDICA.CNPJ         AS CNPJ, 
	  ''                           AS CODIGO_PARA
	  INTO ZDEPARA_SINSTITUICAO_COMPL
  FROM 
      SOPHIA.JURIDICA (NOLOCK)
	  JOIN SOPHIA.HISTORICO (NOLOCK)
	    ON SOPHIA.HISTORICO.ESCOLA = SOPHIA.JURIDICA.CODIGO
 WHERE
      NOT EXISTS (SELECT 1 FROM ZDEPARA_SINSTITUICAO AS Z WHERE Z.CODIGO = SOPHIA.JURIDICA.CODIGO)
ORDER BY 
      SOPHIA.JURIDICA.NOMEFANTASIA;

SELECT * FROM ZDEPARA_SINSTITUICAO_COMPL; 



