IF OBJECT_ID('ZDEPARA_STIPOPARTICIPACAO_COMPL') IS NOT NULL
   DROP TABLE ZDEPARA_STIPOPARTICIPACAO_COMPL;

SELECT 
	  SOPHIA.CARGOS.CODIGO    AS CODIGO,   
	  SOPHIA.CARGOS.DESCRICAO AS DESCRICAO,
	  14                      AS CODCOLIGADA,
	  ''                      AS CODIGO_PARA
	  INTO ZDEPARA_STIPOPARTICIPACAO_COMPL
  FROM 
	  SOPHIA.CARGOS (NOLOCK)
 WHERE
      NOT EXISTS (SELECT 1 FROM ZDEPARA_STIPOPARTICIPACAO AS Z WHERE Z.CODIGO = SOPHIA.CARGOS.CODIGO)	  
ORDER BY 
      SOPHIA.CARGOS.CODIGO;


SELECT * FROM ZDEPARA_STIPOPARTICIPACAO_COMPL;

