IF OBJECT_ID('ZDEPARA_SPREDIO_COMPL') IS NOT NULL
   DROP TABLE ZDEPARA_SPREDIO_COMPL;

SELECT 
	  SOPHIA.UNIDADES.CODIGO    AS CODIGO,
	  SOPHIA.UNIDADES.DESCRICAO AS DESCRICAO,
	  14                        AS CODCOLIGADA,
	  ''                        AS CODFILIAL_PARA,
	  ''                        AS CODIGO_PARA
	  INTO ZDEPARA_SPREDIO_COMPL
  FROM  
		SOPHIA.UNIDADES  (NOLOCK)
		CROSS JOIN (
		            SELECT CODIGO FROM SOPHIA.UNIDADES GROUP BY CODIGO ) AS F
 WHERE
      NOT EXISTS (SELECT 1 FROM ZDEPARA_SPREDIO AS Z WHERE Z.CODIGO = SOPHIA.UNIDADES.CODIGO AND Z.DESCRICAO = SOPHIA.UNIDADES.DESCRICAO)					
ORDER BY 
	  F.CODIGO;

SELECT * FROM ZDEPARA_SPREDIO_COMPL ORDER BY CODFILIAL_PARA,CODIGO ;