IF OBJECT_ID('ZDEPARA_BLOCO_COMPL') IS NOT NULL
   DROP TABLE ZDEPARA_BLOCO_COMPL;

SELECT 
	  SOPHIA.BLOCOS.CODIGO    AS CODIGO,
	  SOPHIA.BLOCOS.UNIDADE   AS UNIDADE,
	  SOPHIA.BLOCOS.DESCRICAO AS DESCRICAO,
	  14                      AS CODCOLIGADA,
	  ''                      AS CODFILIAL_PARA,
	  ''                      AS CODPREDIO_PARA,
	  ''                      AS CODIGO_PARA
	  INTO ZDEPARA_BLOCO_COMPL
  FROM
		SOPHIA.BLOCOS  (NOLOCK)
 WHERE 
      NOT EXISTS (SELECT 1 FROM ZDEPARA_BLOCO AS Z WHERE Z.CODIGO = SOPHIA.BLOCOS.CODIGO AND Z.UNIDADE = SOPHIA.BLOCOS.UNIDADE)	
ORDER BY 
		SOPHIA.BLOCOS.CODIGO;

SELECT * FROM ZDEPARA_BLOCO_COMPL;