IF OBJECT_ID('ZDEPARA_SALA_COMPL') IS NOT NULL
   DROP TABLE ZDEPARA_SALA_COMPL;

SELECT 
	  SOPHIA.SALAS.CODIGO    AS CODIGO,
	  SOPHIA.SALAS.UNIDADE   AS UNIDADE,
	  SOPHIA.SALAS.DESCRICAO AS DESCRICAO,
	  14                     AS CODCOLIGADA,
	  ''                     AS CODFILIAL_PARA,
	  ''                     AS PREDIO_PARA,
	  ''                     AS BLOCO_PARA,
	  ''                     AS CODIGO_PARA
	  INTO ZDEPARA_SALA_COMPL
  FROM 
		SOPHIA.SALAS  (NOLOCK)
 WHERE
      NOT EXISTS (SELECT 1 FROM ZDEPARA_SALA AS Z WHERE Z.CODIGO = SOPHIA.SALAS.CODIGO AND Z.UNIDADE = SOPHIA.SALAS.UNIDADE )		
ORDER BY 
	  SOPHIA.SALAS.UNIDADE, SOPHIA.SALAS.CODIGO;

SELECT * FROM ZDEPARA_SALA_COMPL ORDER BY CODFILIAL_PARA, CODIGO;