IF OBJECT_ID('ZDEPARA_SDISCGRADE_COMPL') IS NOT NULL
   DROP TABLE ZDEPARA_SDISCGRADE_COMPL;

SELECT
      DADOS.*
	  INTO ZDEPARA_SDISCGRADE_COMPL
FROM
(
/* TRAZ DADOS PARA OS CURSOS DO ENSINO BÁSICO DO SOPHIA */
SELECT DISTINCT 
	  
	  CAST(SOPHIA.GRADES.CODIGO                  AS VARCHAR)                     AS CODIGO,
	  CAST(SOPHIA.CURSOS.PRODUTO                 AS VARCHAR)                     AS COD_CURSO,
	  CAST(SOPHIA.CURSOS.NOME                    AS VARCHAR)                     AS NOME_CURSO,
	  CAST(SOPHIA.MATRIZ_CURRICULAR.CODIGO       AS VARCHAR)                     AS COD_MATRIZ,
	  CAST(SOPHIA.MATRIZ_CURRICULAR.DESCRICAO    AS VARCHAR)                     AS NOME_MATRIZ,
	  CAST(SOPHIA.SERIE.CODIGO                   AS VARCHAR)                     AS COD_SERIE,
	  CAST(SOPHIA.SERIE.DESCRICAO                AS VARCHAR)                     AS NOME_SERIE,
	  CAST(SOPHIA.PERIODOS.DESCRICAO             AS VARCHAR)                     AS ANO,
	  CAST(SOPHIA.GRADES.DISCIPLINA              AS VARCHAR)                     AS DISCIPLINA, 
	  CAST(SOPHIA.DISCIPLINAS.NOME               AS VARCHAR)                     AS NOME,
	  CAST(14                                    AS VARCHAR)                     AS CODCOLIGADA,
	  CAST(''                                    AS VARCHAR)                     AS CODCURSO_PARA,
	  CAST(''                                    AS VARCHAR)                     AS CODHABILITACAO_PARA,
	  CAST(''                                    AS VARCHAR)                     AS CODGRADE_PARA,
	  CAST(''                                    AS VARCHAR)                     AS CODIDHABILITACAO_PARA,
	  CAST(''                                    AS VARCHAR)                     AS CODPERIODO_PARA,
	  CAST(''                                    AS VARCHAR)                     AS CODDISC_PARA
  FROM 
      SOPHIA.MATRICULA
	  JOIN SOPHIA.PERIODOS
		ON SOPHIA.PERIODOS.CODIGO = SOPHIA.MATRICULA.PERIODO
	  JOIN SOPHIA.INSCRICAO
		   JOIN SOPHIA.MATRIZ_CURRICULAR (NOLOCK)
		        JOIN SOPHIA.CURSOS
		          ON SOPHIA.CURSOS.PRODUTO = SOPHIA.MATRIZ_CURRICULAR.CURSO
		     ON SOPHIA.MATRIZ_CURRICULAR.CODIGO = SOPHIA.INSCRICAO.MATRIZ_CURRICULAR
		    AND SOPHIA.MATRIZ_CURRICULAR.CURSO  = SOPHIA.INSCRICAO.CURSO
		ON SOPHIA.INSCRICAO.CODIGO = SOPHIA.MATRICULA.inscricao
	   AND SOPHIA.INSCRICAO.CURSO  = SOPHIA.MATRICULA.CURSO
	  JOIN SOPHIA.TURMAS
	    ON SOPHIA.TURMAS.CODIGO = SOPHIA.MATRICULA.TURMA_REGULAR
	  JOIN SOPHIA.SERIE
	       JOIN SOPHIA.GRADES
				JOIN SOPHIA.DISCIPLINAS
				  ON SOPHIA.DISCIPLINAS.CODIGO = SOPHIA.GRADES.DISCIPLINA
		     ON SOPHIA.GRADES.SERIE = SOPHIA.SERIE.CODIGO
        ON SOPHIA.SERIE.CURSO  = SOPHIA.TURMAS.CURSO  
	   AND SOPHIA.SERIE.CODIGO = SOPHIA.TURMAS.SERIE
 WHERE
      YEAR(SOPHIA.PERIODOS.INICIO) = '2026'

UNION
/* TRAZ DADOS PARA OS CURSOS DO ENSINO SUPERIOR DO SOPHIA */
SELECT DISTINCT 
	  
	  CAST(SOPHIA.GRADES.CODIGO       AS VARCHAR)                                 AS CODIGO,
	  CAST(SOPHIA.CURSOS.PRODUTO      AS VARCHAR)                                 AS COD_CURSO,
	  CAST(SOPHIA.CURSOS.NOME         AS VARCHAR)                                 AS NOME_CURSO,
	  CAST(SOPHIA.CURRICULO.CODIGO    AS VARCHAR)                                 AS COD_MATRIZ,
	  CAST(SOPHIA.CURRICULO.DESCRICAO AS VARCHAR)                                 AS NOME_MATRIZ,
	  CAST(SOPHIA.SERIE.CODIGO        AS VARCHAR)                                 AS COD_SERIE,
	  CAST(SOPHIA.SERIE.DESCRICAO     AS VARCHAR)                                 AS NOME_SERIE,
	  CAST(SOPHIA.PERIODOS.DESCRICAO  AS VARCHAR)                                 AS ANO,
	  CAST(SOPHIA.GRADES.DISCIPLINA   AS VARCHAR)                                 AS DISCIPLINA, 
	  CAST(SOPHIA.DISCIPLINAS.NOME    AS VARCHAR)                                 AS NOME,
	  CAST(14                         AS VARCHAR)                                 AS CODCOLIGADA,
	  CAST(''                         AS VARCHAR)                                 AS CODCURSO_PARA,
	  CAST(''                         AS VARCHAR)                                 AS CODHABILITACAO_PARA,
	  CAST(''                         AS VARCHAR)                                 AS CODGRADE_PARA,
	  CAST(''                         AS VARCHAR)                                 AS CODIDHABILITACAO_PARA,
	  CAST(''                         AS VARCHAR)                                 AS CODPERIODO_PARA,
	  CAST(''                         AS VARCHAR)                                 AS CODDISC_PARA
  FROM 
      SOPHIA.MATRICULA
	  JOIN SOPHIA.PERIODOS
		ON SOPHIA.PERIODOS.CODIGO = SOPHIA.MATRICULA.PERIODO
	  JOIN SOPHIA.INSCRICAO
		   JOIN SOPHIA.CURRICULO (NOLOCK)
		        JOIN SOPHIA.CURSOS
		          ON SOPHIA.CURSOS.PRODUTO = SOPHIA.CURRICULO.CURSO
		     ON SOPHIA.CURRICULO.CODIGO = SOPHIA.INSCRICAO.CURRICULO
		ON SOPHIA.INSCRICAO.CODIGO = SOPHIA.MATRICULA.inscricao
	   AND SOPHIA.INSCRICAO.CURSO  = SOPHIA.MATRICULA.CURSO
	  JOIN SOPHIA.TURMAS
	    ON SOPHIA.TURMAS.CODIGO = SOPHIA.MATRICULA.TURMA_REGULAR
	  JOIN SOPHIA.SERIE
	       JOIN SOPHIA.GRADES
				JOIN SOPHIA.DISCIPLINAS
				  ON SOPHIA.DISCIPLINAS.CODIGO = SOPHIA.GRADES.DISCIPLINA
		     ON SOPHIA.GRADES.SERIE = SOPHIA.SERIE.CODIGO
        ON SOPHIA.SERIE.CURSO  = SOPHIA.TURMAS.CURSO  
	   AND SOPHIA.SERIE.CODIGO = SOPHIA.TURMAS.SERIE
 WHERE
      YEAR(SOPHIA.PERIODOS.INICIO) = '2026'
) AS DADOS
WHERE 
     NOT EXISTS (SELECT 1 FROM ZDEPARA_SDISCGRADE AS Z WHERE Z.CODIGO = DADOS.CODIGO AND Z.COD_CURSO = DADOS.COD_CURSO AND Z.COD_MATRIZ = DADOS.COD_MATRIZ AND Z.NOME_MATRIZ = DADOS.NOME_MATRIZ AND Z.ANO = DADOS.ANO AND Z.DISCIPLINA = DADOS.DISCIPLINA AND Z.NOME = DADOS.NOME)

ORDER BY
    DADOS.COD_CURSO, DADOS.ANO, DADOS.COD_MATRIZ, DADOS.COD_SERIE

SELECT * FROM ZDEPARA_SDISCGRADE_COMPL

 