IF OBJECT_ID('ZDEPARA_SHABILITACAOFILIAL_COMPL') IS NOT NULL
   DROP TABLE ZDEPARA_SHABILITACAOFILIAL_COMPL;

SELECT
      DADOS.*
	  INTO ZDEPARA_SHABILITACAOFILIAL_COMPL	
  FROM
  (
/* TRAZ DADOS DE MATRIZ APLICADA DA EDUCAÇÃO BÁSICA */
SELECT DISTINCT
	  SOPHIA.MATRIZ_CURRICULAR.CODIGO    AS CODIGO,
	  SOPHIA.CURSOS.PRODUTO              AS COD_CURSO,
	  SOPHIA.CURSOS.NOME                 AS NOME_CURSO,
	  SOPHIA.MATRIZ_CURRICULAR.CODIGO    AS COD_MATRIZ,
	  SOPHIA.MATRIZ_CURRICULAR.DESCRICAO AS NOME_MATRIZ,
	  SOPHIA.SERIE.CODIGO                AS COD_SERIE,
	  SOPHIA.SERIE.DESCRICAO             AS NOME_SERIE,
	  SOPHIA.PERIODOS.DESCRICAO          AS ANO,
	  SOPHIA.TURMAS.TURNO                AS COD_TURNO,
	  SOPHIA.TURNOS.DESCRICAO            AS NOME_TURNO,
	  14                                 AS CODCOLIGADA,
	  SOPHIA.TURMAS.UNIDADE              AS CODFILIAL,
	  ''                                 AS CODFILIAL_PARA,
	  ''                                 AS CODCURSO_PARA,
	  ''                                 AS CODHABILITACAO_PARA,
	  ''                                 AS CODGRADE_PARA,
	  ''                                 AS CODTURNO_PARA,
	  ''                                 AS NIVELENSINO,
	  ''                                 AS CODIGO_PARA
 FROM 
      SOPHIA.MATRICULA
	  JOIN SOPHIA.PERIODOS
		ON SOPHIA.PERIODOS.CODIGO = SOPHIA.MATRICULA.PERIODO
	  JOIN SOPHIA.INSCRICAO
		   JOIN SOPHIA.MATRIZ_CURRICULAR (NOLOCK)
		        JOIN SOPHIA.CURSOS
		          ON SOPHIA.CURSOS.PRODUTO = SOPHIA.MATRIZ_CURRICULAR.CURSO
		     ON SOPHIA.MATRIZ_CURRICULAR.CODIGO = SOPHIA.INSCRICAO.MATRIZ_CURRICULAR
		    AND SOPHIA.MATRIZ_CURRICULAR.CURSO  = SOPHIA.INSCRICAO.CURSO
		ON SOPHIA.INSCRICAO.CODIGO = SOPHIA.MATRICULA.inscricao
	   AND SOPHIA.INSCRICAO.CURSO  = SOPHIA.MATRICULA.CURSO
	  JOIN SOPHIA.TURMAS
	    ON SOPHIA.TURMAS.CODIGO = SOPHIA.MATRICULA.TURMA_REGULAR
	  JOIN SOPHIA.SERIE
        ON SOPHIA.SERIE.CURSO  = SOPHIA.TURMAS.CURSO  
	   AND SOPHIA.SERIE.CODIGO = SOPHIA.TURMAS.SERIE
      JOIN SOPHIA.TURNOS
	    ON SOPHIA.TURNOS.CODIGO = SOPHIA.TURMAS.TURNO
 WHERE
      YEAR(SOPHIA.PERIODOS.INICIO) = '2026'

UNION

/* TRAZ DADOS DE MATRIZ APLICADA DA EDUCAÇÃO SUPERIOR */
SELECT DISTINCT
	  SOPHIA.CURRICULO.CODIGO            AS CODIGO,
	  SOPHIA.CURSOS.PRODUTO              AS COD_CURSO,
	  SOPHIA.CURSOS.NOME                 AS NOME_CURSO,
	  SOPHIA.CURRICULO.CODIGO            AS COD_MATRIZ,
	  SOPHIA.CURRICULO.DESCRICAO         AS NOME_MATRIZ,
	  SOPHIA.SERIE.CODIGO                AS COD_SERIE,
	  SOPHIA.SERIE.DESCRICAO             AS NOME_SERIE,
	  SOPHIA.PERIODOS.DESCRICAO          AS ANO,
	  SOPHIA.TURMAS.TURNO                AS COD_TURNO,
	  SOPHIA.TURNOS.DESCRICAO            AS NOME_TURNO,
	  14                                 AS CODCOLIGADA,
	  SOPHIA.TURMAS.UNIDADE              AS CODFILIAL,
	  ''                                 AS CODFILIAL_PARA,
	  ''                                 AS CODCURSO_PARA,
	  ''                                 AS CODHABILITACAO_PARA,
	  ''                                 AS CODGRADE_PARA,
	  ''                                 AS CODTURNO_PARA,
	  ''                                 AS NIVELENSINO,
	  ''                                 AS CODIGO_PARA
  FROM 
      SOPHIA.MATRICULA
	  JOIN SOPHIA.PERIODOS
		ON SOPHIA.PERIODOS.CODIGO = SOPHIA.MATRICULA.PERIODO
	  JOIN SOPHIA.INSCRICAO
		   JOIN SOPHIA.CURRICULO (NOLOCK)
		        JOIN SOPHIA.CURSOS
		          ON SOPHIA.CURSOS.PRODUTO = SOPHIA.CURRICULO.CURSO
		     ON SOPHIA.CURRICULO.CODIGO = SOPHIA.INSCRICAO.CURRICULO
		ON SOPHIA.INSCRICAO.CODIGO = SOPHIA.MATRICULA.inscricao
	   AND SOPHIA.INSCRICAO.CURSO  = SOPHIA.MATRICULA.CURSO
	  JOIN SOPHIA.TURMAS
	    ON SOPHIA.TURMAS.CODIGO = SOPHIA.MATRICULA.TURMA_REGULAR
	  JOIN SOPHIA.SERIE
        ON SOPHIA.SERIE.CURSO  = SOPHIA.TURMAS.CURSO  
	   AND SOPHIA.SERIE.CODIGO = SOPHIA.TURMAS.SERIE
      JOIN SOPHIA.TURNOS
	    ON SOPHIA.TURNOS.CODIGO = SOPHIA.TURMAS.TURNO
 WHERE
      YEAR(SOPHIA.PERIODOS.INICIO) = '2026'
) AS DADOS
WHERE
     NOT EXISTS (SELECT 1 FROM ZDEPARA_SHABILITACAOFILIAL AS Z WHERE Z.CODIGO = DADOS.CODIGO AND Z.COD_CURSO = DADOS.COD_CURSO AND Z.COD_MATRIZ = DADOS.COD_MATRIZ AND Z.NOME_MATRIZ = DADOS.NOME_MATRIZ AND Z.COD_SERIE = DADOS.COD_SERIE AND Z.ANO = DADOS.ANO AND Z.COD_TURNO = DADOS.COD_TURNO AND Z.NOME_TURNO = DADOS.NOME_TURNO AND Z.CODFILIAL = DADOS.CODFILIAL)
ORDER BY 
      DADOS.COD_CURSO, DADOS.ANO, DADOS.COD_TURNO;

SELECT * FROM ZDEPARA_SHABILITACAOFILIAL_COMPL;

