/* GERA DE/PARA DE CAMPOS COMPLEMENTARES */

SELECT DISTINCT 
      SOPHIA.CONFIG_TAB_LIVRE_GRUPO.ID_CONFIG_TAB_LIVRE_GRUPO AS COD_GRUPO_DE,
      SOPHIA.CONFIG_TAB_LIVRE_GRUPO.DESCRICAO                 AS NOME_GRUPO_DE,
      SOPHIA.CONFIG_TAB_LIVRE.CODIGO                          AS CODIGO_DE,
      SOPHIA.CONFIG_TAB_LIVRE.NOME                            AS NOME_DE,
      ''                                                      AS TAB_PARA,
      ''                                                      AS CAMPO_PARA
  FROM  
      SOPHIA.FISICA
      JOIN ZDEPARA_SALUNO_RA
        ON ZDEPARA_SALUNO_RA.FISICA = SOPHIA.FISICA.CODIGO
      JOIN SOPHIA.TAB_DESCRICAO_DADOS 
           JOIN SOPHIA.CONFIG_TAB_LIVRE_GRUPO
                JOIN SOPHIA.CONFIG_TAB_LIVRE
                  ON SOPHIA.CONFIG_TAB_LIVRE.IDFK_CONFIG_TAB_LIVRE_GRUPO = SOPHIA.CONFIG_TAB_LIVRE_GRUPO.ID_CONFIG_TAB_LIVRE_GRUPO
             ON SOPHIA.CONFIG_TAB_LIVRE_GRUPO.ID_CONFIG_TAB_LIVRE_GRUPO = SOPHIA.TAB_DESCRICAO_DADOS.IDFK_CONFIG_TAB_LIVRE_GRUPO
        ON SOPHIA.TAB_DESCRICAO_DADOS.FISICA = SOPHIA.FISICA.CODIGO
 WHERE
      
  AND SOPHIA.CONFIG_TAB_LIVRE.NOME LIKE ('%SESC Carteirinha DEP%')  
   OR SOPHIA.CONFIG_TAB_LIVRE.NOME LIKE ('%Dep. Comerci�rio%')  
   OR SOPHIA.CONFIG_TAB_LIVRE.NOME LIKE ('%Cart�o RioCard n�m.%')  
   OR SOPHIA.CONFIG_TAB_LIVRE.NOME LIKE ('%Chip RioCard n�mero%')  
   OR SOPHIA.CONFIG_TAB_LIVRE.NOME LIKE ('%RioCard{1?4}� S�rie/Mod%')  
   OR SOPHIA.CONFIG_TAB_LIVRE.NOME LIKE ('%PCG {1?4}� s�rie/Mod%')  
   OR SOPHIA.CONFIG_TAB_LIVRE.NOME LIKE ('%PCG QUALI PROF AUTOD%')  
   OR SOPHIA.CONFIG_TAB_LIVRE.NOME LIKE ('%PCG EJA AUTOD%')  
   OR SOPHIA.CONFIG_TAB_LIVRE.NOME LIKE ('%Possui Bolsa Fam�lia%')  
   OR SOPHIA.CONFIG_TAB_LIVRE.NOME LIKE ('%Tablet%')  


SELECT * FROM ZDADOS_COMPL