IF OBJECT_ID('ZDEPARA_STATUSDISC_COMPL') IS NOT NULL
    DROP TABLE ZDEPARA_STATUSDISC_COMPL;

SELECT
    SOPHIA.SITUACAO_ALUNO.ID_SITUACAO_ALUNO   AS CODIGO,
    SOPHIA.SITUACAO_ALUNO.DESCRICAO           AS DESCRICAO,
    14                                        AS CODCOLIGADA,
    ''                                        AS CODFILIAL,
    ''                                        AS NIVELENSINO,
    ''                                        AS CODIGO_PARA,
    ''                                        AS DESCRICAO_PARA
INTO ZDEPARA_STATUSDISC_COMPL 
FROM
    SOPHIA.SITUACAO_ALUNO
    CROSS JOIN (
                SELECT UNIDADE FROM SOPHIA.MATRICULA GROUP BY UNIDADE
               ) F
 WHERE 
      NOT EXISTS (SELECT 1 FROM ZDEPARA_STATUSDISC AS Z WHERE Z.CODIGO = SOPHIA.SITUACAO_ALUNO.ID_SITUACAO_ALUNO AND Z.DESCRICAO = SOPHIA.SITUACAO_ALUNO.DESCRICAO);

SELECT * FROM ZDEPARA_STATUSDISC_COMPL ORDER BY 4,1;

