IF OBJECT_ID('ZDEPARA_RESULTADO_HISTORICO_COMPL') IS NOT NULL
   DROP TABLE ZDEPARA_RESULTADO_HISTORICO_COMPL;

SELECT 
      RESULTADO           AS RESULTADO,
      COUNT(*)            AS QTD_REGISTROS,
      14                  AS CODCOLIGADA,
      ''                  AS [CONSIDERAR__SIM_NAO],
      ''                  AS NIVEL_ENSINO,
      ''                  AS CODINSTITUICAO,
      ''                  AS DESCRICAO_PARA
      INTO ZDEPARA_RESULTADO_HISTORICO_COMPL
  FROM 
      SOPHIA.HISTORICO
 WHERE 
      NOT EXISTS (SELECT 1 FROM ZDEPARA_RESULTADO_HISTORICO AS Z WHERE Z.RESULTADO = SOPHIA.HISTORICO.RESULTADO)
GROUP BY
     RESULTADO;

SELECT * FROM ZDEPARA_RESULTADO_HISTORICO_COMPL ;