IF OBJECT_ID('PARTES_HISTORICO_COMPL') IS NOT NULL
   DROP TABLE PARTES_HISTORICO_COMPL;

SELECT 
      CODIGO                     AS CODIGO, 
      DESCRICAO                  AS DESCRICAO,
      ''                         AS CODIGO_PARA,
      ''                         AS DESCRICAO_PARA
      INTO PARTES_HISTORICO_COMPL
  FROM 
      SOPHIA.PARTES
 WHERE
      NOT EXISTS (SELECT 1 FROM PARTES_HISTORICO AS Z WHERE Z.CODIGO = SOPHIA.PARTES.CODIGO AND Z.DESCRICAO = SOPHIA.PARTES.DESCRICAO)      ;

SELECT * FROM PARTES_HISTORICO_COMPL;
