
SELECT X.* FROM (

SELECT 'PARTES_HISTORICO' AS TAB, COUNT (*) AS QTDE FROM PARTES_HISTORICO_COMPL UNION ALL
SELECT 'ZDEPARA_BLOCO' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_BLOCO_COMPL UNION ALL
SELECT 'ZDEPARA_GRUPO_OCORRENCIA' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_GRUPO_OCORRENCIA_COMPL UNION ALL
SELECT 'ZDEPARA_RESULTADO_HISTORICO' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_RESULTADO_HISTORICO_COMPL UNION ALL
SELECT 'ZDEPARA_SALA' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_SALA_COMPL UNION ALL
SELECT 'ZDEPARA_SCURSOCOMPL' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_SCURSOCOMPL UNION ALL
SELECT 'ZDEPARA_SDISCGRADE' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_SDISCGRADE_COMPL UNION ALL
SELECT 'ZDEPARA_SDISCIPLINAS' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_SDISCIPLINAS_COMPL UNION ALL
SELECT 'ZDEPARA_SDOCUMENTO' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_SDOCUMENTO_COMPL UNION ALL
SELECT 'ZDEPARA_SGRADE' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_SGRADE_COMPL UNION ALL
SELECT 'ZDEPARA_SHABILITACAO' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_SHABILITACAO_COMPL UNION ALL
SELECT 'ZDEPARA_SHABILITACAOFILIAL' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_SHABILITACAOFILIAL_COMPL UNION ALL
SELECT 'ZDEPARA_SINSTITUICAO' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_SINSTITUICAO_COMPL UNION ALL
SELECT 'ZDEPARA_SPLETIVO' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_SPLETIVO_COMPL UNION ALL
SELECT 'ZDEPARA_SPREDIO' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_SPREDIO_COMPL UNION ALL
SELECT 'ZDEPARA_STATUS' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_STATUS_COMPL UNION ALL
SELECT 'ZDEPARA_STATUSDISC' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_STATUSDISC_COMPL UNION ALL
SELECT 'ZDEPARA_STIPOPARTICIPACAO' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_STIPOPARTICIPACAO_COMPL UNION ALL
SELECT 'ZDEPARA_STURNO' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_STURNO_COMPL UNION ALL
SELECT 'ZDEPARA_TURMAS' AS TAB, COUNT (*) AS QTDE FROM ZDEPARA_TURMAS_COMPL ) AS X
WHERE X.QTDE>=1
ORDER BY QTDE DESC