IF OBJECT_ID('ZDEPARA_SHABILITACAO') IS NOT NULL
    DROP TABLE ZDEPARA_SHABILITACAO;

DECLARE @CODCOLIGADA INT
SET @CODCOLIGADA = 13

SELECT DISTINCT
    BITB_ACOMPA_MAT.CUR_ID     AS COD_CURSO,
    ZDEPARA_SCURSO.CURSO       AS CURSO,
    BITB_ACOMPA_MAT.TUR_FASE   AS COD_SERIE_DE,
    CASE 
        WHEN ZDEPARA_SCURSO.CURSO NOT LIKE 'EDUCA%' AND ZDEPARA_SCURSO.CURSO NOT LIKE 'ENSINO%' 
        THEN ZDEPARA_SCURSO.CURSO COLLATE Latin1_General_CI_AI
    ELSE
        CONCAT(
            BITB_ACOMPA_MAT.TUR_FASE,
            'º',
            SUBSTRING(BITB_ACOMPA_MAT.TUR_DESCRI, LEN(BITB_ACOMPA_MAT.TUR_DESCRI) - CHARINDEX('-', REVERSE(BITB_ACOMPA_MAT.TUR_DESCRI)) -1 , 1)
        ) END AS NOME_SERIE,
    BITB_ACOMPA_MAT.TUR_FASE AS ORDEM,
    BITB_ACOMPA_MAT.TUR_DESCRI AS DESCRICAO,
    @CODCOLIGADA AS CODCOLIGADA,
    '' AS CODCURSO_PARA,
    '' AS CODIGO_PARA,
    '' AS DESCRICAO_PARA
        INTO ZDEPARA_SHABILITACAO
FROM BITB_ACOMPA_MAT
INNER JOIN ZDEPARA_SCURSO
    ON ZDEPARA_SCURSO.COD_CURSO_DE = BITB_ACOMPA_MAT.CUR_ID
WHERE NULLIF(LTRIM(RTRIM(BITB_ACOMPA_MAT.TUR_DESCRI)), '') IS NOT NULL;

SELECT * FROM ZDEPARA_SHABILITACAO;