IF OBJECT_ID('ZDEPARA_SPLETIVO') IS NOT NULL
   DROP TABLE ZDEPARA_SPLETIVO;

DECLARE @CODCOLIGADA INT
SET @CODCOLIGADA = 13

SELECT 
      TB_PERIODO_LETIVO.PEL_PERID					AS CODIGO_DE,
	  TB_PERIODO_LETIVO.PEL_DESCRI             		AS DESCRICAO,
      CAST(TB_PERIODO_LETIVO.PEL_DATINI AS DATE) 	AS INICIO, 
      CAST(TB_PERIODO_LETIVO.PEL_DATFIN AS DATE) 	AS TERMINO, 
	  @CODCOLIGADA                        		AS CODCOLIGADA,
	  TB_PERIODO_LETIVO.UNIDON	             		AS CODFILIAL,
	  ''                                    		AS CODFILIAL_PARA,
	  ''                                    		AS NIVELENSINO,
	  ''                                    		AS CODIGO_PARA
	  INTO ZDEPARA_SPLETIVO
  FROM 
      TB_PERIODO_LETIVO
 WHERE
      TB_PERIODO_LETIVO.PEL_DESCRI LIKE '2026'
ORDER BY 
    ROW_NUMBER() 
	OVER (ORDER BY TB_PERIODO_LETIVO.PEL_DATINI)

SELECT * FROM ZDEPARA_SPLETIVO;