IF OBJECT_ID('ZDEPARA_STURNO') IS NOT NULL
	DROP TABLE ZDEPARA_STURNO
;

DECLARE @CODCOLIGADA INT
SET @CODCOLIGADA = 13

SELECT DISTINCT
	  TB_TURMA.TUR_ID		           	AS CODIGO, 
	  CASE 
	  	WHEN TB_TURMA.TUR_TURNO = 'M' THEN 'Matutino'
	  	WHEN TB_TURMA.TUR_TURNO = 'V' THEN 'Vespertino'
	  	WHEN TB_TURMA.TUR_TURNO = 'N' THEN 'Noturno'
	  	WHEN TB_TURMA.TUR_TURNO = 'I' THEN 'Integral'
	  END AS TURNO,
	  TB_TURMA.TUR_DESCRI            	AS DESCRICAO, 
	  TB_TURMA.TUR_NUMAULAS_DIA         AS NUM_AULAS,
	  TB_HORARIO.HOR_DURACAOAULAMIN     AS DURACAO,
	  @CODCOLIGADA                     AS CODCOLIGADA,
	  TB_TURMA.UNIDON	              	AS CODFILIAL,
	  ''                                AS CODFILIAL_PARA,
	  ''                                AS NIVELENSINO,
	  ''                                AS CODIGO_PARA,
	  ''                                AS DESCRICAO_PARA
	  INTO ZDEPARA_STURNO
FROM 
	TB_TURMA
LEFT JOIN TB_HORARIO
	ON TB_HORARIO.HOR_TURNO = TB_TURMA.TUR_TURNO
	AND TB_HORARIO.GRUPO_UNIDON = TB_TURMA.GRUPO_UNIDON
	AND TB_HORARIO.UNIDON = TB_TURMA.UNIDON
LEFT JOIN TB_PERIODO_LETIVO
	ON TB_PERIODO_LETIVO.PEL_PERID = TB_TURMA.TUR_PERID
WHERE TB_PERIODO_LETIVO.PEL_ANOREF LIKE '2026'
ORDER BY 
	TB_TURMA.TUR_ID,
	TB_TURMA.TUR_DESCRI
;

SELECT * FROM ZDEPARA_STURNO ;