IF OBJECT_ID('ZDEPARA_SDISCIPLINAS') IS NOT NULL
   DROP TABLE ZDEPARA_SDISCIPLINAS;

DECLARE @CODCOLIGADA INT
SET @CODCOLIGADA = 13

SELECT 
      TB_DISCIPLINA.DIS_DISID           AS CODIGO,
	  TB_DISCIPLINA.DIS_DESDIS          AS NOME, 
	  TB_DISCIPLINA.DIS_ABREVI       	AS NOM_RESUM, 
	  TB_DISCIPLINA.DIS_CHORTH  		AS CH_N_PRESENCIAL, 
	  TB_DISCIPLINA.DIS_CHORTH          AS CH,  
	  ''					         	AS CREDITO, 
	  @CODCOLIGADA                     AS CODCOLIGADA,
	  TB_SUBNIVEL_CURSO.SNC_ID      	AS NIVELENSINO,
	  ''                               	AS CODIGO_PARA,
	  ''                               	AS CODIGO_PARA_DISC_HISTORICO
	  INTO ZDEPARA_SDISCIPLINAS
  FROM 
      TB_DISCIPLINA
  LEFT JOIN TB_SUBNIVEL_CURSO
  	ON TB_SUBNIVEL_CURSO.SNC_ID = TB_DISCIPLINA.DIS_SNDID

SELECT * FROM ZDEPARA_SDISCIPLINAS ;