IF OBJECT_ID('ZDEPARA_SDOCUMENTO') IS NOT NULL
   DROP TABLE ZDEPARA_SDOCUMENTO;

SELECT 
      TB_DOCUMENTO.DOC_DOCID        AS CODIGO,
	  TB_DOCUMENTO.DOC_DESCRI     AS DESCRICAO, 
	  ''                          AS CODIGO_PARA,
	  ''                          AS DESCRICAO_PARA
	  INTO ZDEPARA_SDOCUMENTO
  FROM 
      TB_DOCUMENTO;

SELECT * FROM ZDEPARA_SDOCUMENTO;
