IF OBJECT_ID('ZDEPARA_SGRADE') IS NOT NULL
	DROP TABLE ZDEPARA_SGRADE
;

DECLARE @CODCOLIGADA INT
SET @CODCOLIGADA = 13

SELECT DISTINCT
      DADOS.*
	INTO ZDEPARA_SGRADE
FROM
(
SELECT DISTINCT
      ZDEPARA_SCURSO.COD_CURSO_DE        AS CODCURSO,
      ZDEPARA_SHABILITACAO.COD_SERIE_DE  AS CODHABILITACAO,
      ZDEPARA_SHABILITACAO.COD_SERIE_DE  AS CODGRADE,
	  ZDEPARA_SPLETIVO.CODIGO_DE		 AS CODANO,
	  ZDEPARA_SPLETIVO.DESCRICAO         AS ANO,
	  ZDEPARA_SCURSO.CURSO               AS NOME_CURSO,
	  ZDEPARA_SHABILITACAO.NOME_SERIE    AS NOME_MATRIZ,
	  ZDEPARA_SHABILITACAO.COD_SERIE_DE  AS CODIGO_SERIE,
	  ZDEPARA_SHABILITACAO.NOME_SERIE	 AS SERIE,
	  FILIAL_HABILIT.UNID_CODUNI		 AS CODFILIAL,
	  @CODCOLIGADA	                     AS CODCOLIGADA,
	  ''                                 AS CODCURSO_PARA,
	  ''                                 AS CODHABILITACAO_PARA,
      ''                                 AS CODIGO_PARA,
	  ''                                 AS PERIODO_GRADE
FROM 
	ZDEPARA_SHABILITACAO
	JOIN ZDEPARA_SCURSO
	  ON ZDEPARA_SCURSO.COD_CURSO_DE = ZDEPARA_SHABILITACAO.COD_CURSO
	CROSS APPLY
	  ZDEPARA_SPLETIVO
	JOIN (
		SELECT DISTINCT 
			BITB_ACOMPA_MAT.CUR_ID,
			ZDEPARA_SCURSO.CURSO,
			CASE 
				WHEN ZDEPARA_SCURSO.CURSO NOT LIKE 'EDUCA%' AND ZDEPARA_SCURSO.CURSO NOT LIKE 'ENSINO%' 
				THEN ZDEPARA_SCURSO.CURSO COLLATE Latin1_General_CI_AI
			ELSE
				CONCAT(
					BITB_ACOMPA_MAT.TUR_FASE,
					'º',
					SUBSTRING(BITB_ACOMPA_MAT.TUR_DESCRI, LEN(BITB_ACOMPA_MAT.TUR_DESCRI) - CHARINDEX('-', REVERSE(BITB_ACOMPA_MAT.TUR_DESCRI)) -1 , 1)
				) END AS NOME_SERIE,
			BITB_ACOMPA_MAT.TUR_FASE,
			BITB_ACOMPA_MAT.UNID_CODUNI
		FROM BITB_ACOMPA_MAT
		JOIN ZDEPARA_SCURSO
		  ON ZDEPARA_SCURSO.COD_CURSO_DE = BITB_ACOMPA_MAT.CUR_ID
	) FILIAL_HABILIT
	  ON FILIAL_HABILIT.CUR_ID = ZDEPARA_SCURSO.COD_CURSO_DE
	  AND FILIAL_HABILIT.NOME_SERIE = ZDEPARA_SHABILITACAO.NOME_SERIE
	  AND FILIAL_HABILIT.TUR_FASE = ZDEPARA_SHABILITACAO.COD_SERIE_DE
GROUP BY
	ZDEPARA_SCURSO.COD_CURSO_DE,
	ZDEPARA_SHABILITACAO.COD_SERIE_DE,
	ZDEPARA_SPLETIVO.CODIGO_DE,
	ZDEPARA_SPLETIVO.DESCRICAO,
	ZDEPARA_SCURSO.CURSO,
	ZDEPARA_SHABILITACAO.NOME_SERIE,  
	ZDEPARA_SHABILITACAO.COD_SERIE_DE,
	FILIAL_HABILIT.UNID_CODUNI
	) AS DADOS
	LEFT JOIN (SELECT DISTINCT ING_CURID, ING_PELID FROM TB_INGRESSO) TB_INGRESSO
	  ON TB_INGRESSO.ING_CURID = DADOS.CODCURSO
	WHERE EXISTS (
	  SELECT 1 FROM TB_PERIODO_LETIVO WHERE PEL_PERID = TB_INGRESSO.ING_PELID
	)

SELECT * FROM ZDEPARA_SGRADE ;