IF OBJECT_ID('ZDEPARA_SINSTITUICAO') IS NOT NULL
   DROP TABLE ZDEPARA_SINSTITUICAO
;

SELECT DISTINCT 
      BITB_ACOMPA_MAT.UNID_CODUNI 		AS CODIGO,
	  BITB_ACOMPA_MAT.UNID_NOMFAN		AS NOMEFANTASIA, 
	  BITB_ACOMPA_MAT.UNID_NOMFAN		AS RAZAOSICIAL,
	  ''					         	AS CNPJ, 
	  ''                           		AS CODIGO_PARA
INTO ZDEPARA_SINSTITUICAO
  FROM BITB_ACOMPA_MAT

ORDER BY CODIGO DESC;

SELECT * FROM ZDEPARA_SINSTITUICAO ORDER BY CODIGO; 