IF OBJECT_ID('ZDEPARA_STIPOPARTICIPACAO') IS NOT NULL
   DROP TABLE ZDEPARA_STIPOPARTICIPACAO;

DECLARE @CODCOLIGADA INT
SET @CODCOLIGADA = 13

SELECT DISTINCT
	  TB_OCUPACAO_PROFISSIONAL.OCP_ID    	AS CODIGO,   
	  TB_OCUPACAO_PROFISSIONAL.OCP_DESCRI	AS DESCRICAO,
	  @CODCOLIGADA                      	AS CODCOLIGADA,
	  ''                      				AS CODIGO_PARA
INTO ZDEPARA_STIPOPARTICIPACAO
  FROM 
	  TB_OCUPACAO_PROFISSIONAL
  INNER JOIN TB_PESSOA
	ON TB_PESSOA.PES_OCPID = TB_OCUPACAO_PROFISSIONAL.OCP_ID
	AND TB_PESSOA.GRUPO_UNIDON = TB_OCUPACAO_PROFISSIONAL.GRUPO_UNIDON
	AND TB_PESSOA.UNIDON = TB_OCUPACAO_PROFISSIONAL.UNIDON
ORDER BY 
      TB_OCUPACAO_PROFISSIONAL.OCP_ID;


SELECT * FROM ZDEPARA_STIPOPARTICIPACAO;

