IF OBJECT_ID('ZDEPARA_SPREDIO') IS NOT NULL
   DROP TABLE ZDEPARA_SPREDIO;

DECLARE @CODCOLIGADA INT
SET @CODCOLIGADA = 13

SELECT 
	  ''					    AS CODIGO,
	  ''						AS DESCRICAO,
	  @CODCOLIGADA              AS CODCOLIGADA,
	  ''                        AS CODFILIAL_PARA,
	  ''                        AS CODIGO_PARA
INTO ZDEPARA_SPREDIO

SELECT * FROM ZDEPARA_SPREDIO ;