IF OBJECT_ID('ZDEPARA_SALA') IS NOT NULL
   DROP TABLE ZDEPARA_SALA
;

DECLARE @CODCOLIGADA INT
SET @CODCOLIGADA = 13

SELECT 
	  TB_SALA.SAL_ID    	 AS CODIGO,
	  TB_SALA.UNIDON  		 AS UNIDADE,
	  TB_SALA.SAL_DESCRI	 AS DESCRICAO,
	  @CODCOLIGADA           AS CODCOLIGADA,
	  ''                     AS CODFILIAL_PARA,
	  ''                     AS PREDIO_PARA,
	  ''                     AS BLOCO_PARA,
	  ''                     AS CODIGO_PARA
	  INTO ZDEPARA_SALA
  FROM 
		TB_SALA
ORDER BY 
	  TB_SALA.UNIDON, TB_SALA.SAL_ID;

SELECT * FROM ZDEPARA_SALA ORDER BY CODFILIAL_PARA, CODIGO;