IF OBJECT_ID('ZDEPARA_SDISCGRADE') IS NOT NULL
	DROP TABLE ZDEPARA_SDISCGRADE
;

DECLARE @CODCOLIGADA AS INTEGER = 13
DECLARE @ANOLETIVO AS INTEGER = 2026

SELECT DISTINCT
	ZDEPARA_SHABILITACAO.COD_SERIE_DE												AS CODIGO,
	(
		SELECT TOP 1 ZDEPARA_SINSTITUICAO.NOMEFANTASIA
		FROM TB_TURMA
		INNER JOIN TB_PERIODO_LETIVO ON TB_PERIODO_LETIVO.PEL_PERID = TB_TURMA.TUR_PERID
		LEFT JOIN ZDEPARA_SINSTITUICAO ON ZDEPARA_SINSTITUICAO.CODIGO = TB_TURMA.UNIDON
		WHERE TUR_CURID = ZDEPARA_SCURSO.COD_CURSO_DE 
		  AND TB_PERIODO_LETIVO.PEL_ANOREF = @ANOLETIVO
		  AND TUR_FASE = ZDEPARA_SHABILITACAO.COD_SERIE_DE
	)																				AS INSTITUICAO,
	ZDEPARA_SCURSO.COD_CURSO_DE														AS COD_CURSO,
	ZDEPARA_SCURSO.CURSO															AS NOME_CURSO,
	ZDEPARA_SHABILITACAO.COD_SERIE_DE												AS COD_MATRIZ,
	ZDEPARA_SHABILITACAO.NOME_SERIE													AS NOME_MATRIZ,
	ZDEPARA_SHABILITACAO.COD_SERIE_DE												AS COD_SERIE,
	ZDEPARA_SHABILITACAO.NOME_SERIE													AS NOME_SERIE,
	ZDEPARA_SPLETIVO.DESCRICAO														AS ANO,
	TB_TURMA_DISCIP.TDI_DISCID														AS DISCIPLINA,
	TB_DISCIPLINA.DIS_DESDIS														AS NOME,
	@CODCOLIGADA																	AS CODCOLIGADA,
	''																				AS CODCURSO_PARA,
	''																				AS CODHABILITACAO_PARA,
	''																				AS CODGRADE_PARA,
	''																				AS CODPERIODO_PARA,
	''																				AS CODDISC_PARA,
	''																				AS CODIDHABILITACAO_PARA
	INTO ZDEPARA_SDISCGRADE
FROM 
	ZDEPARA_SHABILITACAO
LEFT JOIN ZDEPARA_SCURSO
	ON ZDEPARA_SCURSO.COD_CURSO_DE = ZDEPARA_SHABILITACAO.COD_CURSO
LEFT JOIN (
	SELECT TB_TURMA.*
	FROM TB_TURMA
	INNER JOIN TB_PERIODO_LETIVO
		ON TB_PERIODO_LETIVO.PEL_PERID = TB_TURMA.TUR_PERID
	WHERE TB_PERIODO_LETIVO.PEL_ANOREF = @ANOLETIVO
	) TURMA
	ON TURMA.TUR_CURID = ZDEPARA_SCURSO.COD_CURSO_DE
LEFT JOIN TB_TURMA_DISCIP
	ON TB_TURMA_DISCIP.TDI_TURID = TURMA.TUR_ID
	AND TB_TURMA_DISCIP.GRUPO_UNIDON = TURMA.GRUPO_UNIDON
	AND TB_TURMA_DISCIP.UNIDON = TURMA.UNIDON

INNER JOIN TB_DISCIPLINA
	ON TB_DISCIPLINA.DIS_DISID = TB_TURMA_DISCIP.TDI_DISCID

CROSS APPLY ZDEPARA_SPLETIVO;

SELECT * FROM ZDEPARA_SDISCGRADE ;
