IF OBJECT_ID('ZDEPARA_SHABILITACAOFILIAL') IS NOT NULL
	DROP TABLE ZDEPARA_SHABILITACAOFILIAL
;

DECLARE @ANOLETIVO AS INT, @CODCOLIGADA AS INT

SET @ANOLETIVO = 2026
SET @CODCOLIGADA = 13

SELECT DISTINCT
	CODIGO,
	COD_CURSO,
	NOME_CURSO,
	COD_MATRIZ,
	NOME_MATRIZ,
	COD_SERIE,
	NOME_SERIE,
	ANO,
	COD_TURNO,
	NOME_TURNO,
	CODCOLIGADA,
	CODFILIAL,
	'' AS CODFILIAL_PARA,
	'' AS CODCURSO_PARA,
	'' AS CODHABILITACAO_PARA,
	'' AS CODGRADE_PARA,
	'' AS CODTURNO_PARA,
	'' AS NIVELENSINO,
	'' AS CODIGO_PARA
	INTO ZDEPARA_SHABILITACAOFILIAL
FROM (
	SELECT DISTINCT
		ZDEPARA_SHABILITACAO.COD_SERIE_DE			AS CODIGO,
		ZDEPARA_SCURSO.COD_CURSO_DE					AS COD_CURSO,
		ZDEPARA_SCURSO.CURSO						AS NOME_CURSO,
		ZDEPARA_SHABILITACAO.COD_SERIE_DE			AS COD_MATRIZ,
		ZDEPARA_SHABILITACAO.NOME_SERIE				AS NOME_MATRIZ,
		ZDEPARA_SHABILITACAO.COD_SERIE_DE			AS COD_SERIE,
		ZDEPARA_SHABILITACAO.NOME_SERIE				AS NOME_SERIE,
		TB_PERIODO_LETIVO.PEL_DESCRI				AS ANO,
		TB_TURMA.TUR_TURNO							AS COD_TURNO,
		CASE
			WHEN TB_TURMA.TUR_TURNO = 'I' THEN 'INTEGRAL'
			WHEN TB_TURMA.TUR_TURNO = 'M' THEN 'MATUTINO'
			WHEN TB_TURMA.TUR_TURNO = 'V' THEN 'VESPERTINO'
		END											AS NOME_TURNO,
		@CODCOLIGADA								AS CODCOLIGADA,
		TB_TURMA.UNIDON								AS CODFILIAL,
		REPLACE(ZDEPARA_SHABILITACAO.NOME_SERIE,'º','') AS CODTURMAAUX
	FROM 
		ZDEPARA_SHABILITACAO
	LEFT JOIN ZDEPARA_SCURSO
		ON ZDEPARA_SCURSO.COD_CURSO_DE = ZDEPARA_SHABILITACAO.COD_CURSO
	LEFT JOIN TB_TURMA
		ON TB_TURMA.TUR_CURID = ZDEPARA_SHABILITACAO.COD_CURSO
	LEFT JOIN TB_PERIODO_LETIVO
		ON TB_PERIODO_LETIVO.PEL_PERID = TB_TURMA.TUR_PERID
	WHERE TB_PERIODO_LETIVO.PEL_ANOREF = @ANOLETIVO
) DADOS

	INNER JOIN (
		SELECT DISTINCT 
			REPLACE(ZDEPARA_SHABILITACAO.NOME_SERIE,'º','') AS CODSERIEDE,
			TB_TURMA.*
		FROM TB_TURMA
		LEFT JOIN TB_PERIODO_LETIVO
			ON TB_PERIODO_LETIVO.PEL_PERID = TB_TURMA.TUR_PERID
		LEFT JOIN (SELECT DISTINCT COD_CURSO, NOME_SERIE, DESCRICAO FROM ZDEPARA_SHABILITACAO) ZDEPARA_SHABILITACAO
			ON ZDEPARA_SHABILITACAO.COD_CURSO = TB_TURMA.TUR_CURID
			AND ZDEPARA_SHABILITACAO.DESCRICAO COLLATE Latin1_General_CI_AI = TB_TURMA.TUR_DESCRI
		WHERE TB_PERIODO_LETIVO.PEL_ANOREF = @ANOLETIVO
	) TURMA_LETIVO
	ON TURMA_LETIVO.TUR_CURID = DADOS.COD_CURSO
	AND TURMA_LETIVO.UNIDON = DADOS.CODFILIAL
	AND TURMA_LETIVO.TUR_TURNO = DADOS.COD_TURNO
	AND TURMA_LETIVO.CODSERIEDE = DADOS.CODTURMAAUX
ORDER BY 1, 2, 3, 5 DESC;

SELECT * FROM ZDEPARA_SHABILITACAOFILIAL ;