IF OBJECT_ID('ZDEPARA_STATUS') IS NOT NULL
    DROP TABLE ZDEPARA_STATUS
;

DECLARE @CODCOLIGADA INT
SET @CODCOLIGADA = 13

SELECT
    ROW_NUMBER() OVER (ORDER BY DADOS.CODFILIAL, DADOS.DESCRICAO) AS CODIGO,
    DADOS.*
    INTO ZDEPARA_STATUS
FROM (
    SELECT DISTINCT
        TB_INGRESSO.ING_STATUS AS DESCRICAO,
        @CODCOLIGADA AS CODCOLIGADA,
        TB_INGRESSO.UNIDON AS CODFILIAL,
        '' AS CODFILIAL_PARA,
        '' AS NIVELENSINO,
        '' AS CODIGO_PARA,
        '' AS DESCRICAO_PARA
    FROM TB_INGRESSO
) DADOS;

SELECT * FROM ZDEPARA_STATUS ;