IF OBJECT_ID('ZDEPARA_STATUSDISC') IS NOT NULL
   DROP TABLE ZDEPARA_STATUSDISC
;

DECLARE @CODCOLIGADA INT
SET @CODCOLIGADA = 13

SELECT DISTINCT
    TB_SITUACAO_RESULTADO.SRD_ID AS CODIGO,
    TB_SITUACAO_RESULTADO.SRD_DESRES AS DESCRICAO,
    @CODCOLIGADA AS CODCOLIGADA,
    CAST(TB_SITUACAO_RESULTADO.UNIDON AS VARCHAR(2)) AS CODFILIAL,
    '' AS NIVELENSINO,
    '' AS CODIGO_PARA,
    '' AS DESCRICAO_PARA
INTO ZDEPARA_STATUSDISC
FROM
    TB_SITUACAO_RESULTADO
ORDER BY 4, 1 ASC

SELECT * FROM ZDEPARA_STATUSDISC ORDER BY 4, 1 ASC;