IF OBJECT_ID('ZDEPARA_RESULTADO_HISTORICO') IS NOT NULL
   DROP TABLE ZDEPARA_RESULTADO_HISTORICO;

DECLARE @CODCOLIGADA INT
SET @CODCOLIGADA = 13

SELECT
	TB_SITUACAO_RESULTADO.SRD_DESRES AS RESULTADO,
	COUNT(TB_INGRESSO.ING_ID) AS QTD_REGISTROS,
	@CODCOLIGADA AS CODCOLIGADA,
	'' AS [CONSIDERAR__SIM_NAO],
	'' AS NIVEL_ENSINO,
	'' AS CODSITUACAO,
	'' AS DESCRICAO_PARA
     INTO ZDEPARA_RESULTADO_HISTORICO
FROM TB_RESULTADO_FASE
JOIN TB_PERIODO_LETIVO
  ON TB_PERIODO_LETIVO.PEL_PERID = TB_RESULTADO_FASE.REF_PERID
JOIN TB_SITUACAO_RESULTADO
  ON TB_SITUACAO_RESULTADO.SRD_ID = TB_RESULTADO_FASE.REF_RESID
JOIN TB_INGRESSO
  ON TB_INGRESSO.ING_ID = TB_RESULTADO_FASE.REF_INGID
GROUP BY TB_SITUACAO_RESULTADO.SRD_DESRES

SELECT * FROM ZDEPARA_RESULTADO_HISTORICO ;
