-- ZDEPARA_TURMAS COM IDHABILITACAOFILIAL CORRIGIDO

WITH IDHABILITACAOFILIAL AS (
    SELECT DISTINCT
        ZDEPARA_SHABILITACAOFILIAL.CODCOLIGADA,
        ZDEPARA_SHABILITACAOFILIAL.CODFILIAL_PARA,
        ZDEPARA_SHABILITACAOFILIAL.CODCURSO_PARA,
        ZDEPARA_SHABILITACAOFILIAL.CODHABILITACAO_PARA,
        ZDEPARA_SHABILITACAOFILIAL.CODGRADE_PARA,
        ZDEPARA_SHABILITACAOFILIAL.CODTURNO_PARA,
        ZDEPARA_SHABILITACAOFILIAL.NIVELENSINO,
        ZDEPARA_SHABILITACAOFILIAL.CODIGO_PARA
    FROM ZDEPARA_SHABILITACAOFILIAL
    JOIN ZDEPARA_TURMAS
        ON ZDEPARA_TURMAS.CODCOLIGADA
            = ZDEPARA_SHABILITACAOFILIAL.CODCOLIGADA 
        AND ZDEPARA_TURMAS.FILIAL_PARA
            = ZDEPARA_SHABILITACAOFILIAL.CODFILIAL_PARA
        AND ZDEPARA_TURMAS.CODCURSO_PARA
            = ZDEPARA_SHABILITACAOFILIAL.CODCURSO_PARA
        AND ZDEPARA_TURMAS.CODHABILITACAO_PARA
            = ZDEPARA_SHABILITACAOFILIAL.CODHABILITACAO_PARA
        AND ZDEPARA_TURMAS.CODGRADE_PARA
            = ZDEPARA_SHABILITACAOFILIAL.CODGRADE_PARA
        AND ZDEPARA_TURMAS.CODTURNO_PARA
            = ZDEPARA_SHABILITACAOFILIAL.CODTURNO_PARA
        AND ZDEPARA_TURMAS.NIVEL_ENSINO
            = ZDEPARA_SHABILITACAOFILIAL.NIVELENSINO
)

UPDATE T
SET T.IDHABILITACAOFILIAL_PARA = I.CODIGO_PARA

FROM ZDEPARA_TURMAS AS T

INNER JOIN IDHABILITACAOFILIAL AS I
    ON I.CODCOLIGADA = T.CODCOLIGADA
    AND I.CODFILIAL_PARA = T.FILIAL_PARA
    AND I.CODCURSO_PARA = T.CODCURSO_PARA
    AND I.CODHABILITACAO_PARA = T.CODHABILITACAO_PARA
    AND I.CODGRADE_PARA = T.CODGRADE_PARA
    AND I.CODTURNO_PARA = T.CODTURNO_PARA
    AND I.NIVELENSINO = T.NIVEL_ENSINO

WHERE I.CODIGO_PARA IS NOT NULL;