----------------------------------------------------------------------------------------------------      
-- Script:					COPIAR TABELAS BASE DE DADOS FIREBIRD PARA SQL
-- Última Alteração:		14/08/2024     
-- Versão:					1 
-- Origem:					FORTES
-- Autor Alteração:			Rafael Stroppa
----------------------------------------------------------------------------------------------------

USE ZMIGRA_GREENLIFE;

--NECESSÁRIO CRIAR LINKED SERVER PARA CONEXÃO COM FIREBIRD

DECLARE @NOMELINKEDSERVER VARCHAR(30) = 'GREENLIFE'

IF OBJECT_ID ('EVE') IS NOT NULL DROP TABLE EVE;
IF OBJECT_ID ('EPG') IS NOT NULL DROP TABLE EPG;
IF OBJECT_ID ('SEP') IS NOT NULL DROP TABLE SEP;
IF OBJECT_ID ('DEP') IS NOT NULL DROP TABLE DEP;
IF OBJECT_ID ('CAR') IS NOT NULL DROP TABLE CAR;
IF OBJECT_ID ('CBA') IS NOT NULL DROP TABLE CBA;
IF OBJECT_ID ('EMP') IS NOT NULL DROP TABLE EMP;
IF OBJECT_ID ('SIN') IS NOT NULL DROP TABLE SIN;
IF OBJECT_ID ('AVI') IS NOT NULL DROP TABLE AVI;
IF OBJECT_ID ('PAE') IS NOT NULL DROP TABLE PAE;
IF OBJECT_ID ('PVE') IS NOT NULL DROP TABLE PVE;
IF OBJECT_ID ('AGE') IS NOT NULL DROP TABLE AGE;
IF OBJECT_ID ('MUN') IS NOT NULL DROP TABLE MUN;
IF OBJECT_ID ('UFD') IS NOT NULL DROP TABLE UFD;
IF OBJECT_ID ('BAN') IS NOT NULL DROP TABLE BAN;
IF OBJECT_ID ('DRM') IS NOT NULL DROP TABLE DRM;
IF OBJECT_ID ('EBC') IS NOT NULL DROP TABLE EBC;
IF OBJECT_ID ('EED') IS NOT NULL DROP TABLE EED;
IF OBJECT_ID ('EFP') IS NOT NULL DROP TABLE EFP;
IF OBJECT_ID ('EPR') IS NOT NULL DROP TABLE EPR;
IF OBJECT_ID ('ERF') IS NOT NULL DROP TABLE ERF;
IF OBJECT_ID ('EST') IS NOT NULL DROP TABLE EST;
IF OBJECT_ID ('FOL') IS NOT NULL DROP TABLE FOL;
IF OBJECT_ID ('FPG') IS NOT NULL DROP TABLE FPG;
IF OBJECT_ID ('GPS') IS NOT NULL DROP TABLE GPS;
IF OBJECT_ID ('HOR') IS NOT NULL DROP TABLE HOR;
IF OBJECT_ID ('LOT') IS NOT NULL DROP TABLE LOT;
IF OBJECT_ID ('TLI') IS NOT NULL DROP TABLE TLI;
IF OBJECT_ID ('LIC') IS NOT NULL DROP TABLE LIC;
IF OBJECT_ID ('REC') IS NOT NULL DROP TABLE REC;
IF OBJECT_ID ('EFO') IS NOT NULL DROP TABLE EFO;
IF OBJECT_ID ('TRC') IS NOT NULL DROP TABLE TRC;
IF OBJECT_ID ('TFO') IS NOT NULL DROP TABLE TFO;
IF OBJECT_ID ('VID') IS NOT NULL DROP TABLE VID;
IF OBJECT_ID ('TB_MOT_DES') IS NOT NULL DROP TABLE TB_MOT_DES;
IF OBJECT_ID ('PAF') IS NOT NULL DROP TABLE PAF;
IF OBJECT_ID ('FER') IS NOT NULL DROP TABLE FER;
IF OBJECT_ID ('IND') IS NOT NULL DROP TABLE IND;
IF OBJECT_ID ('EPC') IS NOT NULL DROP TABLE EPC;
IF OBJECT_ID ('ASO') IS NOT NULL DROP TABLE ASO;
IF OBJECT_ID ('ESO') IS NOT NULL DROP TABLE ESO;
IF OBJECT_ID ('PRS') IS NOT NULL DROP TABLE PRS;

EXEC ('SELECT * INTO EVE FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM EVE'')')
EXEC ('SELECT * INTO EPG FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM EPG'')')
EXEC ('SELECT * INTO SEP FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM SEP'')')
EXEC ('SELECT * INTO DEP FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM DEP'')')
EXEC ('SELECT * INTO CAR FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM CAR'')')
EXEC ('SELECT * INTO CBA FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM CBA'')')
EXEC ('SELECT * INTO EMP FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM EMP'')')
EXEC ('SELECT * INTO SIN FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM SIN'')')
EXEC ('SELECT * INTO AVI FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM AVI'')')
EXEC ('SELECT * INTO PAE FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM PAE'')')
EXEC ('SELECT * INTO PVE FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM PVE'')')
EXEC ('SELECT * INTO AGE FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM AGE'')')
EXEC ('SELECT * INTO MUN FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM MUN'')')
EXEC ('SELECT * INTO UFD FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM UFD'')')
EXEC ('SELECT * INTO BAN FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM BAN'')')
EXEC ('SELECT * INTO DRM FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM DRM'')')
EXEC ('SELECT * INTO EBC FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM EBC'')')
EXEC ('SELECT * INTO EED FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM EED'')')
EXEC ('SELECT * INTO EFP FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM EFP'')')
EXEC ('SELECT * INTO EPR FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM EPR'')')
EXEC ('SELECT * INTO ERF FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM ERF'')')
EXEC ('SELECT * INTO EST FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM EST'')')
EXEC ('SELECT * INTO FOL FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM FOL'')')
EXEC ('SELECT * INTO FPG FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM FPG'')')
EXEC ('SELECT * INTO GPS FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM GPS'')')
EXEC ('SELECT * INTO HOR FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM HOR'')')
EXEC ('SELECT * INTO LOT FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM LOT'')')
EXEC ('SELECT * INTO TLI FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM TLI'')')
EXEC ('SELECT * INTO LIC FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM LIC'')')
EXEC ('SELECT * INTO REC FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM REC'')')
EXEC ('SELECT * INTO EFO FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM EFO'')')
EXEC ('SELECT * INTO TRC FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM TRC'')')
EXEC ('SELECT * INTO TFO FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM TFO'')')
EXEC ('SELECT * INTO VID FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM VID'')')
EXEC ('SELECT * INTO TB_MOT_DES FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM TB_MOT_DES'')')
EXEC ('SELECT * INTO PAF FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM PAF'')')
EXEC ('SELECT * INTO FER FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM FER'')')
EXEC ('SELECT * INTO IND FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM IND'')')
EXEC ('SELECT * INTO EPC FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM EPC'')')
EXEC ('SELECT * INTO ASO FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM ASO'')')
EXEC ('SELECT * INTO ESO FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM ESO'')')
EXEC ('SELECT * INTO PRS FROM OPENQUERY (' + @NOMELINKEDSERVER + ',''SELECT * FROM PRS'')')
