----------------------------------------------------------------------------------------------------      
-- Script:					ZFERIAS
-- �ltima Altera��o:		14/08/2024     
-- Vers�o:					1 
-- Origem:					FORTES
-- Autor Altera��o:			Rafael Stroppa
----------------------------------------------------------------------------------------------------

IF OBJECT_ID('ZFERIAS') IS NOT NULL
   DROP TABLE ZFERIAS;

SELECT PAE.EMP_CODIGO,
       PAE.EPG_CODIGO,
	   PAF.FER_EFO_FOL_SEQ AS FOL_SEQ,
	   PAE.DTINICIAL,
	   PAE.DTFINAL,
	   PAE.DIASDIREITO,
	   PAE.DIASGOZADOS,
	   FER.DTGOZOINICIAL,
	   FER.DTGOZOFINAL,
	   SUBSTRING(CONVERT(VARCHAR,FER.DTGOZOINICIAL,112),1,6) AS ANOMESGOZO,
	   CASE WHEN DATEDIFF(MONTH,FER.DTGOZOINICIAL,FER.DTGOZOFINAL) = 0 THEN DATEDIFF(DAY,FER.DTGOZOINICIAL,FER.DTGOZOFINAL) + 1
			WHEN DATEDIFF(MONTH,FER.DTGOZOINICIAL,FER.DTGOZOFINAL) > 0 THEN DATEDIFF(DAY,FER.DTGOZOINICIAL,DATEADD(DAY,-1,CAST(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,FER.DTGOZOINICIAL),120),1,8) + '01' AS DATE)))
	   END AS DIAS_MES1,
	   CASE WHEN DATEDIFF(MONTH,FER.DTGOZOINICIAL,FER.DTGOZOFINAL) = 0 THEN 0
			WHEN DATEDIFF(MONTH,FER.DTGOZOINICIAL,FER.DTGOZOFINAL) > 0 THEN DATEDIFF(DAY,DATEADD(DAY,-1,CAST(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,FER.DTGOZOINICIAL),120),1,8) + '01' AS DATE)), DATEADD(DAY,1,FER.DTGOZOFINAL))
	   END AS DIAS_MES2,
	   FER.DTRETORNO,
	   FOL.DTCALCULO,
	   PAF.FALTAS,
	   FER.DIASABONO,
	   SUM(CASE WHEN EVE.INFPROVDESC = 1 THEN CAST(EFP.VALOR AS DECIMAL(10,2)) END) AS PROVENTOS,
	   SUM(CASE WHEN EVE.INFPROVDESC = 2 THEN CAST(EFP.VALOR AS DECIMAL(10,2)) END) AS DESCONTOS,
	   SUM(CASE WHEN EVE.INFPROVDESC = 1 THEN CAST(EFP.VALOR AS DECIMAL(10,2))
	            WHEN EVE.InfProvDesc = 2 THEN CAST(EFP.VALOR AS DECIMAL(10,2)) * (-1)
			    WHEN EVE.InfProvDesc = 0 THEN 0
		    END) AS LIQUIDO_FERIAS 
  INTO ZFERIAS
  FROM PAE 
       INNER JOIN ZDEPARA_PFUNC
	           ON ZDEPARA_PFUNC.EMP_CODIGO = PAE.EMP_CODIGO
			  AND ZDEPARA_PFUNC.EPG_CODIGO = PAE.EPG_CODIGO
	   INNER JOIN PAF 
			 INNER JOIN FER 
			 		    INNER JOIN EFO 
						 		   INNER JOIN FOL 
									  ON FOL.EMP_CODIGO = EFO.EMP_CODIGO
									 AND FOL.SEQ        = EFO.FOL_SEQ
										     INNER JOIN EFP 
										           INNER JOIN EVE 
													  ON EVE.EMP_CODIGO = EFP.EMP_CODIGO
												     AND EVE.CODIGO     = EFP.EVE_CODIGO
											  ON EFP.EMP_CODIGO = EFO.EMP_CODIGO
											 AND EFP.EFO_EPG_CODIGO = EFO.EPG_CODIGO
											 AND EFP.EFO_FOL_SEQ    = EFO.FOL_SEQ
									 ON EFO.EMP_CODIGO = FER.EMP_CODIGO
									AND EFO.EPG_CODIGO = FER.EFO_EPG_CODIGO
									AND EFO.FOL_SEQ    = FER.EFO_FOL_SEQ
						  ON FER.EMP_CODIGO     = PAF.FER_EMP_CODIGO
						 AND FER.EFO_EPG_CODIGO = PAF.FER_EFO_EPG_CODIGO
						 AND FER.EFO_FOL_SEQ    = PAF.FER_EFO_FOL_SEQ
			   ON PAF.PAE_EMP_CODIGO = PAE.EMP_CODIGO
			  AND PAF.PAE_EPG_CODIGO = PAE.EPG_CODIGO
			  AND PAF.PAE_DTINICIAL  = PAE.DTINICIAL
 WHERE FOL.FOLHA = 4 -- FERIAS 
   --AND FOL.ENCERRADA = 'S' 
   AND PAE.DTFINAL IS NOT NULL --PARTICULARIDADE DO PROJETO BOA LOCACAO

 GROUP BY PAE.EMP_CODIGO,
          PAE.EPG_CODIGO,
	      PAE.DTINICIAL,
	      PAE.DTFINAL,
	      PAE.DIASDIREITO,
	      PAE.DIASGOZADOS,
	      FER.DTGOZOINICIAL,
	      FER.DTGOZOFINAL,
	      FER.DTRETORNO,
	      FOL.DTCALCULO,
	      PAF.FALTAS,
	      FER.DIASABONO,
	      PAF.FER_EFO_FOL_SEQ