----------------------------------------------------------------------------------------------------      
-- Script:					ZMIGRA_PFHSTSIT
-- �ltima Altera��o:		14/08/2024     
-- Vers�o:					1 
-- Origem:					FORTES
-- Autor Altera��o:			Rafael Stroppa
----------------------------------------------------------------------------------------------------

IF OBJECT_ID('ZMIGRA_PFHSTSIT') IS NOT NULL 
   DROP TABLE ZMIGRA_PFHSTSIT;

SELECT DADOS.CODCOLIGADA, --N�O SER� USADO NO LAYOUT
	   
	   DADOS.CHAPA,
       DADOS.DATAMUDANCA,
       DADOS.MOTIVO,
       DADOS.NOVASITUACAO
  INTO ZMIGRA_PFHSTSIT
  FROM (

-- INICIO DE AFASTAMENTOS
SELECT ZDEPARA_PFUNC.CODCOLIGADA,
       ZDEPARA_PFUNC.CODSITUACAO,
       ZDEPARA_PFUNC.CHAPA,
       CAST(LIC.DTINICIAL AS DATE) AS DATA,
       REPLACE(CONVERT(VARCHAR,LIC.DTINICIAL,103),'/','') + ' 00:00:00' AS DATAMUDANCA,
	   ZDEPARA_SITUACAO.CODMOTIVO_PARA AS MOTIVO,
	   ZDEPARA_SITUACAO.CODSITUACAO_PARA AS NOVASITUACAO 
  FROM LIC
       INNER JOIN ZDEPARA_PFUNC 
               ON ZDEPARA_PFUNC.EMP_CODIGO = LIC.EMP_CODIGO
              AND ZDEPARA_PFUNC.EPG_CODIGO = LIC.EPG_CODIGO
	   INNER JOIN ZDEPARA_SITUACAO
	           ON ZDEPARA_SITUACAO.CODIGO_DE = LIC.TLI_CODIGO
 UNION
 
 -- RETORNO DE AFASTAMENTOS
SELECT ZDEPARA_PFUNC.CODCOLIGADA,
       ZDEPARA_PFUNC.CODSITUACAO,
       ZDEPARA_PFUNC.CHAPA,
       CAST(LIC.DTFINAL AS DATE) AS DATA,
       REPLACE(CONVERT(VARCHAR,LIC.DTFINAL,103),'/','') + ' 00:01:00' AS DATAMUDANCA,
	   ZDEPARA_SITUACAO.CODMOTIVO_RETORNO_PARA AS MOTIVO,
	   ZDEPARA_SITUACAO.CODSITUACAO_RETORNO_PARA AS NOVASITUACAO 
  FROM LIC
       INNER JOIN ZDEPARA_PFUNC 
               ON ZDEPARA_PFUNC.EMP_CODIGO = LIC.EMP_CODIGO
              AND ZDEPARA_PFUNC.EPG_CODIGO = LIC.EPG_CODIGO
	   INNER JOIN ZDEPARA_SITUACAO
	           ON ZDEPARA_SITUACAO.CODIGO_DE = LIC.TLI_CODIGO

UNION

--ADMISS�O
SELECT ZDEPARA_PFUNC.CODCOLIGADA,
       ZDEPARA_PFUNC.CODSITUACAO,
       ZDEPARA_PFUNC.CHAPA,
	   ZDEPARA_PFUNC.DATAADMISSAO AS DATA,
	   REPLACE(CONVERT(VARCHAR,ZDEPARA_PFUNC.DATAADMISSAO,103),'/','') + ' 00:00:00' AS DATAMUDANCA,
	   '01' AS MOTIVO,
	   'A' AS NOVASITUACAO
  FROM ZDEPARA_PFUNC

UNION
  
--DEMISS�O
SELECT ZDEPARA_PFUNC.CODCOLIGADA,
	   ZDEPARA_PFUNC.CODSITUACAO,
       ZDEPARA_PFUNC.CHAPA,
	   ZDEPARA_PFUNC.DATADEMISSAO AS DATA,
	   REPLACE(CONVERT(VARCHAR,ZDEPARA_PFUNC.DATADEMISSAO,103),'/','') + ' 00:00:00' AS DATAMUDANCA,
	   '08' AS MOTIVO,
	   'D' AS NOVASITUACAO
  FROM ZDEPARA_PFUNC
 WHERE ZDEPARA_PFUNC.CODSITUACAO = 'D'

       ) DADOS 

 WHERE DADOS.DATAMUDANCA IS NOT NULL 
  AND DADOS.MOTIVO IS NOT NULL --PARTICULARIDADE DO PROJETO BOA LOCACAO