----------------------------------------------------------------------------------------------------      
-- Script:					ZFICHA
-- �ltima Altera��o:		14/08/2024     
-- Vers�o:					1 
-- Origem:					FORTES
-- Autor Altera��o:			Rafael Stroppa
----------------------------------------------------------------------------------------------------

IF OBJECT_ID('ZFICHA') IS NOT NULL
   DROP TABLE ZFICHA;

SELECT EFP.EMP_CODIGO,
       EFO.FOL_SEQ,
       CASE WHEN FOL.FOLHA IN (3,6,9,11,17,18,20) AND FOL.DTREFERENCIA IS NOT NULL THEN YEAR(FOL.DTREFERENCIA)
	        WHEN FPG.ANOMES IS NOT NULL THEN SUBSTRING(FPG.ANOMES,1,4) 
	        --WHEN FPG.ANOMES IS NULL AND CHARINDEX('/',REPLACE(EPC.COMENTARIO,' ','')) > 0 THEN SUBSTRING(REPLACE(EPC.COMENTARIO,' ',''), CHARINDEX('/',REPLACE(EPC.COMENTARIO,' ','')) + 1, 4)
			ELSE YEAR(FOL.DTCALCULO)
	   END AS ANOCOMP,
	   CASE WHEN FOL.FOLHA IN (3,6,9,11,17,18,20) AND FOL.DTREFERENCIA IS NOT NULL THEN MONTH(FOL.DTREFERENCIA)
	        WHEN FPG.ANOMES IS NOT NULL THEN SUBSTRING(FPG.ANOMES,5,2) 
	        /*WHEN FPG.ANOMES IS NULL AND CHARINDEX('/',REPLACE(EPC.COMENTARIO,' ','')) > 0 
			 AND ISNUMERIC(SUBSTRING(REPLACE(EPC.COMENTARIO,' ',''), CHARINDEX('/',REPLACE(EPC.COMENTARIO,' ','')) -2, 2)) = 1
			THEN SUBSTRING(REPLACE(EPC.COMENTARIO,' ',''), CHARINDEX('/',REPLACE(EPC.COMENTARIO,' ','')) -2, 2)*/
			ELSE MONTH(FOL.DTCALCULO)
	   END AS MESCOMP,
	   ZDEPARA_PERIODO_FOLHA.NROPERIODO_PARA AS NROPERIODO,
	   FOL.FOLHA,
	   FPG.ANOMES,
	   EPC.COMENTARIO,
	   FOL.DTCALCULO AS DTPAGAMENTO,
	   FOL.DTREFERENCIA,
	   EFP.EFO_EPG_CODIGO AS EPG_CODIGO,
	   EFP.EVE_CODIGO,
	   EVE.NOME AS EVENTO,
	   CAST(REPLACE(EFP.REFERENCIA,',','.') AS NUMERIC(15,2)) AS REF,
	   --CAST(REPLACE(REPLACE(REPLACE(EFP.VALOR,'E',''),'-',''),',','.') AS NUMERIC(15,2)) AS VALOR,
	   TRY_CONVERT(DECIMAL(15,2), EFP.VALOR) AS VALOR,
	   ZDEPARA_PFUNC.DTTRANSFERENCIA
  INTO ZFICHA
  FROM EFP 
	   INNER JOIN ZDEPARA_PFUNC 
	           ON ZDEPARA_PFUNC.EMP_CODIGO = EFP.EMP_CODIGO
			  AND ZDEPARA_PFUNC.EPG_CODIGO = EFP.EFO_EPG_CODIGO
	   INNER JOIN EVE 
	           ON EVE.EMP_CODIGO = EFP.EMP_CODIGO
			  AND EVE.CODIGO     = EFP.EVE_CODIGO
	   INNER JOIN EFO
	              INNER JOIN FOL
							 LEFT  JOIN EPC
							         ON EPC.EMP_CODIGO = FOL.EMP_CODIGO
									AND EPC.ID         = FOL.EPC_ID
							 LEFT  JOIN FPG 
							         ON FPG.EMP_CODIGO = FOL.EMP_CODIGO
									AND FPG.FOL_SEQ    = FOL.SEQ
				          ON FOL.EMP_CODIGO = EFO.EMP_CODIGO
						 AND FOL.SEQ        = EFO.FOL_SEQ
	           ON EFO.EMP_CODIGO = EFP.EMP_CODIGO 
			  AND EFO.EPG_CODIGO = EFP.EFO_EPG_CODIGO
			  AND EFO.FOL_SEQ    = EFP.EFO_FOL_SEQ
	   INNER JOIN ZDEPARA_PERIODO_FOLHA
	           ON ZDEPARA_PERIODO_FOLHA.CODIGO_PERIODO_DE = FOL.FOLHA
  WHERE ZDEPARA_PERIODO_FOLHA.NROPERIODO_PARA LIKE '%[0-9]%'
    --AND FOL.ENCERRADA = 'S'
	AND FOL.FOL_SEQ_PAI IS NULL