----------------------------------------------------------------------------------------------------      
-- Script:					ZMIGRA_PFFINANC (Ficha Financeira)
-- Última Alteração:		14/08/2024     
-- Versão:					1 
-- Origem:					FORTES
-- Autor Alteração:			Rafael Stroppa
----------------------------------------------------------------------------------------------------

IF OBJECT_ID ('ZMIGRA_PFFINANC') IS NOT NULL
   DROP TABLE ZMIGRA_PFFINANC;

DECLARE @ANOMESCOMP VARCHAR(6) = '202608' --#Ver: AAAAMM

SELECT  DISTINCT 

        DADOS.CODCOLIGADA, --NÃO SERÁ USADO NO LAYOUT 

        DADOS.CHAPA,
		DADOS.ANOCOMP AS "Ano de Competência",
		DADOS.MESCOMP AS "Mês de Competência",
		CAST(DADOS.NROPERIODO AS INT) AS "Número do Período",	
		DADOS.CODEVENTO AS "Código do Evento",	
		DADOS.DTPAGTO AS "Data de Pagamento",	
		DADOS.HORA AS "Hora",	
		DADOS.REF AS "Referência",
		DADOS.VALOR AS "Valor",	
		DADOS.VALORORIGINAL AS "Valor original"	,
		DADOS.VERBAFERIAS AS "Indica o recálculo do evento de férias",
		DADOS.ORIGEMMOV AS "Origem do Movimento"
	INTO ZMIGRA_PFFINANC
	FROM (

--FÉRIAS TOTAL OU PRIMEIRO MÊS

SELECT ZDEPARA_PFUNC.CODCOLIGADA, --NÃO SERÁ USADO NO LAYOUT
	   ZDEPARA_PFUNC.CHAPA,
	   CASE WHEN SUM(FERIAS.DIAS_MES1) IS NOT NULL THEN RIGHT(MAX(FERIAS.[Data de início das férias]),4) 
	        ELSE ZFICHA.ANOCOMP
	   END AS ANOCOMP,
	   CAST(CASE WHEN SUM(FERIAS.DIAS_MES1) IS NOT NULL THEN SUBSTRING(MAX(FERIAS.[Data de início das férias]),3,2) 
   	             ELSE ZFICHA.MESCOMP
	   END AS INT) AS MESCOMP,
	   ZFICHA.NROPERIODO,
	   CASE WHEN ZFICHA.FOLHA  = 4 AND ZDEPARA_EVENTOS.CODIGO_PARA = '0003' THEN '0098'
	        WHEN ZFICHA.FOLHA  = 4 AND ZDEPARA_EVENTOS.CODIGO_PARA = '0004' THEN '0030' 
	        ELSE ISNULL(ZDEPARA_EVENTOS.CODIGO_PARA,ZDEPARA_EVENTOS.CODIGO_PARA_FICHA_FERIAS_MES1)
	   END AS CODEVENTO,
	   CASE WHEN SUM(FERIAS.DIAS_MES1) IS NOT NULL THEN REPLACE(CONVERT(VARCHAR,MAX(FERIAS.[Data de início das férias]),103),'/','') 
			ELSE REPLACE(CONVERT(VARCHAR,ZFICHA.DTPAGAMENTO,103),'/','') 
	   END AS DTPAGTO,
	   CASE WHEN SUM(ZFICHA.REF) = 0 THEN ' ' 
	        WHEN ZDEPARA_EVENTOS.CODIGO_PARA IN ('0041','0042','0076','0077') THEN ' '
			WHEN ZFICHA.FOLHA  = 4 AND ZDEPARA_EVENTOS.CODIGO_PARA = '0003' THEN ' ' 
            ELSE RIGHT('000' + REPLACE(CAST(CAST(SUM(ZFICHA.REF) AS NUMERIC(15,2)) AS VARCHAR(25)),'.',':'),6)
        END AS HORA, 
	   CASE WHEN SUM(ISNULL(FERIAS.DIAS_MES1,0)) > 0 AND SUM(ISNULL(FERIAS.DIAS_MES2,0)) >= 0 AND ZDEPARA_EVENTOS.TIPO = 'P-PROVENTO'
			THEN REPLACE(CAST(CAST(SUM(FERIAS.DIAS_MES1) AS NUMERIC(15,2)) AS VARCHAR(20)),'.',',')
			ELSE REPLACE(CAST(CAST(SUM(COALESCE(ZFICHA.REF,0)) AS NUMERIC(15,2)) AS VARCHAR(20)),'.',',')
		END AS REF,
	   CASE WHEN SUM(ISNULL(FERIAS.DIAS_MES1,0)) > 0 AND SUM(ISNULL(FERIAS.DIAS_MES2,0)) > 0 AND ZDEPARA_EVENTOS.TIPO = 'P-PROVENTO'
			THEN REPLACE(CAST(CAST((SUM(ZFICHA.VALOR) / SUM(FERIAS.DIASDIREITO)) * SUM(FERIAS.DIAS_MES1) AS NUMERIC(15,2)) AS VARCHAR(20)),'.',',')
			ELSE REPLACE(CAST(CAST(SUM(ZFICHA.VALOR) AS NUMERIC(15,2)) AS VARCHAR(20)),'.',',') 
		END AS VALOR,
	   CASE WHEN SUM(ISNULL(FERIAS.DIAS_MES1,0)) > 0 AND SUM(ISNULL(FERIAS.DIAS_MES2,0)) > 0 AND ZDEPARA_EVENTOS.TIPO = 'P-PROVENTO'
			THEN REPLACE(CAST(CAST((SUM(ZFICHA.VALOR) / SUM(FERIAS.DIASDIREITO)) * SUM(FERIAS.DIAS_MES1) AS NUMERIC(15,2)) AS VARCHAR(20)),'.',',')
			ELSE REPLACE(CAST(CAST(SUM(ZFICHA.VALOR) AS NUMERIC(15,2)) AS VARCHAR(20)),'.',',') 
	   END AS VALORORIGINAL,
	   0 AS VERBAFERIAS,
	   0 AS ORIGEMMOV
  FROM ZFICHA 
       INNER JOIN ZDEPARA_PFUNC
               ON ZDEPARA_PFUNC.EMP_CODIGO = ZFICHA.EMP_CODIGO
              AND ZDEPARA_PFUNC.EPG_CODIGO = ZFICHA.EPG_CODIGO
	   INNER JOIN ZDEPARA_EVENTOS
               ON ZDEPARA_EVENTOS.EMPRESA_DE = ZFICHA.EMP_CODIGO
			  AND ZDEPARA_EVENTOS.CODIGO_DE  = RIGHT('0000' + ZFICHA.EVE_CODIGO, 4)
	   LEFT  JOIN ( SELECT PAE.EMP_CODIGO,
						   ZDEPARA_PFUNC.CHAPA,    
                           MAX(FOL.SEQ) AS SEQ,
                    	   CASE WHEN AVG(CAST(PAE.DiasDireito AS DECIMAL(15,2)))  = 0 THEN 1 ELSE AVG(CAST(PAE.DiasDireito AS DECIMAL(15,2))) END AS DIASDIREITO,
                    	   DATEDIFF(DAY,FER.DTGOZOINICIAL,FER.DTGOZOFINAL) + 1 AS DIAS_GOZADOS,
                    	   DATEDIFF(MONTH,FER.DTGOZOINICIAL,FER.DTGOZOFINAL) + 1 AS MESES,
						   CASE WHEN DATEDIFF(MONTH,FER.DTGOZOINICIAL,FER.DTGOZOFINAL) + 1 = 2 
                    	        THEN DATEDIFF(DAY,FER.DTGOZOINICIAL,DATEADD(DAY,-1,CAST(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,FER.DTGOZOINICIAL),120),1,8) + '01' AS DATE)))
                    			ELSE DATEDIFF(DAY,FER.DTGOZOINICIAL, FER.DTGOZOFINAL) + 1
                    		END AS DIAS_MES1,
						   CASE WHEN DATEDIFF(MONTH,FER.DTGOZOINICIAL,FER.DTGOZOFINAL) + 1 = 2
                    	        THEN DAY(FER.DTGOZOFINAL) + 1
                    			ELSE 0
                    		END AS DIAS_MES2,
						   REPLACE(CONVERT(VARCHAR,PAE.DTFINAL,103),'/','') AS "Data final do período aquisitivo",    
                           REPLACE(CONVERT(VARCHAR,FOL.DTCALCULO,103),'/','') AS "Data de pagamento das férias",    
                           REPLACE(CONVERT(VARCHAR,FER.DTGOZOINICIAL,103),'/','') AS "Data de início das férias",    
                           REPLACE(CONVERT(VARCHAR,FER.DTGOZOFINAL,103),'/','') AS "Data de fim das férias",    
                           REPLACE(CONVERT(VARCHAR,DATEADD(MONTH,-1,FER.DTGOZOINICIAL),103),'/','') AS "Data de aviso das férias",    
                           SUM(CAST(FER.DIASABONO AS DECIMAL(15,2))) AS "Número de dias de abono pecuniário",      
                           SUM(CAST(PAF.FALTAS AS DECIMAL(15,2))) AS "Faltas"
					  FROM PAE 
						   INNER JOIN ZDEPARA_PFUNC   
                                   ON ZDEPARA_PFUNC.EMP_CODIGO = PAE.EMP_CODIGO  
                                  AND ZDEPARA_PFUNC.EPG_CODIGO = PAE.EPG_CODIGO
						  INNER JOIN PAF 
								   INNER JOIN FER 
											INNER JOIN EFO 
														INNER JOIN FOL 
                    										        ON FOL.EMP_CODIGO = EFO.EMP_CODIGO
                    											   AND FOL.SEQ        = EFO.FOL_SEQ
														ON EFO.EMP_CODIGO = FER.EMP_CODIGO
                    									AND EFO.EPG_CODIGO = FER.EFO_EPG_CODIGO
                    									AND EFO.FOL_SEQ    = FER.EFO_FOL_SEQ
											  ON FER.EMP_CODIGO     = PAF.FER_EMP_CODIGO
                    						 AND FER.EFO_EPG_CODIGO = PAF.FER_EFO_EPG_CODIGO
                    						 AND FER.EFO_FOL_SEQ    = PAF.FER_EFO_FOL_SEQ
								   ON PAF.PAE_EMP_CODIGO     = PAE.EMP_CODIGO
                    			  AND PAF.FER_EFO_EPG_CODIGO = PAE.EPG_CODIGO
                    			  AND PAF.PAE_DTINICIAL      = PAE.DTINICIAL
					   WHERE FOL.FOLHA = 4
                         --AND FOL.ENCERRADA = 'S'
                         AND (ZDEPARA_PFUNC.DATADEMISSAO IS NULL OR FOL.DTCALCULO <= ZDEPARA_PFUNC.DATADEMISSAO)
                       GROUP BY ZDEPARA_PFUNC.CHAPA,    
                                PAE.DTFINAL,
                    		    PAE.DTINICIAL,
								PAE.EMP_CODIGO,
                                FOL.DTCALCULO,
                                FER.DTGOZOINICIAL,
                                FER.DTGOZOFINAL
					    ) FERIAS 
	           ON FERIAS.CHAPA		= ZFICHA.EPG_CODIGO
			  AND FERIAS.SEQ		= ZFICHA.FOL_SEQ
			  AND FERIAS.EMP_CODIGO = ZFICHA.EMP_CODIGO
 GROUP BY ZDEPARA_PFUNC.CODCOLIGADA,
		  ZDEPARA_PFUNC.CHAPA,
          ZFICHA.ANOCOMP,
	      ZFICHA.MESCOMP,
	      ZFICHA.NROPERIODO,
	      ZDEPARA_PFUNC.CODCOLIGADA,
		  ZDEPARA_EVENTOS.CODIGO_PARA_FICHA_FERIAS_MES1,
		  ZDEPARA_EVENTOS.CODIGO_PARA,
	      ZFICHA.DTPAGAMENTO,
		  ZFICHA.FOLHA,
		  ZDEPARA_EVENTOS.TIPO

UNION

--FÉRIAS DO SEGUNDO MÊS

SELECT ZDEPARA_PFUNC.CODCOLIGADA, --NÃO SERÁ USADO NO LAYOUT
	   ZDEPARA_PFUNC.CHAPA,
	   CASE WHEN SUM(FERIAS.DIAS_MES1) IS NOT NULL THEN RIGHT(MAX(FERIAS.[Data de início das férias]),4)
	        ELSE ZFICHA.ANOCOMP
	   END AS ANOCOMP,
	   CASE WHEN SUM(FERIAS.DIAS_MES1) IS NOT NULL THEN SUBSTRING(MAX(FERIAS.[Data de início das férias]),3,2)
	        ELSE ZFICHA.MESCOMP
	   END AS MESCOMP,
	   ZFICHA.NROPERIODO,
	   CASE WHEN ZDEPARA_EVENTOS.CODIGO_PARA = '0041' THEN '0042' 
	        WHEN ZDEPARA_EVENTOS.CODIGO_PARA = '0076' THEN '0077' 
			ELSE ISNULL(ZDEPARA_EVENTOS.CODIGO_PARA,ZDEPARA_EVENTOS.CODIGO_PARA_FICHA_FERIAS_MES2)
	   END AS CODEVENTO,
	   CASE WHEN SUM(FERIAS.DIAS_MES1) IS NOT NULL THEN REPLACE(CONVERT(VARCHAR,MAX(FERIAS.[Data de início das férias]),103),'/','') 
			ELSE REPLACE(CONVERT(VARCHAR,ZFICHA.DTPAGAMENTO,103),'/','') 
	   END AS DTPAGTO,
	   CASE WHEN SUM(ZFICHA.REF) = 0 THEN ' ' 
	        WHEN ZFICHA.FOLHA = 4 AND ZDEPARA_EVENTOS.CODIGO_PARA = '0003' THEN ' ' 
			WHEN ZDEPARA_EVENTOS.CODIGO_PARA IN ('0041','0042','0076','0077') THEN ' '
            ELSE RIGHT('000' + REPLACE(CAST(CAST(SUM(ZFICHA.REF) AS NUMERIC(15,2)) AS VARCHAR(25)),'.',':'),6)
       END AS HORA,
	   CASE WHEN SUM(ISNULL(FERIAS.DIAS_MES1,0)) > 0 AND SUM(ISNULL(FERIAS.DIAS_MES2,0)) > 0 AND ZDEPARA_EVENTOS.TIPO = 'P-PROVENTO'
			THEN REPLACE(CAST(CAST(SUM(FERIAS.DIAS_MES2) AS NUMERIC(15,2)) AS VARCHAR(20)),'.',',')
			ELSE REPLACE(CAST(CAST(SUM(COALESCE(ZFICHA.REF,0)) AS NUMERIC(15,2)) AS VARCHAR(20)),'.',',')
	   END AS REF,
	   CASE WHEN SUM(ISNULL(FERIAS.DIAS_MES1,0)) > 0 AND SUM(ISNULL(FERIAS.DIAS_MES2,0)) > 0 AND ZDEPARA_EVENTOS.TIPO = 'P-PROVENTO'
			THEN REPLACE(CAST(CAST((SUM(ZFICHA.VALOR) / SUM(FERIAS.DIASDIREITO)) * SUM(FERIAS.DIAS_MES2) AS NUMERIC(15,2)) AS VARCHAR(20)),'.',',')
			ELSE REPLACE(CAST(CAST(SUM(ZFICHA.VALOR) AS NUMERIC(15,2)) AS VARCHAR(20)),'.',',') 
	   END AS VALOR,
	   CASE WHEN SUM(ISNULL(FERIAS.DIAS_MES1,0)) > 0 AND SUM(ISNULL(FERIAS.DIAS_MES2,0)) > 0 AND ZDEPARA_EVENTOS.TIPO = 'P-PROVENTO'
			THEN REPLACE(CAST(CAST((SUM(ZFICHA.VALOR) / SUM(FERIAS.DIASDIREITO)) * SUM(FERIAS.DIAS_MES2) AS NUMERIC(15,2)) AS VARCHAR(20)),'.',',')
			ELSE REPLACE(CAST(CAST(SUM(ZFICHA.VALOR) AS NUMERIC(15,2)) AS VARCHAR(20)),'.',',') 
	   END AS VALORORIGINAL,
	   0 AS VERBAFERIAS,
	   0 AS ORIGEMMOV
  FROM ZFICHA 
	   INNER JOIN ZDEPARA_PFUNC
               ON ZDEPARA_PFUNC.EMP_CODIGO = ZFICHA.EMP_CODIGO
              AND ZDEPARA_PFUNC.EPG_CODIGO = ZFICHA.EPG_CODIGO
	   INNER JOIN ZDEPARA_EVENTOS
               ON ZDEPARA_EVENTOS.EMPRESA_DE = ZFICHA.EMP_CODIGO
			  AND ZDEPARA_EVENTOS.CODIGO_DE  = RIGHT('0000' + ZFICHA.EVE_CODIGO, 4)
	   INNER JOIN ( SELECT PAE.EMP_CODIGO,
						   ZDEPARA_PFUNC.CHAPA,    
                           MAX(FOL.SEQ) AS SEQ,
                    	   CASE WHEN AVG(CAST(PAE.DiasDireito AS DECIMAL(15,2)))  = 0 THEN 1 ELSE AVG(CAST(PAE.DiasDireito AS DECIMAL(15,2))) END AS DIASDIREITO,
                    	   DATEDIFF(DAY,FER.DTGOZOINICIAL,FER.DTGOZOFINAL) + 1 AS DIAS_GOZADOS,
                    	   DATEDIFF(MONTH,FER.DTGOZOINICIAL,FER.DTGOZOFINAL) + 1 AS MESES,
						   CASE WHEN DATEDIFF(MONTH,FER.DTGOZOINICIAL,FER.DTGOZOFINAL) + 1 = 2 
                    	        THEN DATEDIFF(DAY,FER.DTGOZOINICIAL,DATEADD(DAY,-1,CAST(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,FER.DTGOZOINICIAL),120),1,8) + '01' AS DATE)))
                    			ELSE DATEDIFF(DAY,FER.DTGOZOINICIAL, FER.DTGOZOFINAL) + 1
                    	   END AS DIAS_MES1,
						   CASE WHEN DATEDIFF(MONTH,FER.DTGOZOINICIAL,FER.DTGOZOFINAL) + 1 = 2
                    	        THEN DAY(FER.DTGOZOFINAL) + 1
                    			ELSE 0
                    	   END AS DIAS_MES2,
						   REPLACE(CONVERT(VARCHAR,PAE.DTFINAL,103),'/','') AS "Data final do período aquisitivo",    
                           REPLACE(CONVERT(VARCHAR,FOL.DTCALCULO,103),'/','') AS "Data de pagamento das férias",    
                           REPLACE(CONVERT(VARCHAR,FER.DTGOZOINICIAL,103),'/','') AS "Data de início das férias",    
                           REPLACE(CONVERT(VARCHAR,FER.DTGOZOFINAL,103),'/','') AS "Data de fim das férias",    
                           REPLACE(CONVERT(VARCHAR,DATEADD(MONTH,-1,FER.DTGOZOINICIAL),103),'/','') AS "Data de aviso das férias",    
                           SUM(CAST(FER.DIASABONO AS DECIMAL(15,2))) AS "Número de dias de abono pecuniário",      
                           SUM(CAST(PAF.FALTAS AS DECIMAL(15,2))) AS "Faltas"
					  FROM PAE 
						   INNER JOIN ZDEPARA_PFUNC   
                                   ON ZDEPARA_PFUNC.EMP_CODIGO = PAE.EMP_CODIGO  
                                  AND ZDEPARA_PFUNC.EPG_CODIGO = PAE.EPG_CODIGO
						   INNER JOIN PAF 
									  INNER JOIN FER 
												 INNER JOIN EFO 
														   INNER JOIN FOL 
                    										        ON FOL.EMP_CODIGO = EFO.EMP_CODIGO
                    											   AND FOL.SEQ        = EFO.FOL_SEQ
														 ON EFO.EMP_CODIGO = FER.EMP_CODIGO
                    									AND EFO.EPG_CODIGO = FER.EFO_EPG_CODIGO
                    									AND EFO.FOL_SEQ    = FER.EFO_FOL_SEQ
											  ON FER.EMP_CODIGO     = PAF.FER_EMP_CODIGO
                    						 AND FER.EFO_EPG_CODIGO = PAF.FER_EFO_EPG_CODIGO
                    						 AND FER.EFO_FOL_SEQ    = PAF.FER_EFO_FOL_SEQ
								   ON PAF.PAE_EMP_CODIGO     = PAE.EMP_CODIGO
                    			  AND PAF.FER_EFO_EPG_CODIGO = PAE.EPG_CODIGO
                    			  AND PAF.PAE_DTINICIAL      = PAE.DTINICIAL
					 WHERE FOL.FOLHA = 4
                       --AND FOL.ENCERRADA = 'S'
                       AND (ZDEPARA_PFUNC.DATADEMISSAO IS NULL OR FOL.DTCALCULO <= ZDEPARA_PFUNC.DATADEMISSAO)
					 GROUP BY ZDEPARA_PFUNC.CHAPA,    
                              PAE.DTFINAL,
							  PAE.EMP_CODIGO,
                    		  PAE.DTINICIAL,
                              FOL.DTCALCULO,
                              FER.DTGOZOINICIAL,
                              FER.DTGOZOFINAL
				  ) FERIAS 
	           ON FERIAS.CHAPA		= ZFICHA.EPG_CODIGO
			  AND FERIAS.SEQ		= ZFICHA.FOL_SEQ
			  AND FERIAS.EMP_CODIGO = ZFICHA.EMP_CODIGO
			  AND ZFICHA.EVE_CODIGO IN ('110','111')
			  AND FERIAS.DIAS_MES2	> 0
 GROUP BY ZDEPARA_PFUNC.CODCOLIGADA,
		  ZDEPARA_PFUNC.CHAPA,
          ZFICHA.ANOCOMP,
	      ZFICHA.MESCOMP,
	      ZFICHA.NROPERIODO,
	      ZDEPARA_PFUNC.CODCOLIGADA,
		  ZDEPARA_EVENTOS.CODIGO_PARA_FICHA_FERIAS_MES2,
		  ZDEPARA_EVENTOS.CODIGO_PARA,
	      ZFICHA.DTPAGAMENTO,
		  ZFICHA.FOLHA,
		  ZDEPARA_EVENTOS.TIPO

UNION

--DESCONTO FINAL DE FÉRIAS 
SELECT ZDEPARA_PFUNC.CODCOLIGADA, --NÃO SERÁ USADO NO LAYOUT
       ZDEPARA_PFUNC.CHAPA,
	   CASE WHEN SUM(FERIAS.DIAS_MES1) IS NOT NULL THEN RIGHT(MAX(FERIAS.[Data de início das férias]),4) 
	        ELSE ZFICHA.ANOCOMP
	   END AS ANOCOMP,
	   CAST(CASE WHEN SUM(FERIAS.DIAS_MES1) IS NOT NULL THEN SUBSTRING(MAX(FERIAS.[Data de início das férias]),3,2) 
   	             ELSE ZFICHA.MESCOMP
	   END AS INT) AS MESCOMP,
	   ZFICHA.NROPERIODO,
	   '0043' AS CODEVENTO,
	   CASE WHEN SUM(FERIAS.DIAS_MES1) IS NOT NULL THEN REPLACE(CONVERT(VARCHAR,MAX(FERIAS.[Data de início das férias]),103),'/','') 
			ELSE REPLACE(CONVERT(VARCHAR,ZFICHA.DTPAGAMENTO,103),'/','') 
	   END AS DTPAGTO,
	   ' ' AS HORA,
	   '0,00' /*REPLACE(CAST(CAST(SUM(COALESCE(ZFICHA.REF,0)) AS NUMERIC(15,2)) AS VARCHAR(20)),'.',',')*/ AS REF,
	   REPLACE(CAST(CAST(SUM(CASE WHEN ZDEPARA_EVENTOS.TIPO = 'P-PROVENTO' THEN ZFICHA.VALOR 
	            WHEN ZDEPARA_EVENTOS.TIPO = 'D-DESCONTO' THEN ZFICHA.VALOR * (-1)
			    ELSE 0
		    END) AS NUMERIC(15,2)) AS VARCHAR(20)),'.',',') AS VALOR, 
	   REPLACE(CAST(CAST(SUM(CASE WHEN ZDEPARA_EVENTOS.TIPO = 'P-PROVENTO' THEN ZFICHA.VALOR 
	            WHEN ZDEPARA_EVENTOS.TIPO = 'D-DESCONTO' THEN ZFICHA.VALOR * (-1)
			    ELSE 0
		    END) AS NUMERIC(15,2)) AS VARCHAR(20)),'.',',') AS VALORORIGINAL,
	   0 AS VERBAFERIAS,
	   0 AS ORIGEMMOV
  FROM ZFICHA 
	   INNER JOIN ZDEPARA_PFUNC
               ON ZDEPARA_PFUNC.EMP_CODIGO = ZFICHA.EMP_CODIGO
              AND ZDEPARA_PFUNC.EPG_CODIGO = ZFICHA.EPG_CODIGO
	   INNER JOIN ZDEPARA_EVENTOS
               ON ZDEPARA_EVENTOS.EMPRESA_DE = ZFICHA.EMP_CODIGO
			  AND ZDEPARA_EVENTOS.CODIGO_DE   = RIGHT('0000' + ZFICHA.EVE_CODIGO, 4)
	   LEFT  JOIN ( SELECT PAE.EMP_CODIGO,
						   ZDEPARA_PFUNC.CHAPA,    
                           MAX(FOL.SEQ) AS SEQ,
                    	   CASE WHEN AVG(CAST(PAE.DiasDireito AS DECIMAL(15,2)))  = 0 THEN 1 ELSE AVG(CAST(PAE.DiasDireito AS DECIMAL(15,2))) END AS DIASDIREITO,
                    	   DATEDIFF(DAY,FER.DTGOZOINICIAL,FER.DTGOZOFINAL) + 1 AS DIAS_GOZADOS,
                    	   DATEDIFF(MONTH,FER.DTGOZOINICIAL,FER.DTGOZOFINAL) + 1 AS MESES,
                    	   CASE WHEN DATEDIFF(MONTH,FER.DTGOZOINICIAL,FER.DTGOZOFINAL) + 1 = 2 
                    	        THEN DATEDIFF(DAY,FER.DTGOZOINICIAL,DATEADD(DAY,-1,CAST(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,FER.DTGOZOINICIAL),120),1,8) + '01' AS DATE)))
                    			ELSE DATEDIFF(DAY,FER.DTGOZOINICIAL, FER.DTGOZOFINAL) + 1
                    		END AS DIAS_MES1,
                    	   CASE WHEN DATEDIFF(MONTH,FER.DTGOZOINICIAL,FER.DTGOZOFINAL) + 1 = 2
                    	        THEN DAY(FER.DTGOZOFINAL) + 1
                    			ELSE 0
                    		END AS DIAS_MES2,
                           REPLACE(CONVERT(VARCHAR,PAE.DTFINAL,103),'/','') AS "Data final do período aquisitivo",    
                           REPLACE(CONVERT(VARCHAR,FOL.DTCALCULO,103),'/','') AS "Data de pagamento das férias",    
                           REPLACE(CONVERT(VARCHAR,FER.DTGOZOINICIAL,103),'/','') AS "Data de início das férias",    
                           REPLACE(CONVERT(VARCHAR,FER.DTGOZOFINAL,103),'/','') AS "Data de fim das férias",    
                           REPLACE(CONVERT(VARCHAR,DATEADD(MONTH,-1,FER.DTGOZOINICIAL),103),'/','') AS "Data de aviso das férias",    
                           SUM(CAST(FER.DIASABONO AS DECIMAL(15,2))) AS "Número de dias de abono pecuniário",      
                           SUM(CAST(PAF.FALTAS AS DECIMAL(15,2))) AS "Faltas"
                      FROM PAE 
						   INNER JOIN ZDEPARA_PFUNC   
                                   ON ZDEPARA_PFUNC.EMP_CODIGO = PAE.EMP_CODIGO  
                                  AND ZDEPARA_PFUNC.EPG_CODIGO = PAE.EPG_CODIGO
						   INNER JOIN PAF 
									  INNER JOIN FER 
												 INNER JOIN EFO 
															INNER JOIN FOL 
                    										        ON FOL.EMP_CODIGO = EFO.EMP_CODIGO
                    											   AND FOL.SEQ        = EFO.FOL_SEQ
														 ON EFO.EMP_CODIGO = FER.EMP_CODIGO
                    									AND EFO.EPG_CODIGO = FER.EFO_EPG_CODIGO
                    									AND EFO.FOL_SEQ    = FER.EFO_FOL_SEQ
											  ON FER.EMP_CODIGO     = PAF.FER_EMP_CODIGO
                    						 AND FER.EFO_EPG_CODIGO = PAF.FER_EFO_EPG_CODIGO
                    						 AND FER.EFO_FOL_SEQ    = PAF.FER_EFO_FOL_SEQ
								   ON PAF.PAE_EMP_CODIGO     = PAE.EMP_CODIGO
                    			  AND PAF.FER_EFO_EPG_CODIGO = PAE.EPG_CODIGO
                    			  AND PAF.PAE_DTINICIAL      = PAE.DTINICIAL
					 WHERE FOL.FOLHA = 4
                       --AND FOL.ENCERRADA = 'S'
                       AND (ZDEPARA_PFUNC.DATADEMISSAO IS NULL OR FOL.DTCALCULO <= ZDEPARA_PFUNC.DATADEMISSAO)
					 GROUP BY ZDEPARA_PFUNC.CHAPA,    
                              PAE.DTFINAL,
                    		  PAE.DTINICIAL,
							  PAE.EMP_CODIGO,
                              FOL.DTCALCULO,
                              FER.DTGOZOINICIAL,
                              FER.DTGOZOFINAL
				  ) FERIAS 
	           ON FERIAS.CHAPA = ZFICHA.EPG_CODIGO
			  AND FERIAS.SEQ   = ZFICHA.FOL_SEQ
			  AND FERIAS.EMP_CODIGO = ZFICHA.EMP_CODIGO
  WHERE ZFICHA.FOLHA = 4 
 GROUP BY ZDEPARA_PFUNC.CODCOLIGADA,
          ZDEPARA_PFUNC.CHAPA,
          ZFICHA.ANOCOMP,
	      ZFICHA.MESCOMP,
	      ZFICHA.NROPERIODO,
	      ZDEPARA_PFUNC.CODCOLIGADA,
	      ZFICHA.DTPAGAMENTO
	) DADOS

WHERE CAST(DADOS.ANOCOMP AS VARCHAR(4)) + RIGHT('00' + CAST(DADOS.MESCOMP AS VARCHAR(2)),2) < @ANOMESCOMP --#Ver
  AND DADOS.CODEVENTO LIKE '%[0-9]%'