SELECT '01-FUNCIONARIOS' AS DADO,
SUM(CASE WHEN CODCOLIGADA = '1' THEN 1 ELSE 0 END) AS COL1,
SUM(CASE WHEN CODCOLIGADA = '2' THEN 1 ELSE 0 END) AS COL2,
SUM(CASE WHEN CODCOLIGADA = '3' THEN 1 ELSE 0 END) AS COL3,
SUM(CASE WHEN CODCOLIGADA = '4' THEN 1 ELSE 0 END) AS COL4,
SUM(CASE WHEN CODCOLIGADA = '5' THEN 1 ELSE 0 END) AS COL5,
SUM(CASE WHEN CODCOLIGADA = '6' THEN 1 ELSE 0 END) AS COL6,
COUNT(*) AS TOTAL
FROM ZMIGRA_PFUNC
UNION

SELECT '02-DEPENDENTES' AS DADO,
SUM(CASE WHEN CODCOLIGADA = '1' THEN 1 ELSE 0 END) AS COL1,
SUM(CASE WHEN CODCOLIGADA = '2' THEN 1 ELSE 0 END) AS COL2,
SUM(CASE WHEN CODCOLIGADA = '3' THEN 1 ELSE 0 END) AS COL3,
SUM(CASE WHEN CODCOLIGADA = '4' THEN 1 ELSE 0 END) AS COL4,
SUM(CASE WHEN CODCOLIGADA = '5' THEN 1 ELSE 0 END) AS COL5,
SUM(CASE WHEN CODCOLIGADA = '6' THEN 1 ELSE 0 END) AS COL6,
COUNT(*) AS TOTAL
FROM ZMIGRA_PFDEPEND
UNION

SELECT '03-PERIODO AQUISITIVO DE FÉRIAS' AS DADO,
SUM(CASE WHEN CODCOLIGADA = '1' THEN 1 ELSE 0 END) AS COL1,
SUM(CASE WHEN CODCOLIGADA = '2' THEN 1 ELSE 0 END) AS COL2,
SUM(CASE WHEN CODCOLIGADA = '3' THEN 1 ELSE 0 END) AS COL3,
SUM(CASE WHEN CODCOLIGADA = '4' THEN 1 ELSE 0 END) AS COL4,
SUM(CASE WHEN CODCOLIGADA = '5' THEN 1 ELSE 0 END) AS COL5,
SUM(CASE WHEN CODCOLIGADA = '6' THEN 1 ELSE 0 END) AS COL6,
COUNT(*) AS TOTAL
FROM ZMIGRA_PFUFERIAS
UNION

SELECT '04-PERIODO DE GOZO DE FÉRIAS' AS DADO,
SUM(CASE WHEN CODCOLIGADA = '1' THEN 1 ELSE 0 END) AS COL1,
SUM(CASE WHEN CODCOLIGADA = '2' THEN 1 ELSE 0 END) AS COL2,
SUM(CASE WHEN CODCOLIGADA = '3' THEN 1 ELSE 0 END) AS COL3,
SUM(CASE WHEN CODCOLIGADA = '4' THEN 1 ELSE 0 END) AS COL4,
SUM(CASE WHEN CODCOLIGADA = '5' THEN 1 ELSE 0 END) AS COL5,
SUM(CASE WHEN CODCOLIGADA = '6' THEN 1 ELSE 0 END) AS COL6,
COUNT(*) AS TOTAL
FROM ZMIGRA_PFUFERIASPER
UNION

SELECT '05-RECIBO DE FÉRIAS' AS DADO,
SUM(CASE WHEN CODCOLIGADA = '1' THEN 1 ELSE 0 END) AS COL1,
SUM(CASE WHEN CODCOLIGADA = '2' THEN 1 ELSE 0 END) AS COL2,
SUM(CASE WHEN CODCOLIGADA = '3' THEN 1 ELSE 0 END) AS COL3,
SUM(CASE WHEN CODCOLIGADA = '4' THEN 1 ELSE 0 END) AS COL4,
SUM(CASE WHEN CODCOLIGADA = '5' THEN 1 ELSE 0 END) AS COL5,
SUM(CASE WHEN CODCOLIGADA = '6' THEN 1 ELSE 0 END) AS COL6,
COUNT(*) AS TOTAL
FROM ZMIGRA_PFUFERIASRECIBO
UNION

SELECT '06-VERBAS DE FÉRIAS' AS DADO,
SUM(CASE WHEN CODCOLIGADA = '1' THEN 1 ELSE 0 END) AS COL1,
SUM(CASE WHEN CODCOLIGADA = '2' THEN 1 ELSE 0 END) AS COL2,
SUM(CASE WHEN CODCOLIGADA = '3' THEN 1 ELSE 0 END) AS COL3,
SUM(CASE WHEN CODCOLIGADA = '4' THEN 1 ELSE 0 END) AS COL4,
SUM(CASE WHEN CODCOLIGADA = '5' THEN 1 ELSE 0 END) AS COL5,
SUM(CASE WHEN CODCOLIGADA = '6' THEN 1 ELSE 0 END) AS COL6,
COUNT(*) AS TOTAL
FROM ZMIGRA_PFUFERIASVERBAS
UNION

SELECT '07-HISTORICO SALARIAL' AS DADO,
SUM(CASE WHEN CODCOLIGADA = '1' THEN 1 ELSE 0 END) AS COL1,
SUM(CASE WHEN CODCOLIGADA = '2' THEN 1 ELSE 0 END) AS COL2,
SUM(CASE WHEN CODCOLIGADA = '3' THEN 1 ELSE 0 END) AS COL3,
SUM(CASE WHEN CODCOLIGADA = '4' THEN 1 ELSE 0 END) AS COL4,
SUM(CASE WHEN CODCOLIGADA = '5' THEN 1 ELSE 0 END) AS COL5,
SUM(CASE WHEN CODCOLIGADA = '6' THEN 1 ELSE 0 END) AS COL6,
COUNT(*) AS TOTAL
FROM ZMIGRA_PFHSTSAL
UNION

SELECT '08-HISTORICO DE SITUCAO' AS DADO,
SUM(CASE WHEN CODCOLIGADA = '1' THEN 1 ELSE 0 END) AS COL1,
SUM(CASE WHEN CODCOLIGADA = '2' THEN 1 ELSE 0 END) AS COL2,
SUM(CASE WHEN CODCOLIGADA = '3' THEN 1 ELSE 0 END) AS COL3,
SUM(CASE WHEN CODCOLIGADA = '4' THEN 1 ELSE 0 END) AS COL4,
SUM(CASE WHEN CODCOLIGADA = '5' THEN 1 ELSE 0 END) AS COL5,
SUM(CASE WHEN CODCOLIGADA = '6' THEN 1 ELSE 0 END) AS COL6,
COUNT(*) AS TOTAL
FROM ZMIGRA_PFHSTSIT
UNION

SELECT '09-HISTORICO DE CONTRIBUICAO SINDICAL' AS DADO,
SUM(CASE WHEN CODCOLIGADA = '1' THEN 1 ELSE 0 END) AS COL1,
SUM(CASE WHEN CODCOLIGADA = '2' THEN 1 ELSE 0 END) AS COL2,
SUM(CASE WHEN CODCOLIGADA = '3' THEN 1 ELSE 0 END) AS COL3,
SUM(CASE WHEN CODCOLIGADA = '4' THEN 1 ELSE 0 END) AS COL4,
SUM(CASE WHEN CODCOLIGADA = '5' THEN 1 ELSE 0 END) AS COL5,
SUM(CASE WHEN CODCOLIGADA = '6' THEN 1 ELSE 0 END) AS COL6,
COUNT(*) AS TOTAL
FROM ZMIGRA_PFHSTCSD
UNION

SELECT '10-HISTORICO DE NUMERO DE DEPENDENTES' AS DADO,
SUM(CASE WHEN CODCOLIGADA = '1' THEN 1 ELSE 0 END) AS COL1,
SUM(CASE WHEN CODCOLIGADA = '2' THEN 1 ELSE 0 END) AS COL2,
SUM(CASE WHEN CODCOLIGADA = '3' THEN 1 ELSE 0 END) AS COL3,
SUM(CASE WHEN CODCOLIGADA = '4' THEN 1 ELSE 0 END) AS COL4,
SUM(CASE WHEN CODCOLIGADA = '5' THEN 1 ELSE 0 END) AS COL5,
SUM(CASE WHEN CODCOLIGADA = '6' THEN 1 ELSE 0 END) AS COL6,
COUNT(*) AS TOTAL
FROM ZMIGRA_PFHSTNDEP
UNION

SELECT '11-HISTORICO DE FUNCAO' AS DADO,
SUM(CASE WHEN CODCOLIGADA = '1' THEN 1 ELSE 0 END) AS COL1,
SUM(CASE WHEN CODCOLIGADA = '2' THEN 1 ELSE 0 END) AS COL2,
SUM(CASE WHEN CODCOLIGADA = '3' THEN 1 ELSE 0 END) AS COL3,
SUM(CASE WHEN CODCOLIGADA = '4' THEN 1 ELSE 0 END) AS COL4,
SUM(CASE WHEN CODCOLIGADA = '5' THEN 1 ELSE 0 END) AS COL5,
SUM(CASE WHEN CODCOLIGADA = '6' THEN 1 ELSE 0 END) AS COL6,
COUNT(*) AS TOTAL
FROM ZMIGRA_PFHSTFCO
UNION

SELECT '12-HISTORICO DE AFASTAMENTO' AS DADO,
SUM(CASE WHEN CODCOLIGADA = '1' THEN 1 ELSE 0 END) AS COL1,
SUM(CASE WHEN CODCOLIGADA = '2' THEN 1 ELSE 0 END) AS COL2,
SUM(CASE WHEN CODCOLIGADA = '3' THEN 1 ELSE 0 END) AS COL3,
SUM(CASE WHEN CODCOLIGADA = '4' THEN 1 ELSE 0 END) AS COL4,
SUM(CASE WHEN CODCOLIGADA = '5' THEN 1 ELSE 0 END) AS COL5,
SUM(CASE WHEN CODCOLIGADA = '6' THEN 1 ELSE 0 END) AS COL6,
COUNT(*) AS TOTAL
FROM ZMIGRA_PFHSTAFT
UNION

SELECT '13-HISTORICO DE SECAO' AS DADO,
SUM(CASE WHEN CODCOLIGADA = '1' THEN 1 ELSE 0 END) AS COL1,
SUM(CASE WHEN CODCOLIGADA = '2' THEN 1 ELSE 0 END) AS COL2,
SUM(CASE WHEN CODCOLIGADA = '3' THEN 1 ELSE 0 END) AS COL3,
SUM(CASE WHEN CODCOLIGADA = '4' THEN 1 ELSE 0 END) AS COL4,
SUM(CASE WHEN CODCOLIGADA = '5' THEN 1 ELSE 0 END) AS COL5,
SUM(CASE WHEN CODCOLIGADA = '6' THEN 1 ELSE 0 END) AS COL6,
COUNT(*) AS TOTAL
FROM ZMIGRA_PFHSTSEC
UNION

SELECT '15-PERIODOS DE FICHA FINANCEIRA' AS DADO,
SUM(CASE WHEN CODCOLIGADA = '1' THEN 1 ELSE 0 END) AS COL1,
SUM(CASE WHEN CODCOLIGADA = '2' THEN 1 ELSE 0 END) AS COL2,
SUM(CASE WHEN CODCOLIGADA = '3' THEN 1 ELSE 0 END) AS COL3,
SUM(CASE WHEN CODCOLIGADA = '4' THEN 1 ELSE 0 END) AS COL4,
SUM(CASE WHEN CODCOLIGADA = '5' THEN 1 ELSE 0 END) AS COL5,
SUM(CASE WHEN CODCOLIGADA = '6' THEN 1 ELSE 0 END) AS COL6,
COUNT(*) AS TOTAL
FROM ZMIGRA_PFPERFF
UNION

SELECT '16-FICHA FINANCEIRA' AS DADO,
SUM(CASE WHEN CODCOLIGADA = '1' THEN 1 ELSE 0 END) AS COL1,
SUM(CASE WHEN CODCOLIGADA = '2' THEN 1 ELSE 0 END) AS COL2,
SUM(CASE WHEN CODCOLIGADA = '3' THEN 1 ELSE 0 END) AS COL3,
SUM(CASE WHEN CODCOLIGADA = '4' THEN 1 ELSE 0 END) AS COL4,
SUM(CASE WHEN CODCOLIGADA = '5' THEN 1 ELSE 0 END) AS COL5,
SUM(CASE WHEN CODCOLIGADA = '6' THEN 1 ELSE 0 END) AS COL6,
COUNT(*) AS TOTAL
FROM ZMIGRA_PFFINANC

ORDER BY 1