IF OBJECT_ID('ZMIGRA_NUMBANCO') IS NOT NULL
	DROP TABLE ZMIGRA_NUMBANCO;

SELECT DISTINCT 
	   CODIGO_BANCO_PARA,
	   'INSERT INTO GBANCO (NUMBANCO, NUMEROOFICIAL, NOME, NOMEREDUZIDO, ORGAOPUBLICO) VALUES (''' + CODIGO_BANCO_PARA + ''',''' + CODIGO_BANCO_PARA +''',''' + UPPER(NOME_BANCO_DE) + ''',''' + UPPER(NOME_BANCO_DE) + ''',0 );' AS COMANDO_INSERT
  INTO ZMIGRA_NUMBANCO
  FROM ZDEPARA_BANCO 
  WHERE CODIGO_BANCO_PARA IN ('012','275')
  ORDER BY CODIGO_BANCO_PARA

SELECT * FROM ZMIGRA_NUMBANCO ;