--VERIFICAÇÕES 

SELECT CODCOLIGADA, CHAPA, CODSITUACAO, COUNT(*) AS QTD FROM ZDEPARA_PFUNC GROUP BY CODCOLIGADA, CHAPA, CODSITUACAO HAVING COUNT(*) > 1 ORDER BY 1,2
SELECT * FROM ZDEPARA_PFUNC WHERE CODCOLIGADA IS NULL 
SELECT CODCOLIGADA, COUNT(*) AS QTD FROM ZDEPARA_PFUNC GROUP BY CODCOLIGADA ORDER BY CAST(CODCOLIGADA AS INT) 
SELECT CODSITUACAO, COUNT(*) AS QTD FROM ZDEPARA_PFUNC GROUP BY CODSITUACAO ORDER BY 1
SELECT * FROM ZDEPARA_PFUNC WHERE HST_SAL IS NULL OR HST_FCO IS NULL OR HST_SEC IS NULL OR HST_SIT IS NULL
SELECT * FROM ZDEPARA_PFUNC WHERE MOTIVO_SAL IS NULL OR MOTIVO_FCO IS NULL OR MOTIVO_SEC IS NULL OR MOTIVO_SIT IS NULL

--ATIVO OU INATIVO SEM DADO IMPORTANTE

SELECT A.ID + '-' + A.DADO AS DADO,
	   A.QTD_ATIVO,
	   BB.QTD_INATIVO, 
	   SUM(A.QTD_ATIVO + BB.QTD_INATIVO) AS QTD_TOTAL
 FROM (
		SELECT '1' AS ID, 'FUNCIONARIO SEM SECAO'			AS DADO, COUNT(*) AS QTD_ATIVO FROM ZDEPARA_PFUNC WHERE CODSITUACAO <> 'D' AND LOT_CODIGO IS NULL						UNION
		SELECT '2' AS ID, 'FUNCIONARIO SEM FUNCAO'			AS DADO, COUNT(*) AS QTD_ATIVO FROM ZDEPARA_PFUNC WHERE CODSITUACAO <> 'D' AND CAR_CODIGO IS NULL						UNION
		SELECT '3' AS ID, 'FUNCIONARIO SEM SINDICATO'		AS DADO, COUNT(*) AS QTD_ATIVO FROM ZDEPARA_PFUNC WHERE CODSITUACAO <> 'D' AND SIN_CODIGO IS NULL						UNION
		SELECT '4' AS ID, 'FUNCIONARIO SEM HORARIO'			AS DADO, COUNT(*) AS QTD_ATIVO FROM ZDEPARA_PFUNC WHERE CODSITUACAO <> 'D' AND HOR_CODIGO IS NULL						UNION
		SELECT '5' AS ID, 'FUNCIONARIO SEM BANCO/AGENCIA'	AS DADO, COUNT(*) AS QTD_ATIVO FROM ZDEPARA_PFUNC WHERE CODSITUACAO <> 'D' AND AGE_BAN_CODIGO IS NULL					UNION
		SELECT '6' AS ID, 'FUNCIONARIO SEM CPF'				AS DADO, COUNT(*) AS QTD_ATIVO FROM ZDEPARA_PFUNC WHERE CODSITUACAO <> 'D' AND CPF IS NULL OR CPF NOT LIKE '%[0-9]%'
		) A
  JOIN (
	    SELECT B.*
		  FROM (
				SELECT '1' AS ID, 'FUNCIONARIO SEM SECAO'			AS DADO, COUNT(*) AS QTD_INATIVO FROM ZDEPARA_PFUNC WHERE CODSITUACAO = 'D' AND LOT_CODIGO IS NULL						UNION
				SELECT '2' AS ID, 'FUNCIONARIO SEM FUNCAO'			AS DADO, COUNT(*) AS QTD_INATIVO FROM ZDEPARA_PFUNC WHERE CODSITUACAO = 'D' AND CAR_CODIGO IS NULL						UNION
				SELECT '3' AS ID, 'FUNCIONARIO SEM SINDICATO'		AS DADO, COUNT(*) AS QTD_INATIVO FROM ZDEPARA_PFUNC WHERE CODSITUACAO = 'D' AND SIN_CODIGO IS NULL						UNION
				SELECT '4' AS ID, 'FUNCIONARIO SEM HORARIO'			AS DADO, COUNT(*) AS QTD_INATIVO FROM ZDEPARA_PFUNC WHERE CODSITUACAO = 'D' AND HOR_CODIGO IS NULL						UNION
				SELECT '5' AS ID, 'FUNCIONARIO SEM BANCO/AGENCIA'	AS DADO, COUNT(*) AS QTD_INATIVO FROM ZDEPARA_PFUNC WHERE CODSITUACAO = 'D' AND AGE_BAN_CODIGO IS NULL					UNION
				SELECT '6' AS ID, 'FUNCIONARIO SEM CPF'				AS DADO, COUNT(*) AS QTD_INATIVO FROM ZDEPARA_PFUNC WHERE CODSITUACAO = 'D' AND CPF IS NULL OR CPF NOT LIKE '%[0-9]%'
				) B
			) BB
  ON A.ID = BB.ID
GROUP BY A.ID + '-' + A.DADO, A.QTD_ATIVO, BB.QTD_INATIVO

--DADOS PARA RELATÓRIO DE LOGS
SELECT '1-FUNCIONARIO SEM SECAO'			AS DADO, EMP_CODIGO, CHAPA, NOME, EPG_CODIGO, CODSITUACAO, LOT_CODIGO FROM ZDEPARA_PFUNC WHERE LOT_CODIGO IS NULL 

SELECT '2-FUNCIONARIO SEM FUNCAO'			AS DADO, EMP_CODIGO, CHAPA, NOME, EPG_CODIGO, CODSITUACAO, CAR_CODIGO FROM ZDEPARA_PFUNC WHERE CAR_CODIGO IS NULL 

SELECT '3-FUNCIONARIO SEM SINDICATO'		AS DADO, EMP_CODIGO, CHAPA, NOME, EPG_CODIGO, CODSITUACAO, SIN_CODIGO FROM ZDEPARA_PFUNC WHERE SIN_CODIGO IS NULL 

SELECT '4-FUNCIONARIO SEM HORARIO'			AS DADO, EMP_CODIGO, CHAPA, NOME, EPG_CODIGO, CODSITUACAO, HOR_CODIGO FROM ZDEPARA_PFUNC WHERE HOR_CODIGO IS NULL

SELECT '1-FUNCIONARIO SEM BANCO/AGENCIA'	AS DADO, EMP_CODIGO, CHAPA, NOME, EPG_CODIGO, CODSITUACAO, AGE_BAN_CODIGO FROM ZDEPARA_PFUNC WHERE AGE_BAN_CODIGO IS NULL

SELECT '1-FUNCIONARIO SEM CPF'				AS DADO, EMP_CODIGO, CHAPA, NOME, EPG_CODIGO, CODSITUACAO, CPF FROM ZDEPARA_PFUNC WHERE CPF IS NULL OR CPF NOT LIKE '%[0-9]%'

SELECT '1-FUNCIONARIO SEM NATURALIDADE'		AS DADO, Z.EMP_CODIGO, Z.CHAPA, Z.NOME, Z.EPG_CODIGO, Z.CODSITUACAO, X.MUN_UFD_SIGLA_NATURALIDADE, X.MUN_CODIGO_NATURALIDADE
 FROM ZDEPARA_PFUNC Z
 JOIN EPG X
   ON X.CODIGO = Z.EPG_CODIGO
 WHERE X.MUN_UFD_SIGLA_NATURALIDADE IS NULL 
	 OR X.MUN_CODIGO_NATURALIDADE IS NULL