IF OBJECT_ID('ZMIGRA_PFHSTFCO_DIF') IS NOT NULL
    DROP TABLE ZMIGRA_PFHSTFCO_DIF
;

SELECT
	CODCOLIGADA AS [CODCOLIGADA],
	CHAPA AS [CHAPA],
	[Data de Admissão] + ' 00:01:00' AS [Data da Mudança (ddmmaaaa hh:mm:ss)],
	'01' AS [Código do Motivo da Mud. De Função],
	[Código da Função] AS [Código da Função],
	NULL AS [Nível Salarial],
	NULL AS [Faixa Salarial],
	NULL AS [CAMPOEXTRA1]
    INTO ZMIGRA_PFHSTFCO_DIF
FROM ZMIGRA_PFUNC
WHERE CODCOLIGADA = 1 AND CHAPA IN (
'001101','002171','003388','003760','004086','004643','005890','006072'
) OR CODCOLIGADA = 2 AND CHAPA IN ('000007')
;

INSERT INTO ZMIGRA_PFHSTFCO
SELECT * FROM ZMIGRA_PFHSTFCO_DIF