--SELECT 'DROP TABLE ' + name + ';'
--  FROM sys.sysobjects
-- WHERE xtype = 'U'
--   AND NAME LIKE 'Z%'
-- ORDER BY NAME

/*
-- CONSULTA A BASE DE DADOS:
SELECT * FROM OPENQUERY(UNIVOX,'SELECT * FROM systable') WHERE  TABLE_TYPE = 'BASE' AND REMARKS LIKE '%DEPEN%'

SELECT TAB.TABLE_NAME,
       TAB.REMARKS,
	   TAB.TABLE_TYPE,
	   COLUMN_NAME
  FROM OPENQUERY(UNIVOX,'SELECT * FROM systable') TAB
       INNER JOIN OPENQUERY(UNIVOX,'SELECT * FROM syscolumn') COL
	           ON COL.TABLE_ID = TAB.TABLE_ID
 WHERE COL.COLUMN_NAME = 'I_CALCULOS'
 */

IF OBJECT_ID('FOEMPREGADOS') IS NOT NULL DROP TABLE FOEMPREGADOS 
SELECT * INTO FOEMPREGADOS FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOEMPREGADOS');

IF OBJECT_ID('FORESCISOES') IS NOT NULL DROP TABLE FORESCISOES 
SELECT * INTO FORESCISOES FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FORESCISOES');

IF OBJECT_ID('FOAFASTAMENTOS') IS NOT NULL DROP TABLE FOAFASTAMENTOS 
SELECT * INTO FOAFASTAMENTOS FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOAFASTAMENTOS');

IF OBJECT_ID('FOAFASTAMENTOS_TIPOS') IS NOT NULL DROP TABLE FOAFASTAMENTOS_TIPOS 
SELECT * INTO FOAFASTAMENTOS_TIPOS FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOAFASTAMENTOS_TIPOS');

IF OBJECT_ID('FOFILHOS') IS NOT NULL DROP TABLE FOFILHOS 
SELECT * INTO FOFILHOS FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.fofilhos');

IF OBJECT_ID('FOSINDICATOS') IS NOT NULL DROP TABLE FOSINDICATOS 
SELECT * INTO FOSINDICATOS FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.fosindicatos');

IF OBJECT_ID('FOCARGOS') IS NOT NULL DROP TABLE FOCARGOS 
SELECT * INTO FOCARGOS FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.focargos');

IF OBJECT_ID('FOTROCAS_CARGOS') IS NOT NULL DROP TABLE FOTROCAS_CARGOS 
SELECT * INTO FOTROCAS_CARGOS FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOTROCAS_CARGOS');

IF OBJECT_ID('FODEPTO') IS NOT NULL DROP TABLE FODEPTO 
SELECT * INTO FODEPTO FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FODEPTO');

IF OBJECT_ID('FOTROCAS_DEPTO') IS NOT NULL DROP TABLE FOTROCAS_DEPTO 
SELECT * INTO FOTROCAS_DEPTO FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOTROCAS_DEPTO');

IF OBJECT_ID('FOHORARIOS') IS NOT NULL DROP TABLE FOHORARIOS 
SELECT * INTO FOHORARIOS FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOHORARIOS');

IF OBJECT_ID('FOFERIAS_AQUISITIVOS') IS NOT NULL DROP TABLE FOFERIAS_AQUISITIVOS 
SELECT * INTO FOFERIAS_AQUISITIVOS FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOFERIAS_AQUISITIVOS');

IF OBJECT_ID('FOFERIAS_GOZO') IS NOT NULL DROP TABLE FOFERIAS_GOZO 
SELECT * INTO FOFERIAS_GOZO FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOFERIAS_GOZO');

IF OBJECT_ID('FOFERIAS_PROGRAMACAO') IS NOT NULL DROP TABLE FOFERIAS_PROGRAMACAO 
SELECT * INTO FOFERIAS_PROGRAMACAO FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOFERIAS_PROGRAMACAO');

IF OBJECT_ID('FOEVENTOS') IS NOT NULL DROP TABLE FOEVENTOS 
SELECT * INTO FOEVENTOS FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOEVENTOS');

IF OBJECT_ID('FOBANCOS') IS NOT NULL DROP TABLE FOBANCOS 
SELECT * INTO FOBANCOS FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOBANCOS');

IF OBJECT_ID('FOALTESAL') IS NOT NULL DROP TABLE FOALTESAL 
SELECT * INTO FOALTESAL FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.foaltesal');

IF OBJECT_ID('FOMOVTO') IS NOT NULL DROP TABLE FOMOVTO 
SELECT * INTO FOMOVTO FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOMOVTO');

IF OBJECT_ID('FOINSTITUICAO_ENSINO') IS NOT NULL DROP TABLE FOINSTITUICAO_ENSINO 
SELECT * INTO FOINSTITUICAO_ENSINO FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOINSTITUICAO_ENSINO');

IF OBJECT_ID('FOCOORDENADOR_ESTAGIO') IS NOT NULL DROP TABLE FOCOORDENADOR_ESTAGIO 
SELECT * INTO FOCOORDENADOR_ESTAGIO fROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOCOORDENADOR_ESTAGIO');

IF OBJECT_ID('GEMUNICIPIO') IS NOT NULL DROP TABLE GEMUNICIPIO
SELECT * INTO GEMUNICIPIO FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.gemunicipio');

IF OBJECT_ID('FOPROVISOES') IS NOT NULL DROP TABLE FOPROVISOES
SELECT * INTO FOPROVISOES FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOPROVISOES');

IF OBJECT_ID('FOJORNADAS') IS NOT NULL DROP TABLE FOJORNADAS
SELECT * INTO FOJORNADAS FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOJORNADAS');

IF OBJECT_ID('FOCCUSTOS') IS NOT NULL DROP TABLE FOCCUSTOS
SELECT * INTO FOCCUSTOS FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOCCUSTOS');

IF OBJECT_ID('FOTROCAS_CCUSTOS') IS NOT NULL DROP TABLE FOTROCAS_CCUSTOS
SELECT * INTO FOTROCAS_CCUSTOS FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOTROCAS_CCUSTOS');

--IF OBJECT_ID('GEEMPRE') IS NOT NULL DROP TABLE GEEMPRE
--SELECT * INTO GEEMPRE FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.GEEMPRE');

IF OBJECT_ID('FOSINDICATOS_EMPRESAS') IS NOT NULL DROP TABLE FOSINDICATOS_EMPRESAS
SELECT * INTO FOSINDICATOS_EMPRESAS FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOSINDICATOS_EMPRESAS');

IF OBJECT_ID('FOFILHOS_PLANO_SAUDE') IS NOT NULL DROP TABLE FOFILHOS_PLANO_SAUDE 
SELECT * INTO FOFILHOS_PLANO_SAUDE FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOFILHOS_PLANO_SAUDE');

IF OBJECT_ID ('GEEMPRE') IS NOT NULL
DROP TABLE GEEMPRE
GO

SELECT CODI_EMP,
	   NOME_EMP,
	   CGCE_EMP
 INTO GEEMPRE
 FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.GEEMPRE');

IF OBJECT_ID('FOMOVTOSERV') IS NOT NULL DROP TABLE FOMOVTOSERV
SELECT * INTO FOMOVTOSERV FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOMOVTOSERV');


IF OBJECT_ID('FORESCISOES') IS NOT NULL DROP TABLE FORESCISOES
SELECT * INTO FORESCISOES FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FORESCISOES');

IF OBJECT_ID('FOLANCTO') IS NOT NULL DROP TABLE FOLANCTO
SELECT * INTO FOLANCTO FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOLANCTO');

IF OBJECT_ID('FOBASES') IS NOT NULL DROP TABLE FOBASES
SELECT * INTO FOBASES FROM OPENQUERY(TVINTELIGENTE,'SELECT * FROM bethadba.FOBASES');

