IF OBJECT_ID('ZDEPARA_SINDICATOS') IS NOT NULL
   DROP TABLE ZDEPARA_SINDICATOS ;

SELECT DISTINCT 
	   EMP.Codigo AS EMPRESA_DE,
	   SIN.CODIGO AS CODIGO_DE,
	   SIN.NOME AS NOME_DE,
	   SIN.CNPJ AS CNPJ,
	   ZDEPARA_COLIGADAS.CODCOLIGADA AS COLIGADA_PARA,
	   CAST('' AS VARCHAR(10)) AS CODIGO_PARA
  INTO ZDEPARA_SINDICATOS
  FROM SIN
  JOIN SEP 
    ON SEP.SIN_CODIGO = SIN.CODIGO
  JOIN EMP
	ON EMP.Codigo = SEP.EMP_Codigo
  JOIN ZDEPARA_COLIGADAS
    ON SEP.EMP_CODIGO = ZDEPARA_COLIGADAS.EMPRESA_DE ;

SELECT * FROM ZDEPARA_SINDICATOS ;