IF OBJECT_ID ('ZDEPARA_SECOES') IS NOT NULL
	DROP TABLE ZDEPARA_SECOES ;

SELECT DISTINCT 
       SEP.EMP_CODIGO AS EMPRESA_DE,
       SEP.EST_CODIGO AS FILIAL_DE,
	   --EST.NOME AS ESTABELECIMENTO,
	   SEP.LOT_CODIGO AS CODIGO_DE,
	   LOT.NOME AS NOME_DE,
	   ZDEPARA_COLIGADAS.CODCOLIGADA AS COLIGADA_PARA,
	   CAST('' AS VARCHAR(30)) AS FILIAL_PARA,
	   CAST('' AS VARCHAR(30)) AS CODIGO_PARA
  INTO ZDEPARA_SECOES
  FROM SEP
  JOIN ZDEPARA_COLIGADAS
    ON SEP.EMP_CODIGO = ZDEPARA_COLIGADAS.EMPRESA_DE
  JOIN EST
    ON EST.EMP_CODIGO = SEP.EMP_CODIGO 
   AND EST.CODIGO     = SEP.EST_CODIGO 
  JOIN LOT
    ON LOT.EMP_CODIGO = SEP.EMP_CODIGO 
   AND LOT.CODIGO     = SEP.LOT_CODIGO
 ORDER BY COLIGADA_PARA ;

SELECT * FROM ZDEPARA_SECOES ;

