IF OBJECT_ID ('ZDEPARA_SITUACAO') IS NOT NULL
DROP TABLE ZDEPARA_SITUACAO ; 

SELECT TLI.CODIGO AS CODIGO_DE,
       TLI.NOME AS NOME_DE,
       CAST('' AS VARCHAR(5)) AS CODSITUACAO_PARA,
       CAST('' AS VARCHAR(5)) AS CODMOTIVO_PARA,
       CAST('' AS VARCHAR(5)) AS CODSITUACAO_RETORNO_PARA,
       CAST('' AS VARCHAR(5)) AS CODMOTIVO_RETORNO_PARA
       INTO ZDEPARA_SITUACAO
  FROM TLI
 WHERE EXISTS (SELECT 1 
                 FROM LIC
				 JOIN ZDEPARA_COLIGADAS  
				   ON LIC.EMP_CODIGO = ZDEPARA_COLIGADAS.EMPRESA_DE
				WHERE LIC.TLI_CODIGO = TLI.CODIGO)
 ORDER BY TLI.CODIGO ;

 SELECT * FROM ZDEPARA_SITUACAO ; 


