IF OBJECT_ID ('ZDEPARA_EVENTOS') IS NOT NULL
DROP TABLE ZDEPARA_EVENTOS ; 

SELECT EVE.EMP_CODIGO AS EMPRESA_DE,
       RIGHT('0000' + EVE.CODIGO,4) AS CODIGO_DE,
	   EVE.NOME AS NOME_DE,
	   CASE WHEN INFPROVDESC = 1 THEN 'P-PROVENTO'
	        WHEN INFPROVDESC = 2 THEN 'D-DESCONTO'
			WHEN INFPROVDESC = 0 THEN 'B-BASE'
		END AS TIPO_EVENTO,
	   ZDEPARA_COLIGADAS.CODCOLIGADA AS COLIGADA_PARA,
	   CAST(' ' AS VARCHAR(10)) AS CODIGO_PARA, 
	   '' AS NOME_RM,
	   CAST(' ' AS VARCHAR(10)) AS CODIGO_PARA_FICHA_MES1,
	   '' AS NOME_RM_1,
	   CAST(' ' AS VARCHAR(10)) AS CODIGO_PARA_FICHA_MES2,
	   '' AS NOME_RM_2,
	   CAST(' ' AS VARCHAR(10)) AS CODIGO_PARA_VERBAS_FERIAS,
	   '' AS NOME_RM_3
	   INTO ZDEPARA_EVENTOS
  FROM EVE
  JOIN ZDEPARA_COLIGADAS
    ON EVE.EMP_CODIGO = ZDEPARA_COLIGADAS.EMPRESA_DE
 WHERE EXISTS (SELECT 1 
                 FROM EFP
				WHERE EFP.EMP_CODIGO = EVE.EMP_CODIGO
				  AND EFP.EVE_CODIGO = EVE.CODIGO)
 ORDER BY COLIGADA_PARA, EVE.INFPROVDESC, EVE.NOME ;

 SELECT * FROM ZDEPARA_EVENTOS ;
