IF OBJECT_ID ('ZDEPARA_HORARIO') IS NOT NULL
DROP TABLE ZDEPARA_HORARIO ;

SELECT DISTINCT 
	   HOR.EMP_CODIGO AS EMPRESA_DE,
	   HOR.CODIGO AS CODIGO_DE,
	   HOR.NOME AS NOME_DE,
	   ZDEPARA_COLIGADAS.CODCOLIGADA AS COLIGADA_PARA,
	   '00001' AS CODIGO_PARA 
  INTO ZDEPARA_HORARIO
  FROM HOR
  JOIN ZDEPARA_COLIGADAS
    ON HOR.EMP_CODIGO = ZDEPARA_COLIGADAS.EMPRESA_DE
 WHERE EXISTS (SELECT 1
		         FROM SEP
		        WHERE SEP.EMP_CODIGO = HOR.EMP_CODIGO
		          AND SEP.HOR_CODIGO = HOR_CODIGO)
 ORDER BY COLIGADA_PARA ;

 SELECT * FROM ZDEPARA_HORARIO ;
