IF OBJECT_ID ('ZDEPARA_PERIODO_FOLHA') IS NOT NULL
DROP TABLE ZDEPARA_PERIODO_FOLHA ;

SELECT DISTINCT 
	   CODIGO AS CODIGO_PERIODO_DE,
       DESCRICAO AS TIPO_FOLHA_DE,
	   PREFIXOESOCIAL AS PREFIXO_ESOCIAL,
	   CASE WHEN CODIGO BETWEEN 14 AND 19 THEN 'IGNORAR' ELSE CAST(CODIGO AS VARCHAR(2)) END AS NROPERIODO_PARA
  INTO ZDEPARA_PERIODO_FOLHA
  FROM TFO
 ORDER BY 1 ;

SELECT * FROM ZDEPARA_PERIODO_FOLHA ;
