SELECT 
    'DELETE FROM ' + QUOTENAME(TABLE_NAME) + 
    ' WHERE ' + QUOTENAME(COLUMN_NAME) + 
    ' IS NULL;' AS SQL_DELETE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE 'ZDEPARA_%'
    AND ORDINAL_POSITION = 1
ORDER BY TABLE_NAME;