USE ZMIGRA_BOALOCACAO
GO

SELECT '001-Extração de DE-PARA-FUNCOES'		AS DADO,	COUNT(*) AS QTD FROM ZDEPARA_FUNCOES		UNION
SELECT '002-Extração de DE-PARA-SECOES'			AS DADO,	COUNT(*) AS QTD FROM ZDEPARA_SECOES			UNION
SELECT '003-Extração de DE-PARA-EVENTOS'		AS DADO,	COUNT(*) AS QTD FROM ZDEPARA_EVENTOS		UNION
SELECT '004-Extração de DE-PARA-SINDICATOS'		AS DADO,	COUNT(*) AS QTD FROM ZDEPARA_SINDICATOS		UNION
SELECT '005-Extração de DE-PARA-SITUACAO'		AS DADO,	COUNT(*) AS QTD FROM ZDEPARA_SITUACAO		UNION
SELECT '006-Extração de DE-PARA-BANCOS'			AS DADO,	COUNT(*) AS QTD FROM ZDEPARA_BANCOS			UNION
SELECT '007-Extração de DE-PARA-HORARIO'		AS DADO,	COUNT(*) AS QTD FROM ZDEPARA_HORARIO		UNION
SELECT '008-Extração de DE-PARA-PERIODO_FOLHA'	AS DADO,	COUNT(*) AS QTD FROM ZDEPARA_PERIODO_FOLHA	